### DISCUSSION TITLE
Fail to Load JS Files When Running on Docker with NGINX Reverse Proxy and Cloudflare SSL

### DISCUSSION THREAD

**Discussion by greekrode** [alexjustesen/speedtest-tracker#1030] [Q&A]
I install and run speedtest-tracker via docker compose
This is my docker compose file
```
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest
        environment:
            - PUID=1001
            - PGID=1001
            - DB_CONNECTION=pgsql
            - DB_HOST=host
            - DB_PORT=5432
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=username
            - DB_PASSWORD=password
        volumes:
            - speedtest-app:/config
            - '/home/kangritel/speedtest-tracker/web:/etc/ssl/web'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        networks:
          - nginx-network
volumes:
  speedtest-app:
networks:
  nginx-network:
    external: true
```

I'm using the nginx-network here as I'm setting up a reverse proxy using Nginx Proxy Manager with my setting looks like this
![image](https://github.com/alexjustesen/speedtest-tracker/assets/20609440/501abf01-71f5-436c-9b9b-c56a9a67f809)

Then, I'm using Cloudflare with the following settings
![image](https://github.com/alexjustesen/speedtest-tracker/assets/20609440/492650e7-f25a-48e8-bfe5-e87525636b90)

But, when I access the speedtest page, I received the following errors on my the console. 
Some parts of the page are broken, e.g. chart not showing, dropdown not working.

```
Mixed Content: The page at 'https://speedtest.host.com/' was loaded over HTTPS, 
but requested an insecure script 'http://speedtest.host.com/js/filament/widgets/components/chart.js?v=3.1.24.0'. 
This request has been blocked; the content must be served over HTTPS.
```
```
Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: 
http://speedtest.host.com/js/filament/widgets/components/chart.js?v=3.1.24.0
```

Is there any solution to fix this? I can't figure out what's wrong
