### DISCUSSION TITLE
v0.18.0 (Speedtest statuses + events, listeners and optimized queues)

### DISCUSSION THREAD

**Discussion by alexjustesen** [alexjustesen/speedtest-tracker#1274] [Releases]
## Description

This release focuses on completely refactoring how jobs are processed, adds more robust events, hooks listeners into the events and optimizes the jobs that land on the queue. This should make extending functionality a whole lot easier going forward.

## What's Changed
* [Bug] Fixed view created at timezone by @alexjustesen in https://github.com/alexjustesen/speedtest-tracker/pull/1262
* [Chore] Refactored executing Ookla speedtests and added new events by @alexjustesen in https://github.com/alexjustesen/speedtest-tracker/pull/1264
* [Chore] Refactored database notifications to their own listeners by @alexjustesen in https://github.com/alexjustesen/speedtest-tracker/pull/1266
* [Chore] Refactored webhook notifications to their own listeners by @alexjustesen in https://github.com/alexjustesen/speedtest-tracker/pull/1267
* [Bug] Result factory with fake data by @alexjustesen in https://github.com/alexjustesen/speedtest-tracker/pull/1268
* [Chore] Refactored mail notifications to their own listeners by @alexjustesen in https://github.com/alexjustesen/speedtest-tracker/pull/1269
* [Chore] Refactored Telegram notifications to their own listeners by @alexjustesen in https://github.com/alexjustesen/speedtest-tracker/pull/1270
* [Chore] Refactored Discord notifications to their own listeners by @alexjustesen in https://github.com/alexjustesen/speedtest-tracker/pull/1271
* [Chore] Refactored InfluxDBv2 data listener by @alexjustesen in https://github.com/alexjustesen/speedtest-tracker/pull/1272
* Release v0.18.0 by @alexjustesen in https://github.com/alexjustesen/speedtest-tracker/pull/1273

**Full Changelog**: https://github.com/alexjustesen/speedtest-tracker/compare/v0.17.3...v0.18.0

<hr /><em>This discussion was created from the release <a href='https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.18.0'>v0.18.0 (Speedtest statuses + events, listeners and optimized queues)</a>.</em>

**Comment by seh2000** [comment]
Just a small comment.
Before v0.18.0 one could manually start a test using the same server as set up speedtest servers.
Which was super as you got the same server thereby same result.
In v0.18.0 the function is different, the new function I presume just select e.g. the nearest sever which could give same of different result.   
Is there a way to pre-select the server the new function use?

![Screenshot 2024-03-01 090309](https://github.com/alexjustesen/speedtest-tracker/assets/74658646/e742768f-6d9e-4032-80f0-479e2e3b2d02)

![Screenshot 2024-03-01 090844](https://github.com/alexjustesen/speedtest-tracker/assets/74658646/822e0b74-a667-42bc-a9ef-77924cf52b44)

**Reply by alexjustesen** [reply]
Fix incoming: https://github.com/alexjustesen/speedtest-tracker/pull/1276

**Comment by seh2000** [comment]
I see the below "error" which happens at each run (30 minute)

`speedtest-tracker    | [2024-03-01 11:30:16] production.ERROR: Undefined array key "name" (View: /app/www/resources/views/emails/speedtest-threshold.blade.php) {"exception":"[object] (Illuminate\\View\\ViewException(code: 0): Undefined array key \"name\" (View: /app/www/resources/views/emails/speedtest-threshold.blade.php) at /app/www/storage/framework/views/22d4ed47ad8737f80809935408497e71.php:29)
speedtest-tracker    | [stacktrace]`

`speedtest-tracker    | [previous exception] [object] (ErrorException(code: 0): Undefined array key \"name\" at /app/www/storage/framework/views/22d4ed47ad8737f80809935408497e71.php:29)
speedtest-tracker    | [stacktrace]`

**Reply by alexjustesen** [reply]
@seh2000 I think this might have to do with the view cache, can you verify what you have as the cache driver as it should be `database` on my image but if you're using LSIO you can use `database` or `file`, I recommend `file`.

After that from the application's home directory run `php artisan cache:clear` and `php artisan view:clear` and restart the container, [docs](https://docs.speedtest-tracker.dev/other/commands) if you need help running CLI commands in the container.

**Reply by seh2000** [reply]
Hi Alex,
I am in deep water...
I am using your image (I assume) see below.
I tried to run the commands php artisan cache:clear and php artisan view:clear, but got "Could not open input file: artisan" I am sure I am doing something wrong, but not what it is.

```yaml
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8981:80'
            - '8943:443'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
#        mail:
            - MAIL_MAILER=smtp
            - MAIL_HOST=smtp-mail.outlook.com
            - MAIL_PORT=587
            - MAIL_USERNAME="my@outlook.com"
            - MAIL_PASSWORD="XXXXXXX"
            - MAIL_ENCRYPTION=tls
            - MAIL_FROM_ADDRESS="my@outlook.com"
            - MAIL_FROM_NAME="Speedtest Tracker"
#           - APP_DEBUG=true
        volumes:
#           - speedtest-app:/config
            - /home/admin/docker/speedtest-tracker
#           - '/path/to/directory/web:/etc/ssl/web'
        image: lscr.io/linuxserver/speedtest-tracker:0.18.0
#       image: 'ghcr.io/alexjustesen/speedtest-tracker:v0.16.6'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest_tracker
            - MARIADB_USER=speedy
            - MARIADB_PASSWORD=password
            - MARIADB_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
volumes:
# speedtest-app:
  speedtest-db:
```

Edited by @alexjustesen to make it easier to read
