### DISCUSSION TITLE
Running multiple speedtest-trackers instances using single postgres server with multiple databases

### DISCUSSION THREAD

**Discussion by TCS-UK** [alexjustesen/speedtest-tracker#1345] [Q&A] [answered]
As the title suggests. I am trying to run 4 instances of speedtest-tracker connecting to a single postgres server but with 4 individual databases.

I have all 4 instances starting and connecting to the relevant databases and am able to access the web interface of each instance for a short period until the docker vm host becomes unresponsive. I need to forcible stop the VM. The Docker host VM has plenty of resources available and I have each thrown an extra 16 cores at it just because I can.

Driving my nuts now. Anyone every tried running the speedtest-tracker in this manner and got it to work?

FYI:  Using custom postgres port 6543 Also tried postgres v15,15.6 & 16.2 alpine3.19 images

```
version: '3.4'
services:
    wan1-speed-tracker:
        container_name: wan1-speed-tracker
        networks:
          bwr-lab:
            ipv4_address: 192.168.254.101
        environment:
            - PUID=1000
            - PGID=1000
            - APP_DEBUG=true
            - APP_NAME="WAN1 (Truespeed) Speedtest Tracker"
            - PUBLIC_DASHBOARD=true
            - DB_CONNECTION=pgsql
            - DB_HOST=192.168.254.15
            - DB_PORT=6543
            - DB_DATABASE=wan1_speedtest_tracker_db
            - CACHE_DRIVER=database
            - DB_USERNAME=wan1_speedtest_user
            - DB_PASSWORD=thepassword
        volumes:
            - /var/lib/docker/bind_mounts/speedtest-tracker/wan1:/config
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
    wan2-speed-tracker:
        container_name: wan2-speed-tracker
        networks:
          bwr-lab:
            ipv4_address: 192.168.254.102
        environment:
            - PUID=1000
            - PGID=1000
            - APP_DEBUG=true
            - APP_NAME="WAN2 (Virgin) Speedtest Tracker"
            - PUBLIC_DASHBOARD=true
            - DB_CONNECTION=pgsql
            - DB_HOST=192.168.254.15
            - DB_PORT=6543
            - DB_DATABASE=wan2_speedtest_tracker_db
            - CACHE_DRIVER=database
            - DB_USERNAME=wan2_speedtest_user
            - DB_PASSWORD=thepassword
        volumes:
            - /var/lib/docker/bind_mounts/speedtest-tracker/wan2:/config
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
    wan3-speed-tracker:
        container_name: wan3-speed-tracker
        networks:
          bwr-lab:
            ipv4_address: 192.168.254.103
        environment:
            - PUID=1000
            - PGID=1000
            - APP_DEBUG=true
            - APP_NAME="WAN3 (Starlink) Speedtest Tracker"
            - PUBLIC_DASHBOARD=true
            - DB_CONNECTION=pgsql
            - DB_HOST=192.168.254.15
            - DB_PORT=6543
            - DB_DATABASE=wan3_speedtest_tracker_db
            - CACHE_DRIVER=database
            - DB_USERNAME=wan3_speedtest_user
            - DB_PASSWORD=thepassword
        volumes:
            - /var/lib/docker/bind_mounts/speedtest-tracker/wan3:/config
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
    wan4-speed-tracker:
        container_name: wan4-speed-tracker
        networks:
          bwr-lab:
            ipv4_address: 192.168.254.104
        environment:
            - PUID=1000
            - PGID=1000
            - APP_DEBUG=true
            - APP_NAME="WAN4 (Sky 4G) Speedtest Tracker"
            - PUBLIC_DASHBOARD=true
            - DB_CONNECTION=pgsql
            - DB_HOST=192.168.254.15
            - DB_PORT=6543
            - DB_DATABASE=wan4_speedtest_tracker_db
            - CACHE_DRIVER=database
            - DB_USERNAME=wan4_speedtest_user
            - DB_PASSWORD=thepassword
        volumes:
            - /var/lib/docker/bind_mounts/speedtest-tracker/wan4:/config
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped

networks:
  bwr-lab:
    external: true
```
