### DISCUSSION TITLE
swapped to the new linuxserver builds and got a weird error, nothing works.

### DISCUSSION THREAD

**Discussion by derekcentrico** [alexjustesen/speedtest-tracker#1430] [Q&A] [answered]
So, at first I did a hot swap of just the docker image path.  Then, I tried to change the docker-compose to be like the Linuxserver.io example.  Finally, I deleted everything including the mapped volume directory to start fresh.  Still no go.  I'm at a loss.  Not dropping it as a bug since this build has been out a few days and no one else has brought it up.  I'm guessing it is something dumb I'm overlooking from the switch over....

Docker log:
```
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
speedtest-tracker: https://github.com/sponsors/alexjustesen
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    996
───────────────────────────────────────
using keys found in /config/keys
find: ‘/app/www/bootstrap/cache’: No such file or directory
find: ‘/app/www/storage’: No such file or directory
**** Permissions could not be set. This is probably because your volume mounts are remote or read-only. ****
**** The app may not work properly and we will not provide support for it. ****
ln: failed to create symbolic link '/app/www/.env': No such file or directory
Could not open input file: /app/www/artisan
Could not open input file: /app/www/artisan
Could not open input file: /app/www/artisan
[custom-init] No custom files found, skipping...
./run: line 4: cd: /app/www: No such file or directory
[ls.io-init] done.
./run: line 4: cd: /app/www: No such file or directory
./run: line 4: cd: /app/www: No such file or directory
./run: line 4: cd: /app/www: No such file or directory
./run: line 4: cd: /app/www: No such file or directory
./run: line 4: cd: /app/www: No such file or directory
./run: line 4: cd: /app/www: No such file or directory
```

Original docker-compose:
```
  speedtest:
    container_name: speedtest
    image: lscr.io/linuxserver/speedtest-tracker:latest
    volumes:
      - /home/docker/speedtest/config:/config
      - /home/docker/speedtest/app:/app
    environment:
      - PUID=1000
      - PGID=140
      - TZ="America/New_York"
      - PHP_POOL_NAME="speedtest-tracker_php"
      - DB_CONNECTION="sqlite"
      - DB_DATABASE="/config/database.sqlite"
      - APP_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    restart: unless-stopped
```

Changed one:
```
  speedtest:
    container_name: speedtest
    image: lscr.io/linuxserver/speedtest-tracker:latest
    volumes:
      - /home/docker/speedtest/config:/config
      - /home/docker/speedtest/app:/app
    environment:
      - PUID=1000
      - PGID=140
      - TZ=America/New_York
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/config/database.sqlite
      - APP_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    restart: unless-stopped
```

Not sure what's up here.  Anyone have a thought on solving?
