### DISCUSSION TITLE
SQLite '400 Bad Request'

### DISCUSSION THREAD

**Discussion by meelokun** [alexjustesen/speedtest-tracker#145] [Q&A] [answered]
Copy and pasting your docker-compose into my existing docker-compose file is proving to be challenging. Admittingly, I'm a bit of a docker novice. I have been successful in loading various docker containers via docker-compose, but yours contains code/structure ive never come across before in a docker-compose.

I get the following when attempting to pull. (i put yours at the top of my docker compose file for convenience...

![image](https://user-images.githubusercontent.com/1051664/201435494-9fb12b0f-a60c-4b43-95ba-5332cde853b1.png)

I'm wondering if its just a spacing issue... Noticed theres varing amounts of spacing as compared to all my other containers in my compose file.

Also - i hope this is ok, but i did deviate and changed the app_port to 8765 (coping the predecessor)

I'm running a Synology DS1621+ NAS (DSM 7.1.1)

![image](https://user-images.githubusercontent.com/1051664/201435365-3d38d2f0-ca61-4dec-a8a7-46ab88c12656.png)

**Comment by alexdelprete** [comment, marked as answer]
Check the docs site for the official examples: https://docs.speedtest-tracker.dev/getting-started/installation#install-with-docker-compose

Choose the one based on the database you want to use.

Just as an example, this is my docker-compose, with 2 space indentation (doesn't make much difference), using an external database (MariaDB):

```yaml
version: '3.3'
services:
  speedtest-tracker:
    image: ghcr.io/alexjustesen/speedtest-tracker:v0.3.0
    container_name: speedtest-tracker
    restart: unless-stopped
    ports:
      - 8008:443
    environment:
      TZ: Europe/Rome
      PUID: 1000
      PGID: 1000
      DB_CONNECTION: mysql
      DB_HOST: mariadb.domain.local
      DB_PORT: 3306
      DB_DATABASE: speedtest_tracker
      DB_USERNAME: db_user
      DB_PASSWORD: db_pw
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/config:/config
      - $PWD/certs:/etc/ssl/web
```

**Reply by meelokun** [reply]
Alright - so i got MariaDB installed via the package center - i missed that this is a dependency (i tried sqlite, but it was giving me problems, and i couldnt figure out how to change the ports and make it work (any combination resulted it no connection), i believe the inclusion of nginx is conflicting with the one built into the Synology NAS (my best guess)

heres why i think that wont work
![image](https://user-images.githubusercontent.com/1051664/201458974-9ab63b94-b999-474a-8ef4-49aa7ed4fc40.png)
![image](https://user-images.githubusercontent.com/1051664/201458987-301ee50e-6d2b-4814-8e7b-124428650935.png)


Heres my docker compose - as copied from yours above, and slightly adapted to my needs.

```
  speedtest-tracker:
    image: ghcr.io/alexjustesen/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    ports:
      - 8008:443
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: speedtest_tracker
      DB_USERNAME: root
      DB_PASSWORD: Password
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/speedtracker/config:/config

```

when trying to go to https://NASIP:443 - it simply redirects me to the NAS's https site at NASIP:5001

With port https://NASIP:8008
![image](https://user-images.githubusercontent.com/1051664/201459196-1d3986b4-6b94-45ab-b6a7-74b42ef82e7b.png)

Caveat* I have **no** experience with MariaDB - but theres no real configuration, other than the Port and password

![image](https://user-images.githubusercontent.com/1051664/201458735-4973f35b-1915-4ed8-9674-a4b9883a2aa7.png)

I checked the logs, and theres lots of problems... 

Pastebin https://pastebin.com/WJrPENYn
