### DISCUSSION TITLE
Proper timezone set, time records are wrong

### DISCUSSION THREAD

**Discussion by cmdshft** [alexjustesen/speedtest-tracker#1538] [Q&A] [answered]
I have my timezone set in the docker-compose as `- APP_TIMEZONE=America/New_York` and as of this post, it's approximately 11:30pm for me. I ran a speedtest at that time and the time is recorded as `Jun 15 - 3:20` (though it's still Jun 14th for me).

I made sure that my timezone settings on my server are correct as well.

![image](https://github.com/alexjustesen/speedtest-tracker/assets/8571823/744f2388-06d0-464b-a4f8-78a588d9f884)

Here is my full compose as well:

```
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8080:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=*********
            - DB_CONNECTION=sqlite
            - APP_URL=http://localhost
            - SPEEDTEST_SCHEDULE=0 */2 * * *
            - SPEEDTEST_SERVERS=16071
            - PRUNE_RESULTS_OLDER_THAN=30
            - APP_TIMEZONE=America/New_York
        volumes:
            - /home/ubuntu/stt/data:/config
            - /home/ubuntu/stt/keys:/keys
        image: lscr.io/linuxserver/speedtest-tracker:0.20.6
        restart: unless-stopped
```
