### DISCUSSION TITLE
UI says no speedtest scheduled.

### DISCUSSION THREAD

**Discussion by SodaSyrup** [alexjustesen/speedtest-tracker#1619] [Q&A] [answered]
Hello, i setup in the enviroments a cron schedule, after restarting the container it says "No speedtest scheduled." in the UI. Is this just a "bug" or does it need to run the first scheduled one? how would i test if the schedule actually works? 
```- SPEEDTEST_SCHEDULE=0 */2 * * *```

**Comment by svenvg93** [comment]
If it says this there can be a few problems 
- the environment variable is not pick up by the container. 
- the cron job is not valid 

the cron job looks fine. 
did you try with another one just to be sure? 
For example `6 */2 * * *` 

can you share your full docker compose

**Reply by SodaSyrup** [reply]
```
version: "3.3"
services:
  speedtest-tracker:
    container_name: speedtest-tracker
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - SPEEDTEST_SCHEDULE=0 */2 * * *
      - PUID=1000
      - PGID=1000
      - APP_KEY=base64:zecrTD9t7XyBp0PMGgBzYjap5/84uh7wyLQRYbNNTSU=
      - DB_CONNECTION=sqlite
      - APP_TIMEZONE=Europe/Berlin
      - DISPLAY_TIMEZONE=Europe/Berlin
    volumes:
      - /path/to/data:/config
    image: lscr.io/linuxserver/speedtest-tracker:latest
networks: {}
```
