### DISCUSSION TITLE
No speedtest result shown

### DISCUSSION THREAD

**Discussion by mau-hm** [alexjustesen/speedtest-tracker#1625] [Q&A] [answered]
Hi all,

Until June 29th, I had my speedtest-tracker working flawlessly, then after updating and using my next docker compose code I cannot see any speedtest result, I have re-deployed and updated with several changes but it does not run the speedtests.

```
version: '3.4'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8080:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=base64:prc1PNfuJF7fZqNGS7EGO6E+bWdnd2T9jH4nErMC2b8=
            - DB_CONNECTION=sqlite
            - SPEEDTEST_SCHEDULE=0 */2 * * *
            - APP_TIMEZONE=America/Mexico_City
            - TZ=America/Mexico_City
            - DISPLAY_TIMEZONE=America/Mexico_City
            - TELEGRAM_BOT_TOKEN=
        volumes:
            - './path/to/data:/config'
            - './path/to-custom-ssl-keys:/config/keys'
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
```

**Comment by svenvg93** [comment]
Hi @wolfpackspartan 

in the volume section your don’t have the paths defined it’s still using the placeholders

**Reply by mau-hm** [reply]
Hi @svenvg93

Thanks for your help, is there any specific path? I've tried with /home/docker/ and I see that all the config is also being created.

With yml above I actually see the config being created too, I don't know if there's an specific path.

**Reply by svenvg93** [reply]
No every path should work as long as the app can write into it. But as in the yml it still has the placeholder I always double check

**Reply by mau-hm** [reply]
I can access and change the settings through the user interface and they are being applied successfully but no speedtest run are executed, I assume that if changes in settings are being stored the app has actually rights to write in the path.

**Reply by seh2000** [reply]
I am no expert, but shouldn't the actual speed test server be there...

**Reply by svenvg93** [reply]
If there none defined it will auto pick one

**Comment by svenvg93** [comment]
Can you run a Speedtest manual? Do you see the schedule in the gui? Like the “next run at”

**Reply by mau-hm** [reply]
Manual test doesn't show any result, neither the schedule one.

![Screenshot_20240726_092354_Brave.jpg](https://github.com/user-attachments/assets/21572662-0ce5-4d1e-94a0-cfb65440e3c2)

![Screenshot_20240726_092340_Brave.jpg](https://github.com/user-attachments/assets/276881af-7ab3-4a1d-91b6-c4f7cfd1b45b)

![Screenshot_20240726_092512_Brave.jpg](https://github.com/user-attachments/assets/1893630d-2374-4e11-ad98-1e53e1c0bb6d)

![Screenshot_20240726_092519_Brave.jpg](https://github.com/user-attachments/assets/569c045d-a617-41d8-ba1c-1faca55ae0cf)

**Reply by svenvg93** [reply]
Can you try with the last release 0.20.8?

**Reply by mau-hm** [reply]
I re-deployed using next image and results are still empty,

`        image: lscr.io/linuxserver/speedtest-tracker:0.20.8
`

![image](https://github.com/user-attachments/assets/14e04cf3-43dd-4872-8113-7c8334671c33)

**Reply by svenvg93** [reply]
Sorry for the late reply, I missed your comment. 
In case you still have problems. Can you go into the container and run `speedtest --accept-license --accept-gdpr`. Is to check if the container can start the test at all.

**Reply by mau-hm** [reply]
Hi @svenvg93 after a last update it started working this morning, I didn't do anything, I only restarted my raspberry pi after a energy power loss.

Thanks for your support!!

**Comment by SpiderMANek** [comment]
Hi, all...
I am totally noobish in Linux, and begginer in Portainer and Docker.
I have deployed some useful Dockers on my homeserver, one of them is SpeedTest-Tracker.
I'm having the same issue. I don't have any results. Could somebody tell me what to do to fix it?
I tried to deploy newest version 0.21.2, but still have version 0.20.7, and still have the same issue with no test results...


```
---
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - APP_KEY=base64:M8PxuoQvSLB8PzA2eC711h5WZZxc7d7gq+/gpDtX59Q=
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE=30 */1 * * *
      - SPEEDTEST_SERVERS=5134,7175,9510,7481,1958,8123,15315#
      - DB_HOST= #optional
      - DB_PORT= #optional
      - DB_DATABASE= #optional
      - DB_USERNAME= #optional
      - DB_PASSWORD= #optional
      - DISPLAY_TIMEZONE=Etc/UTC #optional
      - PRUNE_RESULTS_OLDER_THAN=0 #optional
      - DATETIME_FORMAT="j.M.Y, G:i:s"
      - CHART_DATETIME_FORMAT="j.M, G:i:s"
      - APP_DEBUG=true
    volumes:
      - /srv/dev-disk-by-uuid-fcfa1630-62f2-4fbe-b8eb-f1c57f444dfa/cache_ssd/Docker/Data/Speedtest-Tracker/data:/config
    ports:
      - 8765:80
    restart: unless-stopped
```

![ST_NoResults](https://github.com/user-attachments/assets/25a83359-cba4-44d9-a2be-9b3473fadd69)
