### DISCUSSION TITLE
Email Notifications Version 0.21.2

### DISCUSSION THREAD

**Discussion by ric-m** [alexjustesen/speedtest-tracker#1692] [Q&A] [answered]
Added the following to the compose.yaml file to receive notifications. Testing shows the "email sent" message, but no email ever arrives.
Here's the environment section of the compose file:

```
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=base64:H<rest of app_key string deleted>
            - APP_URL=http://localhost
            - DB_CONNECTION=sqlite
            - SPEEDTEST_SCHEDULE="0,30 * * * *"	# every 30 mins, on the hour and half-past
            - DISPLAY_TIMEZONE="Europe/London"
            - MAIL_MAILER=smtp
            - MAIL_HOST=smtp.gmail.com
            - MAIL_PORT=465
            - MAIL_USERNAME=someuser@gmail.com
            - MAIL_PASSWORD="somepassword"
            - MAIL_ENCRYPTION=tls
            - MAIL_FROM_ADDRESS=someuser@gmail.com
            - MAIL_FROM_NAME="Speedtest Tracker"
```
         
The password contains special characters "%" and "&". Even if these are escaped with a $ prefix, emails never arrive. The recipient is also added to the Mail section of "Notifications".

I'm also struggling with Telegram, but I'll save that for a separate thread.

Any and all help greatly appreciated.

Ric
PS: love the speedtest app - impressive.

**Comment by shalak** [comment]
What do the logs say, when you run the test email?

What I would try is to move the secrets to the `speedtest.env` file, remove them from `environment` key in compose and add `env_file: speedtest.env` instead.

**Reply by ric-m** [reply]
The logs are (and always have been) unremarkable:

```
user@host:/opt/stacks/speedtest $ docker logs -f speedtest-tracker
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done

Brought to you by linuxserver.io

To support the app dev(s) visit:
speedtest-tracker: https://github.com/sponsors/alexjustesen

To support LSIO projects visit:
https://www.linuxserver.io/donate/

GID/UID
User UID:    1000
User GID:    1000

Linuxserver.io version: v0.21.2-ls43
Build-date: 2024-08-24T21:21:31+00:00
using keys found in /config/keys
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```
There is no speetdtest.env file: I shall puruse the 2nd part of your response later in the day.
Many thanks,
Ric

**Reply by ric-m** [reply]
Hi
I made the changes. This is the compose.yaml:
```
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=base64:H<deleted>
            - APP_URL=http://localhost
            - DB_CONNECTION=sqlite
            - SPEEDTEST_SCHEDULE="0,30 * * * *"
            - DISPLAY_TIMEZONE="Europe/London"
            - ENV_FILE=speedtest.env
            # - MAIL_MAILER=smtp
            # - MAIL_HOST=smtp.gmail.com
            # - MAIL_PORT=465
            # - MAIL_USERNAME=someuser@gmail.com
            # - MAIL_PASSWORD="somepassword"
            # - MAIL_ENCRYPTION=tls
            # - MAIL_FROM_ADDRESS=someuser@gmail.com
            # - MAIL_FROM_NAME="Speedtest Tracker"
```
and this is `speedtest.env` (located in `/opt/stacks/speedtest/data/.config`):
```
MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=465
MAIL_USERNAME=someuser@gmail.com
MAIL_PASSWORD="somepassword"
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=someuser@gmail.com
MAIL_FROM_NAME="Speedtest Tracker"
```
Again, nothing reported in the logs; no email received.
Ric

**Reply by shalak** [reply]
`speedtest.env` should be located in the same directory as your compose file.

The `env_file` is a key in compose, not an environment variable. Here's how this should look like:

```
env_file:
    - speedtest.env
environment:
    - PUID=1000
    - PGID=1000
    - APP_KEY=base64:H<deleted>
    - APP_URL=http://localhost
    - DB_CONNECTION=sqlite
    - SPEEDTEST_SCHEDULE="0,30 * * * *"
    - DISPLAY_TIMEZONE="Europe/London"
```

Or even better, use key-value mapping instead of list:
```
env_file:
    - speedtest.env
environment:
    PUID: 1000
    PGID: 1000
    APP_KEY: base64:H<deleted>
    APP_URL: http://localhost
    DB_CONNECTION: sqlite
    SPEEDTEST_SCHEDULE: "0,30 * * * *"
    DISPLAY_TIMEZONE: "Europe/London"
```
(that way you'll have an immediate error with env duplicates)

As for the logs - check them while sending the test email.

Are you hosting this on your local machine, and you expose port 80? Because it you don't, the `APP_URL=http://localhost` makes no sense.

As a side-note: it's recommended not to run speed tests on full hours, i.e. I'd suggest tuning your cron to e.g. `7,37 * * * *` - lot's of people run at full hours, to the results might be scewed because of ookla loads ;)

**Reply by ric-m** [reply]
Thank you for that. I have made the changes using the key-value mapping and ensured speedtest.env is located alongside the docker compose file. I've double-checked the password and yes, port 80 is open but unused (it returns a 403 Forbidden message).

Logs were checked whils sending emails and remain stubbornly quiet, no no obvious errors.
Speedtest is hosted on a Raspberry Pi, latest OS, 64 bit.

Regards,
Ric

**Reply by shalak** [reply]
Also, another note:

> Even if these are escaped with a $ prefix, emails never arrive

I'm not 100% sure, but I recall, that escaping with `$` is only for `$` itself, i.e. when you want to pass literal `$SOMETHING` (and not the `SOMETHING` env variable value), you'd use `$$SOMETHING`. 

For YAML, depending on parser implementation, you need to escape some characters, but as a general rule of thumb you should always put them in quotes, e.g. instead this:

```yaml
main_key:
  key1: colon:example
  key2: hash#example
  key3: curly_braces{example}
  key4: curly_braces}example
  key5: square_brackets[example]
  key6: square_brackets]example
  key7: comma,example
  key8: ampersand&example
  key9: asterisk*example
  key10: exclamation!example
  key11: pipe|example
  key12: greater_than>example
  key13: single_quote'example
  key14: percent%example
  key15: at@example
  key16: backslash\example
  key17: double_quote"example
```

it's safer to go like this:
```yaml
main_key:
  key1: "colon:example"
  key2: "hash#example"
  key3: "curly_braces{example}"
  key4: "curly_braces}example"
  key5: "square_brackets[example]"
  key6: "square_brackets]example"
  key7: "comma,example"
  key8: "ampersand&example"
  key9: "asterisk*example"
  key10: "exclamation!example"
  key11: "pipe|example"
  key12: "greater_than>example"
  key13: "single_quote'example"
  key14: "percent%example"
  key15: "at@example"
  key16: "backslash\example"
  key17: 'double_quote"example'
```
Notice that double-quote is single-quoted, also this is a hint only for YAML maps, not array-lists, nor the `.env` file.

However, when it comes to the `.env` files, I think it may be a completely different parser.

In general, that's why I hate "special character" requirement in passwords. I believe the best way is to only use alphanumeric characters, and even exclude homoglyphs (i.e. l, I, 1, O, 0) - just make the passwords 128 chars long ;)
