### DISCUSSION TITLE
production.ERROR: Failed to fetch external IP address.

### DISCUSSION THREAD

**Discussion by affix2711** [alexjustesen/speedtest-tracker#1980] [Q&A]
When I try to start a speedtest I get this error in the logs: `19:20:30] production.ERROR: Failed to fetch external IP address. ["cURL error 28: Resolving timed out after 5000 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://icanhazip.com/"] `

This is my compose file: 
```
services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        container_name: speedtest-tracker
        ports:
            - 8084:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=***
            - DB_CONNECTION=sqlite
        volumes:
            - /mnt/docker/speedtest:/config
  ```
            
I tried it with and without a reverse proxy and neither seem to work.
I also disabled blocking in Pi-Hole, which also didn't work.
