### DISCUSSION TITLE
Home Assistant Integration using Webhooks

### DISCUSSION THREAD

**Discussion by bubtheengineer** [alexjustesen/speedtest-tracker#1991] [Q&A]
Not sure if this has been mentioned, but if you want to integrate the speedtest-tracker with Home Assistant there's a super simple way to do it using webhooks.
The only thing you need to change are the parts in <>.  And create a unique webhook to link the two services together.

You'll configure a webhook in speedtest-tracker under notifications with the following URL:

`https://<homeassistant>:<port>/api/webhook/<unique-webhook>`

Then you add some template sensors to your HA config.yaml, like so:

```
template:
  - trigger:
      - platform: webhook
        webhook_id: <unique-webhook>
    sensor:
      - name: "Speedtest Download"
        state: "{{ (trigger.json.download / 1024 / 1024) | round(2) }}"
        state_class: measurement
        unit_of_measurement: "Mbps"
      - name: "Speedtest Upload"
        state: "{{ (trigger.json.upload / 1024 / 1024) | round(2) }}"
        state_class: measurement
        unit_of_measurement: "Mbps"
      - name: "Speedtest Ping"
        state: "{{ trigger.json.ping | round(2) }}"
        state_class: measurement
        unit_of_measurement: "ms"
      - name: "Speedtest Packet Loss"
        state: "{{ trigger.json.packetLoss }}"
        state_class: measurement
        unit_of_measurement: "%"
      - name: "Speedtest ISP"
        state: "{{ trigger.json.isp }}"
      - name: "Speedtest Result URL"
        state: "{{ trigger.json.speedtest_url }}"
```

And that's it!  After restarting HA, run a speedtest and you'll start seeing the data show up in HA.

*Edited to add the state_class so you get measurement statistics calculated in HA

**Comment by alexjustesen** [comment]
Instead of defining the state and and unit of measurement couldn't you use the new `download/upload_bits_human`?

https://docs.speedtest-tracker.dev/api/v1#data-dictionary

**Comment by bubtheengineer** [comment]
This integration is using the speedtest webhook, and I don't see that data being sent as part of the json body.  This is what I receive in HA when the webhook is called:

```
  json:
    result_id: 31
    site_name: Speedtest Tracker
    isp: Brightspeed
    ping: 8.585
    download: 933175808
    upload: 863484176
    packetLoss: 0
    speedtest_url: https://www.speedtest.net/result/c/<uuid>
    url: http://localhost/admin/results
```

Also, parsing a string with uom into the HA sensor values is harder than using the int values, afaik.

**Reply by alexjustesen** [reply]
I completely misread that and thought you were hitting the new API endpoints.

**Comment by Thunder7ga** [comment]
Nice...works well...how would I round the upload/download numbers, right now they are showing at like 15 decimals :)  That's a lot of numbers.  The nearest whole or hundredth of a percent would be more than adequate.

**Reply by bubtheengineer** [reply]
Thanks, glad it was able to help someone else.

I didn't even notice the crazy number of decimals, the trend must automatically truncate to two digits.  I fixed it above, just missing some paranthesis to apply the rounding to the result of the calclulation:
`state: "{{ (trigger.json.upload / 1024 / 1024) | round(2) }}"`

You can adjust the 'round' function to control the number of digits to the right of the decimal.

**Reply by Thunder7ga** [reply]
Perfect..thanks.  It works as intended now.

**Comment by Hechamon** [comment]
The webhook data seems to have changed in the meantime, I had to update the trigger a little to make it work.
If anybody happens upon this thread, here is the trigger that worked for me:

```yaml
- trigger:
    - platform: webhook
      webhook_id: speedtest-tracker
  sensor:
    - name: "Speedtest Download"
      state: "{{ (trigger.json.download / 1024 / 1024) | round(2) }}"
      state_class: measurement
      unit_of_measurement: "Mbps"
      unique_id: speedtest-download
    - name: "Speedtest Upload"
      state: "{{ (trigger.json.upload / 1024 / 1024) | round(2) }}"
      state_class: measurement
      unit_of_measurement: "Mbps"
      unique_id: speedtest-upload
    - name: "Speedtest Ping"
      state: "{{ trigger.json.ping | round(2) }}"
      state_class: measurement
      unit_of_measurement: "ms"
      unique_id: speedtest-ping
    - name: "Speedtest Packet Loss"
      state: "{{ trigger.json.packet_loss }}"
      state_class: measurement
      unit_of_measurement: "%"
      unique_id: speedtest-packet-loss
    - name: "Speedtest ISP"
      state: "{{ trigger.json.isp }}"
      unique_id: speedtest-isp
    - name: "Speedtest Result URL"
      state: "{{ trigger.json.url }}"
      unique_id: speedtest-result-url
```
