### DISCUSSION TITLE
cant reach webinterface when connected to vpn

### DISCUSSION THREAD

**Discussion by swinxx** [alexjustesen/speedtest-tracker#2093] [Q&A]
**Describe the bug**
I run speedtest tracker latest image on my synolog nas.
it works while running on eth0 interface when my vpn is not connected

my homenetwork is not reachable from outside the network. thats what i want. 

but i want my nas to connect to the internet on port 80 and 443 only with vpn. I have a script that marks all my 80 and 443 traffic from the host and docker networks and sends the traffic over to the vpn tunnel. as soon as i connect to my vpn the webgui from speedtest tracker is not reachable anymore. 

the interesting thing is, that only the speedtest tracker service is not working anymore. other services in the same network are working as expected. 

before the last updates (speedtest tracker and docker compose) everything worked as expected. 

can i do anything to reach to the gui while connected to the vpn tunnel?

**Comment by svenvg93** [comment]
Can you share your docker compose? As well can you reach the UI when locally on the same network? I doubt it has anything to do with the application itself, sounds more of a (docker) networking problem.

**Comment by swinxx** [comment]
No chance i can reach the gui. not with the IP Adress, and not with the Subdomain (Reverse Proxy).
I have used a portainer stack to install the service. 

here is the yaml

```
services:
  db:
    image: postgres:17
    container_name: SpeedTest-TRACKER-DB
    hostname: speedtestracker-db
    networks:
      - Default_Docker
    mem_limit: 1g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "speedtest", "-U", "speedtestuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume4/docker/speedtest/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: speedtest
      POSTGRES_USER: speedtestuser
      POSTGRES_PASSWORD: speedtestpass
    restart: on-failure:5
  speedtest-tracker:
    image: ghcr.io/linuxserver/speedtest-tracker:latest
    container_name: SpeedTest-TRACKER
    networks:
       - Default_Docker
    healthcheck:
     test: curl -f http://localhost:80/ || exit 1
    environment:
       PUID: 1026
       PGID: 100
       APP_TIMEZONE: Europe/Vienna
       DISPLAY_TIMEZONE: Europe/Vienna
       APP_KEY: base64:xyz= #docker exec speedtest-tracker php /app/www/artisan key:generate --show
       APP_URL: https://speedt.blackb.one
       ASSET_URL: https://speedt.blackb.one
       TRUSTED_PROXIES: 0.0.0.0/0
       DB_CONNECTION: pgsql
       DB_HOST: speedtestracker-db
       DB_PORT: 5432
       DB_DATABASE: speedtest
       DB_USERNAME: speedtestuser
       DB_PASSWORD: speedtestpass
    volumes:
      - /volume4/docker/speedtest/config:/config:rw
    ports:
      - 8998:80
    restart: on-failure:5
networks:
  Default_Docker:
    external: true
```
