### DISCUSSION TITLE
v0.11.1

### DISCUSSION THREAD

**Discussion by alexjustesen** [alexjustesen/speedtest-tracker#364] [Releases]
## What's Changed
* delete speedtest results from the UI by @alexjustesen in https://github.com/alexjustesen/speedtest-tracker/pull/321
* Added versioned tag alongside latest on docker-hub deployment by @UnAfraid in https://github.com/alexjustesen/speedtest-tracker/pull/330
* Require recipient Telegram and validate bot token by @garanda21 in https://github.com/alexjustesen/speedtest-tracker/pull/324
* removed auth message by @alexjustesen in https://github.com/alexjustesen/speedtest-tracker/pull/340
* Added support  X-Forwarded-Prefix+TrustedProxies by @alexdelprete in https://github.com/alexjustesen/speedtest-tracker/pull/342
* Release 0.11.1 by @alexjustesen in https://github.com/alexjustesen/speedtest-tracker/pull/363

**Full Changelog**: https://github.com/alexjustesen/speedtest-tracker/compare/v0.11.0...v0.11.1

<hr /><em>This discussion was created from the release <a href='https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.11.1'>v0.11.1</a>.</em>

**Comment by alexjustesen** [comment]
**Important on this release**: #342 removes proxy restrictions from the application which _should_ resolve some of the proxy issues I've been seeing.

If you have issues with this release please post in the comments below 👇

**Comment by lfac76** [comment]
Hello Alex,

After the update, I received the error message:

502 Bad Gateway
openresty

How can I find the problem? 

Thanks a lot.

**Reply by alexjustesen** [reply]
Are you getting this in the browser or in logs?

**Reply by lfac76** [reply]
In the browser.

**Reply by lfac76** [reply]
The container is restarting after 10 seconds up.

5d6e0c5711c1   ghcr.io/alexjustesen/speedtest-tracker:latest   "/init"                  2 hours ago    Restarting (1) Less than a second ago

**Reply by lfac76** [reply]
Here is my files. Anything to change? Before update it was everything great!

docker-compose.yml:
```
---
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8888:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - /home/luiz/docker_volumes/speedtest-tracker/config:/config
        image: ghcr.io/alexjustesen/speedtest-tracker:latest
        restart: unless-stopped
```

And .env:
```
APP_NAME="Speedtest` Tracker"
APP_ENV=production
APP_KEY=xxxxxxxxxxxxxxxxxxxxxxxxx
APP_DEBUG=false
APP_URL=http://localhost

LOG_CHANNEL=stderr
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=sqlite
# DB_HOST=127.0.0.1
# DB_PORT=3306
# DB_DATABASE=speedtest_tracker
# DB_USERNAME=root
# DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database
SESSION_DRIVER=database
SESSION_LIFETIME=120

MAIL_MAILER=smtp
MAIL_HOST=mailhog
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

TELEGRAM_BOT_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Reply by alexdelprete** [reply]
are you using a reverse proxy?

**Reply by lfac76** [reply]
Yes, but I tried to connect directly too.

The container stays in loop after starts.

**Reply by alexdelprete** [reply]
can you show the logs please? the container log, so we can check the startup phase...

are you sure that accessing directly doesn't work? how are you accessing it directly? show us the screenshot of the browser with the url etc.

thanks.

**Reply by alexdelprete** [reply]
Works fine here:

```
--------------------------------------------------------------------
 ____                             ____  _     _        _   _
/ ___|  ___ _ ____   _____ _ __  / ___|(_) __| | ___  | | | |_ __
\___ \ / _ \  __\ \ / / _ \  __| \___ \| |/ _` |/ _ \ | | | |  _ \
 ___) |  __/ |   \ V /  __/ |     ___) | | (_| |  __/ | |_| | |_) |
|____/ \___|_|    \_/ \___|_|    |____/|_|\__,_|\___|  \___/| .__/
                                                            |_|
Brought to you by serversideup.net
--------------------------------------------------------------------
To support Server Side Up projects visit:
https://serversideup.net/sponsor
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
🏃‍♂️ Checking for Laravel automations...
🔐 Linking the storage...
🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...
   INFO  The [public/storage] link has been connected to [storage/app/public].
🐇  Configuring Speedtest Tracker...
✅  Environment file exists
🔗  Creating symlinks to config and log files
✅  App key exists
🔒  Fixing app path file permissions
💰  Building the cache...
[28-Jan-2023 18:03:05] NOTICE: fpm is running, pid 101
[28-Jan-2023 18:03:05] NOTICE: ready to handle connections
[28-Jan-2023 18:03:05] NOTICE: systemd monitor interval set to 10000ms
🚛  Migrating the database...
✅  All set, starting Speedtest Tracker container...
⏰  Starting the cron service...
💪  Starting the queue worker...
10.1.10.30 - - [28/Jan/2023:18:04:21 +0100] "GET / HTTP/2.0" 302 386 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.0.0"
10.1.10.30 - - [28/Jan/2023:18:04:22 +0100] "GET /admin HTTP/2.0" 200 21155 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.0.0"
```

**Reply by lfac76** [reply]
> can you show the logs please? the container log, so we can check the startup phase...
> 
> are you sure that accessing directly doesn't work? how are you accessing it directly? show us the screenshot of the browser with the url etc.
> 
> thanks.

Container log:
```
--------------------------------------------------------------------
 ____                             ____  _     _        _   _
/ ___|  ___ _ ____   _____ _ __  / ___|(_) __| | ___  | | | |_ __
\___ \ / _ \  __\ \ / / _ \  __| \___ \| |/ _` |/ _ \ | | | |  _ \
 ___) |  __/ |   \ V /  __/ |     ___) | | (_| |  __/ | |_| | |_) |
|____/ \___|_|    \_/ \___|_|    |____/|_|\__,_|\___|  \___/| .__/
                                                            |_|

Brought to you by serversideup.net
--------------------------------------------------------------------

To support Server Side Up projects visit:
https://serversideup.net/sponsor
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

🏃‍♂️ Checking for Laravel automations...
🔐 Linking the storage...
🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...
[2023-01-28 16:46:32] production.ERROR: The /var/www/html/bootstrap/cache directory must be present and writable. {"exception":"[object] (Exception(code: 0): The /var/www/html/bootstrap/cache directory must be present and writable. at /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php:178)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(137): Illuminate\\Foundation\\PackageManifest->write()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(107): Illuminate\\Foundation\\PackageManifest->build()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(90): Illuminate\\Foundation\\PackageManifest->getManifest()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(79): Illuminate\\Foundation\\PackageManifest->config()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php(26): Illuminate\\Foundation\\PackageManifest->aliases()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(242): Illuminate\\Foundation\\Bootstrap\\RegisterFacades->bootstrap()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(383): Illuminate\\Foundation\\Application->bootstrapWith()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(153): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#8 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#9 {main}
"}

In PackageManifest.php line 178:

  The /var/www/html/bootstrap/cache directory must be present and writable.


s6-rc: warning: unable to start service laravel-automations: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
s6-linux-init-shutdown: fatal: unable to talk to shutdownd: Operation not permitted
```

**Reply by alexdelprete** [reply]
filesystem error...does the PID: 1000 PGID: 1000 have permission to the config folder?

BTW: If docker-compose file is in the `/home/luiz/docker_volumes/speedtest-tracker` folder you can optimize the volume mapping like this:

```yaml
          volumes:
            - $PWD/config:/config
```

@alexjustesen I've seen other reports for other versions with this cache permission issue, how did they solve in the end?

**Reply by InertiaImpact** [reply]
I am also seeing the same issue of the "must be present and writable" directory. Docker, definitely has perms.

Have tried wiping and re-deploying the stack from scratch several times now. Would appreciate some guidance. 
Thanks!

**Comment by lfac76** [comment]
Telegram notification was working...

![image](https://user-images.githubusercontent.com/83482904/215278809-2861c16c-d60c-428f-bc59-b51fbcecf672.png)

**Comment by lfac76** [comment]
I deleted everything, recreate and now it works.

**Reply by alexdelprete** [reply]
you see old data right?

**Reply by lfac76** [reply]
Yes! It's everything alright.

Sorry about these messages.

**Reply by alexdelprete** [reply]
don't worry. everything's good. :)

**Comment by InertiaImpact** [comment]
So on the latest version on docker I have to go through a series of steps whenever I redeploy a stack(via portainer). I also ended up just using a different mariaDB image that I knew how to properly configure.

Composer: 

```
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8890:80'
            - '8891:443'
        environment:
            - PUID=101
            - PGID=101
            - DB_CONNECTION=mysql
            - DB_HOST=mariadb_speedtest-tracker
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password!
        volumes:
            - /root/speedtest-tracker/config:/config
        image: 'ajustesen/speedtest-tracker:0.11.1'
        restart: unless-stopped
        depends_on:
            - mariadb_speedtest-tracker
    mariadb_speedtest-tracker:
        image: lscr.io/linuxserver/mariadb
        container_name: mariadb_speedtest-tracker
        environment:
          - PUID=1000
          - PGID=1000
          - MYSQL_ROOT_PASSWORD=speedy!
          - TZ=America/Chicago
          - MYSQL_DATABASE=speedtest_tracker
          - MYSQL_USER=speedy
          - MYSQL_PASSWORD=password!
          - MYSQL_PORT_3306_TCP_PORT = 3306
        
        volumes:
          - mariadb_speedtest-tracker:/var/lib/mysql
          - /root/mariadb_speedtest-tracker/config:/config

volumes:
  mariadb_speedtest-tracker:
```

1. Deploy Stack
2. Jump into an interactive shell in the mariaDB container to fix a perms issue. (Not sure if that is a mariaDB bug)
> mysql -uroot -p
> \*type in password defined in env params*
> GRANT ALL ON \*.* TO 'speedy'@'%';
> FLUSH privileges;
> EXIT;

3. Open interactive shell on the speedtest container to fix missing files/params
>chmod 777 -R /var/www/html/bootstrap/cache
>chmod 777 -R storage bootstrap/cache
>php artisan storage:link

4. Stop the speedtest container since when it first runs, there doesn't seem to be any log output or any indication of it actually running other than the ability to open an interactive shell on it.
5. Run the container again, this time it should connect and start up.

**Reply by UnAfraid** [reply]
I recommend you set a fixed tag on your images, using latest is risky because you never know when a new major version is going to be published and break potentially loosing data in the process

**Reply by InertiaImpact** [reply]
Fair enough, however in this instance it isn't the source of my issues. I have several other containers I spun up today with that bug too but I wanted to include step 2 incase anyone else was going to try and replicate it using my config/w/ my db choice.

**Reply by UnAfraid** [reply]
I modified slightly the docker-compose file you posted above:

.env
```env
DB_HOST=speedtest-tracker-db
DB_PORT=3306
DB_ROOT_PASSWORD=speedy
DB_DATABASE=speedtest_tracker
DB_USERNAME=speedy
DB_PASSWORD=password
```

docker-compose.yaml
```yaml
version: "3"
services:
    speedtest-tracker-app:
        image: ajustesen/speedtest-tracker:0.11.1
        container_name: speedtest-tracker-app
        restart: unless-stopped
        ports:
            - '8890:80'
            - '8891:443'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=mysql
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        volumes:
            - speedtest-tracker-app:/config

    speedtest-tracker-db:
        image: mariadb:10.6.11
        container_name: speedtest-tracker-db
        restart: unless-stopped
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Chicago
          - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
          - MYSQL_DATABASE=${DB_DATABASE}
          - MYSQL_USER=${DB_USERNAME}
          - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
          - speedtest-tracker-db:/var/lib/mysql

volumes:
  speedtest-tracker-app:
  speedtest-tracker-db:
```
