### DISCUSSION TITLE
SSL_MODE

### DISCUSSION THREAD

**Discussion by cinderblockgames** [alexjustesen/speedtest-tracker#462] [Q&A] [answered]
What are the options for SSL_MODE except for "mixed?"  I have a reverse proxy that handles SSL and would like to turn off the cert generation on startup.

**Comment by alexjustesen** [comment, marked as answer]
You can use `off`, `mixed` or `full`, here's the base container docs https://serversideup.net/open-source/docker-php/docs/reference/environment-variable-specification

**Reply by cinderblockgames** [reply]
Thanks!

**Comment by alexdelprete** [comment]
The cert. re-generation is only related to the `SSL_MODE=mixed` or `SSL_MODE=on` configuration.
To avoid the generation of SSL certs at startup, you should use a bind mount or named volume to the container's directory where certs are created (`/etc/ssl/web`). At startup, the container will find existing certs and won't recreate them.

If you use a reverse proxy with TLS, you must use SSL on ST too, otherwise the browser will receive a mixed-content error (see discussion for issue #280). The possible values for SSL_MODE are:

- `SSL_MODE=mixed` (default) both `http/80` and `https/443` available
- `SSL_MODE=full` only `https/443` available
- `SSL_MODE=off` only `http/80` available

Example docker compose file:

```yaml
version: '3.3'
services:
  speedtest-tracker:
    image: ghcr.io/alexjustesen/speedtest-tracker:v0.11.7
    container_name: speedtest-tracker
    restart: unless-stopped
    ports:
      - 8008:443
    environment:
      TZ: Europe/Rome
      PUID: 1000
      PGID: 1000
      DB_CONNECTION: mysql
      DB_HOST: mariadb.domain.dom
      DB_PORT: 3306
      DB_DATABASE: speedtest_tracker
      DB_USERNAME: xxxxxxxxxx
      DB_PASSWORD: yyyyyyyyyy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/config:/config
      - $PWD/certs:/etc/ssl/web
```
