### DISCUSSION TITLE
Speedtracker not starting

### DISCUSSION THREAD

**Discussion by yodaphone** [alexjustesen/speedtest-tracker#474] [Q&A] [answered]
i've installed it on a new VM & ran it using docker compose. the container starts up and is stuck on

```
Attaching to speedtest-tracker
```

My docker compose file

```
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8080:80'
            - '8443:443'
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - '/opt/speedtracker:/config'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped

```
