### DISCUSSION TITLE
Docker Error: Unable to fork [stty 2>&1]

### DISCUSSION THREAD

**Discussion by sjg** [alexjustesen/speedtest-tracker#541] [Q&A]
Hey all, 

Starting a discussion rather than an issue as I think this error is cause by something in my docker install rather than the software (also as #400 is closed)

Having an issue the same as #400 with a new docker install in Ubuntu 22.04.   The logs states: 

```
speedtest-tracker    | [13-Apr-2023 22:20:41] NOTICE: fpm is running, pid 129
speedtest-tracker    | [13-Apr-2023 22:20:41] NOTICE: ready to handle connections
speedtest-tracker    | [13-Apr-2023 22:20:41] NOTICE: systemd monitor interval set to 10000ms
speedtest-tracker    | [2023-04-13 22:20:41] production.ERROR: exec(): Unable to fork [stty 2>&1] {"exception":"[object] (ErrorException(code: 0): exec(): Unable to fork [stty 2>&1] at /var/www/html/vendor/symfony/console/Terminal.php:131)
speedtest-tracker    |   exec(): Unable to fork [stty 2>&1]

```
Docker Compose

```
speedtest-tracker:
    container_name: speedtest-tracker
    ports:
        - '8765:80'
        - '8443:443'
    environment:
        - PUID=1000
        - PGID=1000
    volumes:
        - '/docker/appdata/speedtest:/config'
    image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
    restart: unless-stopped
```

Things I've tried
  - Pulling from GHCR:Latest
  - Pulling from Docker Hub:latest
  - Building from source
  - binding the volume, rather then using the volume in docker-compose
  - chmod'ing the volume directory to the same user id

Any help would be much appreciated

Cheers :)
