### DISCUSSION TITLE
Unable to issue email notifications

### DISCUSSION THREAD

**Discussion by ilikemyfto** [alexjustesen/speedtest-tracker#697] [Q&A]
I have tried to issue email notifications and used email providers such as gmail, maligun and Virginmedia to no avail. I have set notifications to trigger on: Notify on every speedtest run and Notify on threshold failures.

Attached is a copy of todays logs taken from Portainer and a copy of the Stack. I have also attached a copy of a Python program which I have used to show that the username and password used for the gmail account works.
[_speedtest-tracker_logs.txt](https://github.com/alexjustesen/speedtest-tracker/files/12475968/_speedtest-tracker_logs.txt)
[_speedtest-tracker-db-1_logs.txt](https://github.com/alexjustesen/speedtest-tracker/files/12475969/_speedtest-tracker-db-1_logs.txt)
[Stacks>speedtest-tracker.docx](https://github.com/alexjustesen/speedtest-tracker/files/12475976/Stacks.speedtest-tracker.docx)
[import smtplib.docx](https://github.com/alexjustesen/speedtest-tracker/files/12475980/import.smtplib.docx)

Otherwise the program is a fantastic project, over the weekend it really showed the effects of the storm.
<img width="911" alt="Screenshot 2023-08-30 at 14 25 14" src="https://github.com/alexjustesen/speedtest-tracker/assets/34509561/d1e69782-ac00-4a90-9f4c-700e8058445b">

Thanks for any help given.

**Comment by alexjustesen** [comment]
@ilikemyfto can you share your environment variables you're setting either when starting the container or in your `docker-compose.yml` file?

**Comment by ilikemyfto** [comment]
Hi Alex
Thank you for taking a look at this, I have to admit I'm not very savvy using Docker, though I feel pleased to have got thus far. I loaded the project after watching a YouTube video by BD Tech - Internet SpeedTest Tracker on Docker - 2022 Edition. To my delight it worked straight off the cuff. It was installed directly into Portainer using a Stack, I think this is equal to the docker compose, (not sure) but the env was as follows after inserting the Mail commands:-
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8080:80'
            - '8443:443'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
            - MAIL_MAILER=smtp
            - MAIL_HOST=smtp.gmail.com
            - MAIL PORT=465
            - MAIL USERNAME=r***********@virginmedia.com
            - MAIL PASSWORD=a****-b****-v****-s****
            - MAIL_FROM_NAME="${APP_NAME}"
            - APP_DEBUG=true
            - TZ=UTC
        volumes:
            - '/home/pi/speedtest:/config'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest_tracker
            - MARIADB_USER=speedy
            - MARIADB_PASSWORD=password
            - MARIADB_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
volumes:
  speedtest-db:

I've blotted out my email with *****.

Logs and any other bits I could download from Portainer are in the txt and docx files contained in my previous post.

I am hosting the Speedtest_tracker on a Raspberry pi4 2gb running the Raspberry OS full 64bit Debian Bullseye.

Apart from not being able to issue notifications the SpeedTest-Tracker works really well and I have enjoyed using it. Also I'm rather please to get programs running in Docker. The pi is also running Pi-Hole and a VPN. 

Thanks again.

Kind Regards 

Roy

**Reply by alexjustesen** [reply]
So I _think_ it's because your `MAIL_HOST` value is incorrect, based on this [forum post](https://community.virginmedia.com/t5/Help/Virgin-Media-Email-settings/td-p/3166396) I think it should be `MAIL_HOST=smtp.virginmedia.com`.

**Comment by ilikemyfto** [comment]
Hi Alex. Thank you for pointing out my error, I had been trying to see if it would work with gmail and opps! I omitted to change the - "MAIL USERNAME=" statement back to smtp.virginmedia.com.

I have noticed that when I try the "test email channel" I get the "Test mail notification sent" ok but immediately in the log for [speedtest-tracker-db-1] container I see this message:-

(http://192.168.1.96:9000/#!/2/docker/containers/369f542daa7561463e73e05351117a8cc519b37d1ac39c5a097dc096afd773c8)
2023-09-05 14:33:38 29482 [Warning] Aborted connection 29482 to db: 'speedtest_tracker' user: 'speedy' host: '172.19.0.3' (Got an error reading communication packets)

Using a python script with the same from and to email addresses/password works ok.

So I'm stumped. :-(

Kind Regards

Roy

**Reply by alexjustesen** [reply]
You can probably ignore that warning if emails are making it to your inbox

**Reply by ilikemyfto** [reply]
But emails don't reach my mailbox,so is the error related?

**Comment by ilikemyfto** [comment]
I have tried to get the email notifications by using malign as you suggested. The Docker stack is as follows:-

```
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8080:80'
            - '8443:443'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
            
            - MAIL_DRIVER=smtp
            - MAIL_MAILER=smtp
            - MAIL_HOST=smtp.mailgun.org
            - MAIL PORT=587
            - MAIL USERNAME="postmaster@sandbox********************.mailgun.org"
            - MAIL PASSWORD="8******************************************-081cc153"
            - MAIL_ENCRYPTION=tls
            - MAIL_FROM_NAME="${APP_NAME}"

            - APP_DEBUG=true
            - TZ=UTC
        volumes:
            - '/home/pi/speedtest:/config'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest_tracker
            - MARIADB_USER=speedy
            - MARIADB_PASSWORD=password
            - MARIADB_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
volumes:
  speedtest-db:
```

with an email address as per the mailgun authorized recipients.

It still doesn't work.

Do you have any ideas?

Kind Regards 

Roy

Edited by @alexjustesen to make the `docker-compose.yml` file easier to read
