### DISCUSSION TITLE
Problems getting this running behind Gluetun

### DISCUSSION THREAD

**Discussion by Landrin201** [alexjustesen/speedtest-tracker#817] [Q&A] [answered]
I want to set this up behind gluetun and I can't get it working. I've tried everything, i'm completely lost

I'm running everything in docker, and using postgres. 

Here's the dockercompose for the speedtest tracker: 

```
speedtest-tracker:
    container_name: speedtest-tracker
    image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
    network_mode: service:gluetun_protonvpn
    restart: unless-stopped
    environment:
        - PUID=1000
        - PGID=1000
        - DB_CONNECTION=pgsql
        - DB_HOST=localhost
        - DB_PORT=5432
        - DB_DATABASE=speedtest_tracker
        - DB_USERNAME=speedy
        - DB_PASSWORD=password
        - TZ=America/New_York
    volumes:
        - '/etc/localtime:/etc/localtime:ro'
        - '/configStorage/config/arrSpeedtestTracker/config:/config'
    depends_on:
        - speedtest_tracker_db
        - gluetun_protonvpn
    healthcheck:
      test: "curl -sf https://example.com  || exit 1"
      interval: 1m
      timeout: 10s
      retries: 1
    labels:
      - "deunhealth.restart.on.unhealthy=true"
      
  speedtest_tracker_db:
    image: postgres:15
    container_name: speedtest_tracker_db
    restart: unless-stopped
    network_mode: service:gluetun_protonvpn
    depends_on:
        - gluetun_protonvpn
    environment:
        - PUID=1000
        - PGID=1000
        - POSTGRES_DB=speedtest_tracker
        - POSTGRES_USER=speedy
        - POSTGRES_PASSWORD=password
    volumes:
          - /configStorage/config/arrSpeedtestTracker/database:/var/lib/postgresql/data
```

Whenever I try to run the stack, I get the following error in the speedtest-tracker container:

```
In Connection.php line 801:

                                                                               

  SQLSTATE[08006] [7] connection to server at "localhost" (127.0.0.1), port 5  

  432 failed: Connection refused                                               

  	Is the server running on that host and accepting TCP/IP connections?         

  connection to server at "localhost" (::1), port 5432 failed: Cannot assign   

  requested address                                                            

  	Is the server running on that host and accepting TCP/IP connections? (Conn   

  ection: pgsql, SQL: select * from information_schema.tables where table_cat  

  alog = speedtest_tracker and table_schema = public and table_name = migrati  

  ons and table_type = 'BASE TABLE')                                           

                                                                               

In Connector.php line 65:

                                                                               

  SQLSTATE[08006] [7] connection to server at "localhost" (127.0.0.1), port 5  

  432 failed: Connection refused                                               

  	Is the server running on that host and accepting TCP/IP connections?         

  connection to server at "localhost" (::1), port 5432 failed: Cannot assign   

  requested address                                                            

  	Is the server running on that host and accepting TCP/IP connections? 
```

I'm at a loss here. I've tried everything I can think of; I KNOW that localhost is working with the gluetun network_mode, because other services being run inside that exact same network are communicating with each other just fine via localhost. I've tried changing the db port. ALL of the variables, for that matter. I've done everything logical and figure I should bring it up here.

Any ideas?

Also, as a side note, I keep noticing that the database container keeps changing the ownership of the database folder I specified to systemd-coredump. I'm starting to wonder if this has something to do with that, it's really weird. It's set to use user 1000, which is not what it keeps changing the ownership to...
