### DISCUSSION TITLE
registry.hub.docker.com

### DISCUSSION THREAD

**Discussion by pippopd** [alexjustesen/speedtest-tracker#91] [Ideas]
hi, can you add your project on "https://registry.hub.docker.com"?
If you publish it here too, we can also install it on Synology nas that support dockers.
I gladly accept a guide on how to install it on Synology in another way.
Thank you.

**Comment by alexdelprete** [comment]
you can install it on Synology, through docker-compose.

**Comment by pippopd** [comment]
Unfortunately, I'm not very familiar with docker-compose.
I tried with:

_version: '3.3'
services:
    speedtest:
        container_name: speedtest-tracker
        image: alexjustesen/speedtest-tracker
        ports:
            - 8785:80
        volumes:
            - /volume1/docker/internetspeedtracker:/config
        environment:
            - TZ=Europe/Rome
            - PGID=100
            - PUID=1026
            - OOKLA_EULA_GDPR=true
        restart: unless-stopped_

unfortunately when I try this error comes out and the installation is not successful:

![image](https://user-images.githubusercontent.com/10078112/198007198-b5275982-b2cc-482d-a6ff-cb688e9b3fa8.png)

Any ideas on how to fix?

**Reply by alexjustesen** [reply]
https://docs.speedtest-tracker.dev/getting-started/installation

**Reply by alexdelprete** [reply]
> Unfortunately, I'm not very familiar with docker-compose.

Did you read the docs? https://docs.speedtest-tracker.dev/getting-started/installation#install-with-docker-compose

Your `image:` is wrong.

```yaml
version: '3.3'
services:
    speedtest-tracker:
        image: ghcr.io/alexjustesen/speedtest-tracker:latest
        container_name: speedtest-tracker
        ports:
            - '8443:443'
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - '/path/to/directory:/config'

```
