### DISCUSSION TITLE
I already type in the correct password. But the container stuck at the login screen.

### DISCUSSION THREAD

**Discussion by LyonelleHansen** [alexjustesen/speedtest-tracker#974] [Q&A] [answered]
when I click the sign in button after enter the correct use name and password. I keep getting stuck at the sign in screen without going any further. When I click sign in, it loading and stop at the login screen. How do I fix this. I'm install this speedtest tracker container on raspberry pi 4. Please help.
<img width="1312" alt="Screenshot 2023-12-10 at 18 39 57" src="https://github.com/alexjustesen/speedtest-tracker/assets/152894139/7234d95e-ffe0-41b5-856b-0e33047e5659">

**Comment by alexjustesen** [comment]
@LyonelleHansen I'll need some more information. Can you please include the `docker-compose.yml` file that you used and your Raspberry Pi model and installed OS?

**Reply by LyonelleHansen** [reply]
I use raspberry pi 4 with 8GB RAM, I'm running raspberry pi OS bookworm lite 64 bit version. 
```
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8080:80'
            - '8443:443'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
        volumes:
            - '/portainer/Files/AppData/Config/speedtest-app/speedtest-app:/config'
            - '/portainer/Files/AppData/Config/speedtest-app/web:/etc/ssl/web'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest_tracker
            - MARIADB_USER=speedy
            - MARIADB_PASSWORD=password
            - MARIADB_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
volumes:
  speedtest-app:
  speedtest-db:
```
