### ISSUE TITLE
On docker compose up: "failed to register layer: "

### ISSUE THREAD

**Issue by circle3451** [alexjustesen/speedtest-tracker#1032]
**Describe the bug**

I get the following error message when trying to run the container:

`failed to register layer: failed to Lchown "/usr/bin/crontab" for UID 0, GID 105 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /usr/bin/crontab: invalid argument`

**To Reproduce**
```
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8080:80'
            - '8443:443'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
        volumes:
            - speedtest-app:/config
            - '/path/to/directory/web:/etc/ssl/web'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest_tracker
            - MARIADB_USER=speedy
            - MARIADB_PASSWORD=password
            - MARIADB_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
volumes:
  speedtest-app:
  speedtest-db:
```

**Expected behavior**
A succesful pull and up of container

**Environment (please complete the following information):**
 - OS: debian lxc on proxmox
-  Architecture: amd64
 - Version: tested on v0.14.1 and v0.13.4

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**

Edited by @alexjustesen to make reading the config easier
