### ISSUE TITLE
User lost access to admin settings

### ISSUE THREAD

**Issue by shalak** [alexjustesen/speedtest-tracker#1039]
**Describe the bug**
In some of the recent updates, my admin user lost its access to admin settings. The left-hand menu no longer shows the proper entries

**To Reproduce**
1. Login as admin user
2. Go do `/admin`

**Expected behavior**
User is allowed to perform admin actions

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
-  Architecture: amd64
 - Browser: Firefox
 - Version: App: 0.14.1

**Screenshots**

<img width="455" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/1536554/41fc5c14-dc2a-4431-b031-7b94914c39e4">

<img width="422" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/1536554/2b194934-b0cd-4d2c-bb54-7833dd06f4e6">

**Additional context**
My compose file:

```yaml
  speedtest:
    image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
    container_name: speedtest
    restart: unless-stopped
    environment:
        - PUID=1000
        - PGID=1000
        - DB_CONNECTION=mysql
        - DB_HOST=speedtest-db
        - DB_PORT=3306
        - DB_DATABASE=speedtest_tracker
        - DB_USERNAME=speedy
        - APP_URL=https://speedtest.mydomain.net
    env_file: /srv/fast/services/speedtest/.env
    volumes:
        - '/srv/fast/services/speedtest/speedtest:/config'
    labels:
      - "traefik.enable=true"
    depends_on:
        - speedtest-db
  speedtest-db:
    image: mariadb:10
    container_name: speedtest-db
    restart: unless-stopped
    environment:
        - MARIADB_DATABASE=speedtest_tracker
        - MARIADB_USER=speedy
        - MARIADB_RANDOM_ROOT_PASSWORD=true
    env_file: /srv/fast/services/speedtest/.env
    volumes:
        - /srv/fast/services/speedtest/speedtest-db:/var/lib/mysql
```
