### ISSUE TITLE
MySQL - connection refused - New install of both

### ISSUE THREAD

**Issue by malaki86** [alexjustesen/speedtest-tracker#1078]
**Describe the bug**
In Unraid, I installed MySQL-Official (Docker) and Speedtest-Tracker. With MySQL running, Speedtest-Tracker errors out with a "Connection Refused". I used the same database name, login & password on both.

**To Reproduce**
1 - Start "Speedtest-Tracker"
Errors out in a few seconds

**Environment (please complete the following information):**
 - OS: Unraid v6.12.6
-  Architecture: x64
 - Version: Latest

**Logs**
s6-rc: warning: unable to start service laravel-automations: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.

In Connection.php line 822:
                                                                               
  SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select t  
  able_name as `name`, (data_length + index_length) as `size`, table_comment   
  as `comment`, engine as `engine`, table_collation as `collation` from infor  
  mation_schema.tables where table_schema = 'db' and table_type in ('BASE TAB  
  LE', 'SYSTEM VERSIONED') order by table_name)                                
                                                                               

In Connector.php line 65:
                                             
  SQLSTATE[HY000] [2002] Connection refused 

**Additional context**

**Comment by malaki86** [comment]
I uninstalled MySQL and installed MariaDB (docker). Now I'm getting an 'access denied' error

`#36 {main}
"} 
s6-rc: warning: unable to start service laravel-automations: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.

In Connection.php line 822:
                                                                               
  SQLSTATE[HY000] [1045] Access denied for user 'root'@'172.17.0.14' (using p  
  assword: YES) (Connection: mysql, SQL: select table_name as `name`, (data_l  
  ength + index_length) as `size`, table_comment as `comment`, engine as `eng  
  ine`, table_collation as `collation` from information_schema.tables where t  
  able_schema = 'db' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED') ord  
  er by table_name)                                                            
                                                                               

In Connector.php line 65:
                                                                               
  SQLSTATE[HY000] [1045] Access denied for user 'root'@'172.17.0.14' (using p  
  assword: YES)                                                              `

**Comment by jasonmeehan11** [comment]
Having the same problem.
I even tried install MariaDB on my host OS (ubuntu) creating a database and giving full remote access to the user spcified in my env variables.
Still have the same error....

**Comment by modem7** [comment]
Can confirm the same here:

`SQLSTATE[HY000] [2002] Connection refused`

```yaml
  speedtest:
    container_name: Speedtest
    image: ghcr.io/alexjustesen/speedtest-tracker
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      # - APP_DEBUG=true
      - APP_KEY=$SPEEDTEST_APP_KEY
      - DASHBOARD_POLLING=60s
      - NOTIFICATION_POLLING=60s
      - RESULTS_POLLING=false
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    networks:
      pihole:
        ipv4_address: '172.22.0.108'
    ports:
      - 5180:80
    volumes:
      - $USERDIR/Speedtest/config:/config
      - $USERDIR/Speedtest/web:/etc/ssl/web
    labels:
      - backup
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.speedtest-rtr.entrypoints=https"
      - "traefik.http.routers.speedtest-rtr.rule=Host(`speedtest.$DOMAINNAME`)"
      - "traefik.http.routers.speedtest-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.speedtest-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.speedtest-rtr.service=speedtest-svc"
      - "traefik.http.services.speedtest-svc.loadbalancer.server.port=80"
      ## Homepage
      - homepage.name=Speedtest Tracker
      - homepage.group=System
      - homepage.icon=openspeedtest
      - homepage.href=https://speedtest.$DOMAINNAME
      - homepage.widget.type=speedtest
      - homepage.widget.url=http://speedtest
    healthcheck:
      test: curl -fSs http://localhost/ping || exit 1
      start_period: 120s
      interval: 10s
      timeout: 10s
      retries: 3
    restart: always
    mem_limit: 500m
    mem_reservation: 200m
```
