### ISSUE TITLE
Result in API response is not calculated in Mbps or Gbps in version 0.16.x

### ISSUE THREAD

**Issue by mannbadal** [alexjustesen/speedtest-tracker#1176]
**Describe the bug**
Result in API response is not calculated in Mbps or Gbps in version 0.16.x but showing in bps

**To Reproduce**
Steps to reproduce the behaviour:
1. Install version 0.16.x
2. Schedule a speedtest 
3. GET /api/speedtest/latest
4. Download and Upload speed are in bps

**Expected behavior**
It should show rounded results in Mbps or Gbps with 2 decimal values

**Environment (please complete the following information):**
 - OS: Docker
-  Architecture: arm64
 - Browser: Chrome
 - Version 0.16.3

**API response**
v0.16.3 shows
```
{"message":"ok","data":{"id":1,"ping":264.839,"download":126109704,"upload":62118624}
```
v0.15.5 shows (Expected)
```
{"message":"ok","data":{"id":1,"ping":264.839,"download":126.1096,"upload":62.1184}
```
**Screenshot**
![image](https://github.com/alexjustesen/speedtest-tracker/assets/108790470/861a2a90-d4aa-48b1-b5a7-d9f39497ee96)

**Logs**
N/A

**Additional context**
Systems like Organizr etc do not calculate results but relies on what is provided within API

**Comment by OddSquirrel** [comment]
Same issue using Heimdall:

![image](https://github.com/alexjustesen/speedtest-tracker/assets/39886438/965d7514-162e-43a8-845c-1a4f4574a46d)

Although I certainly would not mind if that were the real speed. 😊

**Comment by v1rusnl** [comment]
Same when pulling the api data via Homepage. Resultat should say Mbit/s instead of Tbit/s. ![IMG_20240220_071538.jpg](https://github.com/alexjustesen/speedtest-tracker/assets/18641204/3d1ba3e1-8143-4021-b5e0-8622d406ce61)

**Comment by crispybegs** [comment]
same

<img width="287" alt="Screenshot 2024-02-20 at 07 13 39" src="https://github.com/alexjustesen/speedtest-tracker/assets/129169122/93d0f8fa-d72d-4cc4-bb0b-0e683dc305b2">

**Comment by gsanchez2004** [comment]
Same issue with Api report on Homepage !

**Comment by alexjustesen** [comment]
#1182 incoming in `v0.16.4` which will fix the calc for Speedtest Tracker dashboards and tables. This isn't going to fix Homepage or Heimdall widgets as an fyi. Will have to circle back around to that later tonight.

**Comment by Christophe999s** [comment]
> Same issue with Api report on Homepage !

For a quick fix you can use the custom API.
You can add this in your services.yaml
Just replace http://speedtest with your own url
```
widget:
    type: customapi
    url: http://speedtest/api/speedtest/latest
    refreshInterval: 60000
    method: GET
    mappings:
        - field:
            data: download
          label: Download
          format: number
          scale: 1/1000000
          suffix: Mbps
        - field:
            data: upload
          label: Upload
          format: number
          scale: 1/1000000
          suffix: Mbps
        - field:
            data: ping
          label: ms
          format: float
```
