### ISSUE TITLE
Support for arm v7

### ISSUE THREAD

**Issue by crypticviper** [alexjustesen/speedtest-tracker#120]
**Is your feature request related to a problem? Please describe.**
I want to be able to run this as docker container on raspberry pi (arm v7).

**Describe the solution you'd like**
Is there any plan to support this in the near future?

**Additional context**
NA

**Comment by alexjustesen** [comment]
Phoning a friend, @jaydrogers does the base containers supper arm 7?

**Comment by jaydrogers** [comment]
I think it should?

See my platforms here: https://github.com/serversideup/docker-php/blob/main/.github/workflows/workflow-docker-publish.yml#L64-L67

Here are all the options:

https://github.com/docker-library/official-images#architectures-other-than-amd64

**Comment by fragolinux** [comment]
unfortunately, it does not seem to exist a mariadb armv7, so this fails anyway
![image](https://github.com/alexjustesen/speedtest-tracker/assets/21192010/3b1953b8-8dc0-4a4d-a6fd-e099c59e9054)

**Comment by crypticviper** [comment]
> unfortunately, it does not seem to exist a mariadb armv7, so this fails anyway
> ![image](https://user-images.githubusercontent.com/21192010/282295411-3b1953b8-8dc0-4a4d-a6fd-e099c59e9054.png)

I use “ yobasystems/alpine-mariadb”  which has armv7 support and works ok for me.

**Comment by fragolinux** [comment]
solved using this **docker-compose.yml**:

```
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8765:80'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
            - TZ=Europe/Rome
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./data/speedtest:/config
            - ./data/speedtest/web:/etc/ssl/web
        image: 'ghcr.io/alexjustesen/speedtest-tracker'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: linuxserver/mariadb:arm32v7-10.6.13
        restart: unless-stopped
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Rome
            - MYSQL_ROOT_PASSWORD=root_password
            - MYSQL_DATABASE=speedtest_tracker
            - MYSQL_USER=speedy
            - MYSQL_PASSWORD=password
        volumes:
            - ./data/mysql:/config
```

**Comment by fragolinux** [comment]
> > unfortunately, it does not seem to exist a mariadb armv7, so this fails anyway
> > ![image](https://user-images.githubusercontent.com/21192010/282295411-3b1953b8-8dc0-4a4d-a6fd-e099c59e9054.png)
> 
> I use “ yobasystems/alpine-mariadb” which has armv7 support and works ok for me.

sorry, just saw this, i was searching for a solution myself and came to the one in my previous post, maybe better add an armv7 compatible docker-compose.yml to your repo, then?
thanks!

**Comment by fragolinux** [comment]
i just reduced everything to this, as it's enough for me:

```
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8765:80
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=sqlite
            - DB_HOST=/config/database.sqlite
            - TZ=Europe/Rome
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./data:/config
        image: ghcr.io/alexjustesen/speedtest-tracker
        restart: unless-stopped
```
