### ISSUE TITLE
Graph time axis is reversed: goes from most recent to oldest values

### ISSUE THREAD

**Issue by rloomans** [alexjustesen/speedtest-tracker#1204]
**Describe the bug**
I would expect that the graphs would have the oldest values on the left to the newest values on the right.  What I’m seeing is the reverse.

**To Reproduce**
Both the public dashboard and the admin one have graphs in the same newest to oldest values

**Expected behavior**
I would expect that the graphs would have the oldest values on the left to the newest values on the right. 

**Environment (please complete the following information):**
 - OS: Debian
-  Architecture: amd64
 - Browser: Safari on iOS
 - Version: 17.3

Using your docker image, not the Linux server one, with postgresql

```
version: '3.3'
services:
  speedtest-tracker:
    container_name: speedtest-tracker
    expose:
      - 80
      - 443
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME=speedy
      - DB_PASSWORD=<redacted>
      - TZ=Australia/Brisbane
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './config:/config'
      - './web:/etc/ssl/web'
    image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - nginx_proxy
      - default

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=speedtest_tracker
      - POSTGRES_USER=speedy
      - POSTGRES_PASSWORD=<redacted>
      - TZ=Australia/Brisbane
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - speedtest-db:/var/lib/postgresql/data
    networks:
      - default

volumes:
  speedtest-db:

networks:
  nginx_proxy:
    name: nginx_proxy
    external: true
```

**Screenshots**

![IMG_0344](https://github.com/alexjustesen/speedtest-tracker/assets/92133/eacc6a04-8602-4aad-8889-35e0d9ba7e70)

**Logs**
N/A

**Additional context**
<img width="867" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/92133/cc9f2971-9a8b-4ca7-b8b6-efb4082c5bda">
