### ISSUE TITLE
Time Zone issues after updating to v0.16.x

### ISSUE THREAD

**Issue by Starfiresg1** [alexjustesen/speedtest-tracker#1214]
**Describe the bug**
After updating I noticed a timezone discrepency in new speedtests. It seams the "created at" column and the json-data of the test now contain both UTC time. Prior to the upgrade the "created at" column contained local time.
I use a MariaDB-Database which has the local timezone set:

SELECT @@global.time_zone, @@session.time_zone; 

@@global.time_zone 	@@session.time_zone 	
SYSTEM 			SYSTEM

output of date command on command line:
Wed Feb 21 22:18:04 CET 2024

CET (UTC+1) is used

I've had the following settings that worked prior to upgrading to the new release:
![grafik](https://github.com/alexjustesen/speedtest-tracker/assets/8659009/4dc219b9-9afd-4577-b07f-fa3861accc64)

In the results table new entries have UTC-time in both the JSON-field and "created_at" column. Older tests before the migration had the local time in the created_at column and display with the correct local time in the result list and the charts.
![grafik](https://github.com/alexjustesen/speedtest-tracker/assets/8659009/e28ca490-1917-41f3-8fe2-f2737a84641b)

The public dashboard is even stranger - it backdates the result one hour from UTC - displaying the result at UTC-1.

**To Reproduce**
1. Run a manual speedtest at an specific local time
2. Click on 'Results' or refresh the dashboard
3. Time of the result in list and graph is not displayed in local time

**Expected behavior**
Time in the result list and the graph should be in local time as they did in v15 I think.

**Environment (please complete the following information):**
 - OS: debian (docker)
 - Architecture: amd64
 - Browser: Firefox
 - Version v0.16.6 (Linuxserver,io)
 - Linuxserver.io MariaDB-Docker running 10.11.6 of MariaDB

**Screenshots**
Test run at 21:47 local time
Admin Dashboard displays 20:47 as last entry
![grafik](https://github.com/alexjustesen/speedtest-tracker/assets/8659009/5ab9c7d4-ebb0-4350-82e3-9ee2875326ee)
Result list displays 20:47 as test time
![grafik](https://github.com/alexjustesen/speedtest-tracker/assets/8659009/5d4c91fc-160d-4616-bb1b-2f6a116febe6)
Public dashboard displays 19:47 as last entry
![grafik](https://github.com/alexjustesen/speedtest-tracker/assets/8659009/d3d55dcb-ec1e-4f42-92ec-93e02b1300d4)

**Logs**
Nothing oblivious in the logs

**Comment by hoorna** [comment]
I am seeing the same behavior (also using version v0.16.6 from Linuxserver). My MariaDB and the Speedtest container are both set to the local timezone (with environment variable TZ). If you switch "Database has timezone" off then the times presented on the Result page are OK for new tests (of course not for old tests).

**Comment by OddSquirrel** [comment]
On my end, I can't even choose time zones or servers anymore. Both show arrows, but nothing happens when I click on them:

![image](https://github.com/alexjustesen/speedtest-tracker/assets/39886438/c8c23503-5e41-4068-b889-dc4777888b09)

Are you guys running v0.16.6 as well?

**Comment by hoorna** [comment]
@OddSquirrel, as I wrote earlier: yes I am also running v0.16.6 (from linuxserver)..

I have created the Speedtest-tracker container with a docker-compose file and with the TZ environment variable set. For the database I am running MariaDB (version 11.3.2) in a docker container which is also created with a docker-compose file and with the TZ environment variable set. I switched off the "Database has time zone".

Since one of the v16 versions (I really do not know which one) all times are correct now (on the Dashboard page as well as on the Result and Public pages). In new database records, all times are now written everywhere in UTC (in the "data" field and in the "created_at" and the "updated_at" fields).

@alexjustesen, it appears that the solution to the [previously reported Timezone issues](https://github.com/alexjustesen/speedtest-tracker/issues/939#issuecomment-1847542115) with the "Database has time zone" switch is no longer necessary.

**Comment by OddSquirrel** [comment]
@hoorna Sorry, must have missed the version part. I'm running PostgreSQL on my end.

@alexjustesen Do you have an eye on that issue with the non-choosable time zone and server, or should I raise a dedicated ticket for it?

**Comment by alexjustesen** [comment]
> @alexjustesen Do you have an eye on that issue with the non-choosable time zone and server, or should I raise a dedicated ticket for it?

Can you open a separate issue and also add your browser info?

**Comment by alexjustesen** [comment]
@Starfiresg1 can you share your `docker-compose.yml` config?

**Comment by Starfiresg1** [comment]
```
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '<redacted>:8765:80'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=mysql
            - DB_HOST=mariadb
            - DB_PORT=3306
            - DB_DATABASE=<redacted>
            - DB_USERNAME=<redacted>
            - DB_PASSWORD=<redacted>
	    - APP_KEY=base64:<redacted>
        volumes:
            - /opt/docker/speedtest-tracker:/config
            - /opt/docker/speedtest-tracker/web:/etc/ssl/web
        image: 'lscr.io/linuxserver/speedtest-tracker:latest'
        restart: unless-stopped
networks:
  swagnet:
    external: true
  mariadb:
    external: true
```

Database is defined external (Linuxserver.io MariaBD) - used by multiple docker-containers
in case it is needed, here it's it compose:


```
version: "2.1"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=<redacted>
      - TZ=Europe/Berlin
    volumes:
      - /opt/docker/mariadb:/config
    ports:
      - <redacted>:3306:3306
    restart: unless-stopped
networks:
  mariadb:
    external: true
```

Network mariadb is a user defined bridget network which allows docker containers needing access to the mariadb-docker talking to each other and the mariadb-container.
