### ISSUE TITLE
/ping endpoint not found

### ISSUE THREAD

**Issue by modem7** [alexjustesen/speedtest-tracker#1228]
It seems that the /ping endpoint is no longer functioning.

```
https://speedtest.mydomain.com/ping
```

Getting `404 NOT FOUND`

![image](https://github.com/alexjustesen/speedtest-tracker/assets/4349962/cde20d79-f8a5-46a5-ae49-8342602edf39)

```yaml
  speedtest:
    container_name: Speedtest
    image: linuxserver/speedtest-tracker
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      # - APP_DEBUG=true
      - APP_KEY=$SPEEDTEST_APP_KEY
      - DASHBOARD_POLLING=60s
      - NOTIFICATION_POLLING=60s
      - RESULTS_POLLING=false
      # - CACHE_DRIVER=file
      - DB_CONNECTION=sqlite
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    networks:
      pihole:
        ipv4_address: '172.22.0.108'
    ports:
      - 5180:80
    volumes:
      - $USERDIR/Speedtest/config:/config
      - $USERDIR/Speedtest/web:/etc/ssl/web
    labels:
      - backup
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.speedtest-rtr.entrypoints=https"
      - "traefik.http.routers.speedtest-rtr.rule=Host(`speedtest.$DOMAINNAME`)"
      - "traefik.http.routers.speedtest-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.speedtest-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.speedtest-rtr.service=speedtest-svc"
      - "traefik.http.services.speedtest-svc.loadbalancer.server.port=80"
    # healthcheck:
    #   test: curl -fSs http://localhost/ping || exit 1
    #   start_period: 120s
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    restart: always
    mem_limit: 500m
    mem_reservation: 200m
```
