### ISSUE TITLE
Discord webhook notifications doesn't work

### ISSUE THREAD

**Issue by Tresmos** [alexjustesen/speedtest-tracker#1235]
**Describe the bug**
Discord webhook notifications doesn't work. Console outputs `production.ERROR: Undefined array key "discord_webhook_url"`

**To Reproduce**
1. Enable Discord Notifications and Notify on every speedtest run or on threshold failures
2. Queue Speedtest

**Expected behavior**
Discord notification being actually sent.

**Environment (please complete the following information):**
 - OS: Raspbian with docker using `lscr.io/linuxserver/speedtest-tracker:latest` as image
-  Architecture: arm64
 - Version: App: 0.17.1

**Screenshots**
![image](https://github.com/alexjustesen/speedtest-tracker/assets/32764592/c24b7616-0ab8-4600-aa2c-ddb04989de8d)

![image](https://github.com/alexjustesen/speedtest-tracker/assets/32764592/1ed37d6f-3445-4eaa-9b23-803098ff53dd)

**Logs**
```speedtest-tracker  | [migrations] started
speedtest-tracker  | [migrations] 01-nginx-site-confs-default: skipped
speedtest-tracker  | [migrations] done
speedtest-tracker  | ───────────────────────────────────────
speedtest-tracker  | 
speedtest-tracker  |       ██╗     ███████╗██╗ ██████╗
speedtest-tracker  |       ██║     ██╔════╝██║██╔═══██╗
speedtest-tracker  |       ██║     ███████╗██║██║   ██║
speedtest-tracker  |       ██║     ╚════██║██║██║   ██║
speedtest-tracker  |       ███████╗███████║██║╚██████╔╝
speedtest-tracker  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
speedtest-tracker  | 
speedtest-tracker  |    Brought to you by linuxserver.io
speedtest-tracker  | ───────────────────────────────────────
speedtest-tracker  | 
speedtest-tracker  | To support the app dev(s) visit:
speedtest-tracker  | speedtest-tracker: https://github.com/sponsors/alexjustesen
speedtest-tracker  | 
speedtest-tracker  | To support LSIO projects visit:
speedtest-tracker  | https://www.linuxserver.io/donate/
speedtest-tracker  | 
speedtest-tracker  | ───────────────────────────────────────
speedtest-tracker  | GID/UID
speedtest-tracker  | ───────────────────────────────────────
speedtest-tracker  | 
speedtest-tracker  | User UID:    1000
speedtest-tracker  | User GID:    1000
speedtest-tracker  | ───────────────────────────────────────
speedtest-tracker  | 
speedtest-tracker  | using keys found in /config/keys
speedtest-tracker  | An application key was generated at start up, as no environment variable was set.
speedtest-tracker  | To set an application key that persists, read the docs: https://docs.speedtest-tracker.dev/
speedtest-tracker  | [custom-init] No custom files found, skipping...
speedtest-tracker  | [ls.io-init] done.
speedtest-tracker  | [2024-02-22 23:27:46] production.ERROR: Undefined array key "discord_webhook_url"  
speedtest-tracker  | [2024-02-22 23:34:30] production.ERROR: Undefined array key "discord_webhook_url"
```

**Additional context**
Pressing "Test discord notification" button does send a discord message:
![Discord_FysiYhGwwE](https://github.com/alexjustesen/speedtest-tracker/assets/32764592/6f41d9ab-3255-411a-9aec-38f0ee4f4c44)

I've tried

- `php artisan migrate --force` outputs `Nothing to migrate.`
- `php artisan cache:clear`

**Comment by masterwishx** [comment]
@Tresmos is it working now on treshholds?
Not working for me

**Comment by alexjustesen** [comment]
Last night's hotfix should of fixed it #1236

**Comment by masterwishx** [comment]
@alexjustesen 
moved to linuxserver.io v 0.17.2 not working on treshholds also mail was not working (throws exeption) and telegram , after `php artisan cache:clear`  and restart checked on **Notify on every speedtest run** this was working also mail and telegram now working but not discord thresholds!

**Comment by jonezy35** [comment]
Is this working after this morning's PR or is it still broken? Do you think something with the Discord PR caused this or something else?

**Comment by jonezy35** [comment]
I was able to pull the lscr.io:latest image and all seems to be working on my end. See the screenshot below to see that test notifications, speedtest notifications, and threshold notifications are all working. See the docker-compose.yml for reference as well.

<img width="931" alt="Screenshot 2024-02-23 at 11 40 53 AM" src="https://github.com/alexjustesen/speedtest-tracker/assets/103131545/fc99a0f0-2d49-40df-8be1-d276851502ae">

```
version: '3.4'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8080:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
        volumes:
            - ./config:/config
            - ./web:/etc/ssl/web
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest_tracker
            - MARIADB_USER=speedy
            - MARIADB_PASSWORD=password
            - MARIADB_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
volumes:
  speedtest-db:
```
