### ISSUE TITLE
UI extremely slow

### ISSUE THREAD

**Issue by garanda21** [alexjustesen/speedtest-tracker#127]
**Describe the bug**
From login, to navigate on web application, every click takes to many seconds. Maybe duplicate from issue #92, but he behaviour is exactly the same, loads up to 20 seconds.

**To Reproduce**
1. Go to 'https://IP:8443'
2. Click on 'Login'
3. Navigate to the application menus
4. See slowness

**Expected behavior**
Faster load on ms. Actually is taking up to 18 seconds to load some pages

**Environment (please complete the following information):**
 - OS: Docker
-  Architecture: [e.g. arm64, amd64]
 - Browser [safari]
 - Version 0.2.0

**Screenshots**
Login screen:
<img width="629" alt="Loading screen" src="https://user-images.githubusercontent.com/29885913/200138376-3debc17d-dd01-4d25-a86a-8a8d77bfc5de.png">

Dashboard:
<img width="641" alt="Web application" src="https://user-images.githubusercontent.com/29885913/200138388-fa5ccd75-a91c-49ac-92d2-f5b61af109af.png">

**Logs**
<img width="1459" alt="Screenshot 2022-11-05 at 21 48 41" src="https://user-images.githubusercontent.com/9530250/200140744-961162fc-394b-4cde-bcb0-92cd8e2e6528.png">

Console:
<img width="852" alt="Console errors" src="https://user-images.githubusercontent.com/29885913/200138394-812cd971-b59a-4177-9d9f-2f2ccdcafb15.png">

**Additional context**
I'm using docker with sqlite. Mapped config file and accessing trough mi local IP and HTTPS.

**Comment by cdaringe** [comment]
can you share your exact config and boot mechanism/commands/etc?

**Comment by alexjustesen** [comment]
@garanda21 can you log into your container's terminal and run `php artisan optimize`? This will refresh the application cache which can improve performance

**Comment by garanda21** [comment]
> php artisan optimize

Done, result: 

```  
  INFO  Caching the framework bootstrap files.  

  config ................................................................................. 134ms DONE
  routes ................................................................................. 43ms DONE
```
But there's no much difference, here is the docker config that I'm using:

```
docker run -d --name speedtest-tracker \
    -p 8443:443 \
    -e PUID=1000 \ 
    -e PGID=1000 \
    -v /path/to/directory:/config \
    -v /path/to/directory/certs:/etc/ssl/web\
    ghcr.io/alexjustesen/speedtest-tracker:latest
```
Not estrange commands or anything else on boot.

I'm trying to test with `SSL_MODE=off` or `SSL_MODE=mixed`, but is not possible to use only port 80, the application always redirect to https no matter what, adicional every time that I change SSL_MODE, the log shows this error: *`nginx: [emerg] a duplicate default server for 0.0.0.0:80 in /etc/nginx/site-opts.d/http.conf:1`* and nothing works, I have to recreate the container.

**Comment by mztiq** [comment]
The UI is very slow for me too, when I click on the "results" tab it takes anything from 15 - 30 sec to load.
Already tried `php artisan optimize`, no noticable difference tho.

Here's my docker-compose.yml (changed volume mapping path and port):

```
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '<port>:443'
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - '/path/to/config:/config'
        restart: unless-stopped
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
```
