### ISSUE TITLE
Fresh install with latest image gives error

### ISSUE THREAD

**Issue by Okami-** [alexjustesen/speedtest-tracker#1294]
Using docker compose with the most current image I get a 500 error. Checking logs it states that I'm missing a cache table in the sqlite db. This is from a fresh install and I deleted everything to make sure. I've tried both deleting the database.sqlite and starting a fresh build with a fresh image and also creating it and doing the same both leading to the same error.

```
In Connection.php line 829:
                                                                               
  SQLSTATE[HY000]: General error: 1 no such table: cache (Connection: sqlite,  
   SQL: select * from "cache" where "key" = laravel_cache_illuminate:queue:re  
  start limit 1)                                                               
                                                                               
In Connection.php line 423:
                                                          
  SQLSTATE[HY000]: General error: 1 no such table: cache  
```

Compose:

```
version: '3.3'
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    ports:
     - 8982:80
     - 8943:443
    environment:
     - PUID=1000
     - PGID=1000
     - DB_CONNECTION=sqlite
    volumes:
     - /data/appdata/speedtest-tracker/config:/config
    restart: unless-stopped

```
