### ISSUE TITLE
Elements of the Web GUI page not loaded with HTTPS

### ISSUE THREAD

**Issue by dogeMcdogeface** [alexjustesen/speedtest-tracker#1358]
I noticed that Firefox gave a mixed content warning icon when loading over https. Checking the developer console informs us that 

```
Mixed Content: The page at 'https://speedtest.site.net/admin' was loaded over HTTPS, but requested an insecure stylesheet 'http://speedtest.site.net/fonts/inter/inter.css'. This request has been blocked; the content must be served over HTTPS.
admin:1  Mixed Content: The page at 'https://speedtest.site.net/admin' was loaded over HTTPS, but requested an insecure favicon 'http://speedtest.site.net/img/speedtest-tracker-icon.png'. This request has been blocked; the content must be served over HTTPS.
```

I have configured NGINX (linuxserver-swag) to always use https, and also added ` - FORCE_HTTPS=true` to speedtest-tracker's docker compose.

**To Reproduce**
1. Go to 'https://speedtest-tracker.site.net/'
2. Open developer console
3. See error

**Environment (please complete the following information):**
 - OS: Debian
 - Browser any
 - Using latest speedtest-tracker from linuxserver

**Screenshots**
![image](https://github.com/alexjustesen/speedtest-tracker/assets/79205861/9121e3fb-7e06-4ed8-8123-45b3e2c5c21a)

**Additional context**
I peeped at the html page from the inspector, and while most requests are hardcoded with https, the few problematic ones are not. Not sure if this was an oversight or there's a reason behind this. I think at least with ` - FORCE_HTTPS=true` these should also be performed with https

**Comment by alexjustesen** [comment]
Is your `APP_URL` set to the `https://` prefix for your domain?

**Comment by dogeMcdogeface** [comment]
> Is your `APP_URL` set to the `https://` prefix for your domain?

I will check presently, in what context (file)?

**Comment by alexjustesen** [comment]
This needs to be set in your `.env` file in the mounted volume or directory. If you're not mounting anything then it should be set as an environment variable.

**Comment by tobidemski** [comment]
Had the same issue. I fixed it by setting the env variable "ASSET_URL" to the same value as my APP_URL.

Example
```
APP_URL: "https://speedtest.example.com"
ASSET_URL: "https://speedtest.example.com"
```

**Comment by alexjustesen** [comment]
`ASSET_URL` can be used to "force" compiled assets to use a specific domain, also good for if the assets are served by a CDN.

**Comment by dogeMcdogeface** [comment]
Is there some way to do this without hardcoding the url in the docker file? I would prefer to keep any explicit reference to domains in my Nginx configuration as i've been able to do so far.

**Comment by alexjustesen** [comment]
You don't have to hard code it, just pass it into the container as an environment variable.

**Comment by kmanwar89** [comment]
I'm also facing this behavior. I just did a docker compose pull today just in case it was a bug that was fixed in later versions - no luck. I'm also on Linux (Ubuntu-derivative), and switching over to Traefik as my reverse proxy, but I noticed this behavior in my previous reverse proxy (NPM) as well.  It used to work, so I'm not sure at what point it "broke"

This is what the developer console of a private Firefox window shows:

![image](https://github.com/alexjustesen/speedtest-tracker/assets/11323060/53f8c5d9-abe8-4184-b679-1dd50d5a933b)

I tried the guidance from [Mozilla](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) around mixed content and to adjust the relevant flag in about:config - no change

My compose file:

```
---
services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        container_name: speedtest-tracker
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=sqlite
        volumes:
            - ./config:/config
            - ./web:/etc/ssl/web
        working_dir: /app/www
#        ports:
#            - 9010:80
#            - 9011:443
        networks:
          - services
        labels:
          - traefik.enable=true  # we enable Traefik for this service
          - traefik.http.routers.speed.entrypoints=web # Listens on the entrypoint "web", i.e. port 80
          - traefik.http.routers.speed.rule=Host(`speed.kadaranwar.com`)  # we specify the rule to access our service
          - traefik.http.routers.speed.middlewares=traefik-auth
          - traefik.http.middlewares.traefik-auth.basicauth.users=user:hashed_password
networks:
  services:
    name: services
    external: true 
```

I added in the asset URL and APP_URL, no change in behavior. Here's my .env, located within <parent directory/config>
```
# A full list of options can be found in the '.env.example' file.

# Application key
# Used for encryption where needed, if a key is not generated run: php artisan key:generate
APP_KEY=

# Application URL
# Not used in the URL but effects links in emails and notifications: https://docs.speedtest-tracker.dev/faqs#links-in-emails-dont-point-to-the-correct-url
#APP_URL=http://localhost
APP_URL=https://speed.kadaranwar.com
# Potential fix below for graphs not loading after transitioning to traefik (or maybe it's https related?)
# Relevant link: https://github.com/alexjustesen/speedtest-tracker/issues/1358
ASSET_URL=https://speed.kadaranwar.com

# SMTP mail config
# Only SMTP protocol is supported at this time: https://docs.speedtest-tracker.dev/settings/notifications/mail
MAIL_MAILER=smtp
MAIL_HOST=mailhog
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="Speedtest Tracker"

# Telegram bot config
TELEGRAM_BOT_TOKEN=null
```

Happy to share any other files that help towards a resolution, and I'll keep poking around in the interim. Thanks!
