### ISSUE TITLE
InfluxDB - could not resolve host

### ISSUE THREAD

**Issue by bvarick** [alexjustesen/speedtest-tracker#1398]
I host speedtest-tracker in a docker container, and recently updated to the LinuxServer container. I also host InfluxDB on a seperate container on the same docker network. This setup has been working great until I switched to the LinuxServer container. No data since the switch has made it into InfluxDB, and I'm getting a `could not resolve host` error in the logs:
```
[2024-04-22 01:32:04] production.INFO: GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: influxdb (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://influxdb:8086/api/v2/write?org=*******&bucket=speedtest&precision=s in /app/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210

```

Any suggestions how to fix this. Nothing else has changed about my docker networking. I can ping the host `influxdb` from within the speedtest-tracker container.

**Comment by bvarick** [comment]
```
---
services:
  speedtest:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest
#    ports:
#      - '8080:80'
#      - '8443:443'
    environment:
      - PUID=1000
      - PGID=1000
      - APP_KEY=base64:************
      - DB_CONNECTION=sqlite
    volumes:
      - '/opt/dendroalsia/speedtest/config:/config'
#      - '/opt/dendroalsia/speedtest/web:/etc/ssl/web'
    restart: unless-stopped
    networks:
      - swag
networks:
  swag:
    external: true
```
