### ISSUE TITLE
Service never starts when launch as a service in a docker swarm

### ISSUE THREAD

**Issue by tristangrimaux** [alexjustesen/speedtest-tracker#1410]
I am trying to integrate speedtest-tracker inside a docker stack which results in an endless loop of preparing - ready - starting. If I start a local container with a very similar docker compose file everything works fine

`docker stack deploy  --detach=false --compose-file docker-stack.yaml house`

this is the **docker-stack.yaml** file
```
services:
  speedtracker:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - homepage.group=Network
        - homepage.name=SpeedTracker
        - homepage.icon=mdi-web
        - homepage.href=http://10.10.20.8:4501
        - homepage.description=Speed tracker
        - homepage.widget.type=speedtest
        - homepage.widget.url=http://10.10.20.8:4501

    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=sqlite
      - APP_KEY=base64:xxxxxxx=
      - APP_DEBUG=true

    hostname: speedtracker
    image: lscr.io/linuxserver/speedtest-tracker:latest
    ports:
      - 4501:80/tcp
    volumes:
      - type: volume
        source: cfg_speedtracker
        target: /config
        volume:
          nocopy: true

    #working_dir: /config
    #networks:
    #  - housenet

volumes:
  cfg_speedtracker:
    driver_opts:
      type: "nfs4"
      o: "addr=10.10.20.8,soft,rw"
      device: ":/opt/dockerapps/configs/infra/speedtracker"

```
