### ISSUE TITLE
[Feature Req] set username and password in environment variable

### ISSUE THREAD

**Issue by svenvg93** [alexjustesen/speedtest-tracker#1428]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
Instead of having a default username and password to change, which is optional. It would be nice to set the username and password of the first user  in the environment variable of the docker container. 

Example
```
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        image: lscr.io/linuxserver/speedtest-tracker:0.19.0
        ports:
            - 8080:80
        environment:
            - TZ=Europe/Amsterdam
            - SPEEDTEST_USERNAME=speedtest
            - SPEEDTEST_PASSWORD=Tracker
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=sqlite
```
 

**Additional context**
N/A
