### ISSUE TITLE
Speedtest Tracker tries to connect to PG using root login

### ISSUE THREAD

**Issue by mmomjian** [alexjustesen/speedtest-tracker#1432]
**Describe the bug**
The Speedtest Tracker container seems to intermittently not use the provided PG login credentials. I have specified DB_USERNAME and DB_PASSWORD, but intermittently I get auth log failures in the Postgres logs.  I changed the IP of the Speedtest Tracker container to confirm it was the source of the logs, and it is. Otherwise, results and notifications are stored in the database under the proper username.

**Environment (please complete the following information):**
 - OS: Debian
-  Architecture: amd64, Docker, LSIO container
 - Browser n/a
 - Version 0.19.0
 - Postgres 15

**Logs**
```
postgresql-15-main.log.1:2024-05-05 06:33:10.960 EDT [1904103] root@root FATAL:  no pg_hba.conf entry for host "172.28.0.81", user "root", database "root", SSL encryption
postgresql-15-main.log.1:2024-05-05 06:33:10.962 EDT [1904127] root@root FATAL:  no pg_hba.conf entry for host "172.28.0.81", user "root", database "root", no encryption
postgresql-15-main.log:2024-05-16 15:10:39.707 EDT [2828520] root@root FATAL:  no pg_hba.conf entry for host "10.40.10.81", user "root", database "root", SSL encryption
postgresql-15-main.log:2024-05-16 15:10:39.710 EDT [2828529] root@root FATAL:  no pg_hba.conf entry for host "10.40.10.81", user "root", database "root", no encryption
```

**Comment by alexjustesen** [comment]
You probably started the container before setting the initial creds, if you don't have anything in your PG db delete it's volume and let it rebuild with the new authentication credentials.

**Comment by alexjustesen** [comment]
Where are you specifying your `DB_` environment variables?

**Comment by mmomjian** [comment]
docker-compose:

```
        environment:
            TZ: ${tz}
            PUID: '17683'
            PGID: '17683'
            DB_CONNECTION: 'pgsql'
            PUBLIC_DASHBOARD: 'true'
            APP_NAME: 'speedtest tracker'
            DB_HOST: postgres.internaldomain.example
            DB_PORT: 5430
            DB_DATABASE: speedtesttracker
            DB_USERNAME: speedtesttracker
            DB_PASSWORD: <redacted>
            FORCE_HTTPS: 'true'
            HOME: /config
            CACHE_DRIVER: 'database'
```
