### ISSUE TITLE
Mail Notification not working in v.0.19.0

### ISSUE THREAD

**Issue by EinKantHolz** [alexjustesen/speedtest-tracker#1440]
I'm running v.19 and set up the environment like below:

```
MAIL_MAILER=smtp
MAIL_HOST=web49.mailserver.de
MAIL_PORT=465
MAIL_USERNAME=mail@my-server.online
MAIL_PASSWORD=password (tried also "password")
MAIL_ENCRYPTION=SSL
MAIL_FROM_ADDRESS=mail@my-server.online
MAIL_FROM_NAME="Speedtest Server"
TZ=Europe/Berlin
```

And it's not working. Neither the test mail and also not the regular Threshold mail.
What am I missing here?

Docker compose:
```
version: '3.4'
services:
    speedtest-tracker:
        container_name: speedtest-server
        ports:
            - 5710:80
            - 5711:443
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=sqlite
        volumes:
            - /mnt/service-data/speedtest-server:/config
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: always
```
