### ISSUE TITLE
0.20.1: Could not resolve host.

### ISSUE THREAD

**Issue by armond-avanes** [alexjustesen/speedtest-tracker#1484]
**Describe the bug**
I have a brand new docker installation of the latest version (0.20.1), and all my speedtest runs are failing with "Could not resolve host." error message with no error or debug information in the docker logs. The only error message that I see is when I click on the failed test and on its details dialog. I've set all the newly introduced env variables (SPEEDTEST_SCHEDULE, SPEEDTEST_SERVERS, etc).

I tried to extract the servers list by the instructions explained in the following release notes and got a long list:
https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.20.0

Regardless of whether I include the entire list or just a random server, all I get is the same error message explained above.

**Environment (please complete the following information):**
 - OS: Raspberry OS
-  Architecture: arm64
 - Browser: Chrome (on MacOS)
 - Version: 0.20.1

NOTE: Before the most recent updates in the past couple of days, I've been running Speedtest-tracker for the several months (docker) with zero issues on the same hardware and under the same database config (mysql).

**Comment by alexjustesen** [comment]
This means your container could not reach the internet, specifically it attempts to reach Cloudflare `1.1.1.1` to check for an good WAN connection.

https://docs.speedtest-tracker.dev/help/error-messages

**Comment by armond-avanes** [comment]
@alexjustesen I can ping 1.1.1.1 and any other server (either name or IP) from inside the container.

**Comment by alexjustesen** [comment]
Can you check your container logs and see if they provide any more information? I'm doing a pretty simple `GET` request so I'd be surprised if that was the reason for it failing.

https://github.com/alexjustesen/speedtest-tracker/blob/main/app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php#L48-L63

**Comment by armond-avanes** [comment]
That's exactly the issue that I don't get any error details in the logs. Here is the entire log, I'm attaching here:
```
[migrations] started
[migrations] 01-nginx-site-confs-default: executing...
[migrations] 01-nginx-site-confs-default: succeeded
[migrations] done
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
speedtest-tracker: https://github.com/sponsors/alexjustesen
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
Linuxserver.io version: v0.20.1-ls27
Build-date: 2024-06-07T18:52:14+00:00
───────────────────────────────────────
    
Setting resolver to  192.168.1.1
Setting worker_processes to 4
generating self-signed keys in /config/keys, you can replace these with your own keys if required
....
-----
Waiting for DB to be available
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

Can you add some error logging to the catch block? At least to print the value of `$th` variable you're catching there...

**Comment by armond-avanes** [comment]
@alexjustesen I believe I found the root cause.

You're actually doing HTTP GET on `1.1.1.1` and my router is blocking `DNS over HTTP (DoH)` access so that all the connected devices query the router itself for DNS. As a side effect, `HTTP GET 1.1.1.1` is blocked from the client (along with some other DNS servers like `8.8.8.8`) although the router itself is using `1.1.1.1` for for DNS queries. I've seen this behavior on other routers as well and that's for having full control on what the clients are accessing (and to deny if a client should not access a URL/website/domain).

Is it possible that you "ping 1.1.1.1" in your code instead of `HTTP GET` ? This will fix the problem and you can still tell whether there is an active internet connection or not.

**Comment by adrianmusante** [comment]
I have the same error. I tried rollback version to 0.19.0 and works again. 
The ping to 1.1.1.1 fails, I think is blocked by my ISP. However, the ping to 8.8.8.8 (Google DNS) does work. It's possible to use a domain or hostname to check connectivity instead of ip?

**Comment by armond-avanes** [comment]
Maybe this can be something configurable via environment variables so that people can change if the default doesn't work in their current network configuration.

**Comment by armond-avanes** [comment]
I'm also curious to know the reason for introducing the connection checking part in 0.20.x versions. After all, when you hit the actual speedtest servers and if there isn't any active connection, you're going to get the same error message as you get here in the case of `1.1.1.1`. The previous versions without this check were all working fine and as expected. Maybe I'm missing something here...

**Comment by alexjustesen** [comment]
PR incoming which switches the HTTP get request to a ping, but in a nutshell this was to provide better error messages for when the host's internet connection was down.

**Comment by MisterHighping** [comment]
I am not that firm with Github so sorry if it is wrong to write something into a closed issue.
On version 0.20.3 I am still getting the issue with my speedtests. It tells me that the hosts could not get resolved. 
When I switch into the container CLI everything is working as expected regarding the DNS resolution.

```
root@26c1609c5317:/var/log/nginx# nslookup www.google.de
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
Name:	www.google.de
Address: 64.233.184.94

Non-authoritative answer:
Name:	www.google.de
Address: 2a00:1450:400c:c1d::5e

```

The logs of the docker container don't show an issue:

```
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
speedtest-tracker: https://github.com/sponsors/alexjustesen
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
Linuxserver.io version: v0.20.3-ls28
Build-date: 2024-06-08T13:10:45+00:00
───────────────────────────────────────
    
using keys found in /config/keys
Waiting for DB to be available
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2023-04-13 │ 2024-05-28 │ /config/nginx/site-confs/default.conf                                  │
│ 2023-04-13 │ 2024-05-27 │ /config/nginx/nginx.conf                                               │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /config/nginx/site-confs/default.conf:7
[ls.io-init] done.
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /config/nginx/site-confs/default.conf:8
```

If you need further information or specific logs I am glad if I can support.

**Comment by adrianmusante** [comment]
> I am not that firm with Github so sorry if it is wrong to write something into a closed issue. On version 0.20.3 I am still getting the issue with my speedtests. It tells me that the hosts could not get resolved. When I switch into the container CLI everything is working as expected regarding the DNS resolution.
> 
> ```
> root@26c1609c5317:/var/log/nginx# nslookup www.google.de
> Server:		127.0.0.11
> Address:	127.0.0.11:53
> 
> Non-authoritative answer:
> Name:	www.google.de
> Address: 64.233.184.94
> 
> Non-authoritative answer:
> Name:	www.google.de
> Address: 2a00:1450:400c:c1d::5e
> ```
> 
> The logs of the docker container don't show an issue:
> 
> ```
>    Brought to you by linuxserver.io
> ───────────────────────────────────────
> To support the app dev(s) visit:
> speedtest-tracker: https://github.com/sponsors/alexjustesen
> To support LSIO projects visit:
> https://www.linuxserver.io/donate/
> ───────────────────────────────────────
> GID/UID
> ───────────────────────────────────────
> User UID:    1000
> User GID:    1000
> ───────────────────────────────────────
> Linuxserver.io version: v0.20.3-ls28
> Build-date: 2024-06-08T13:10:45+00:00
> ───────────────────────────────────────
>     
> using keys found in /config/keys
> Waiting for DB to be available
> **** The following active confs have different version dates than the samples that are shipped. ****
> **** This may be due to user customization or an update to the samples. ****
> **** You should compare the following files to the samples in the same folder and update them. ****
> **** Use the link at the top of the file to view the changelog. ****
> ┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
> │  old date  │  new date  │ path                                                                   │
> ├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
> │ 2023-04-13 │ 2024-05-28 │ /config/nginx/site-confs/default.conf                                  │
> │ 2023-04-13 │ 2024-05-27 │ /config/nginx/nginx.conf                                               │
> └────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
> [custom-init] No custom files found, skipping...
> nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /config/nginx/site-confs/default.conf:7
> [ls.io-init] done.
> nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /config/nginx/site-confs/default.conf:8
> ```
> 
> If you need further information or specific logs I am glad if I can support.

The version 0.20.3 added the environment variable `SPEEDTEST_PING_URL`, which defaults to using the value 1.1.1.1. Try running `ping 1.1.1.1`? In my case, after defining the variable with my ISP's DNS, the problem was resolved.

**Comment by MisterHighping** [comment]
Thanks for the hint with ``` SPEEDTEST_PING_URL``` but it doesn't seem to do the trick:
I set my local DNS Server as a URL target and also tried Google DNS for an example but everytime I get the error message Could not resolve host when doing a speedtest.
```
root@c0273c8878a4:/# ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1): 56 data bytes
64 bytes from 1.1.1.1: seq=0 ttl=55 time=57.556 ms
64 bytes from 1.1.1.1: seq=1 ttl=55 time=56.769 ms
^C
--- 1.1.1.1 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 56.769/57.162/57.556 ms
root@c0273c8878a4:/# ping 192.168.1.200
PING 192.168.1.200 (192.168.1.200): 56 data bytes
64 bytes from 192.168.1.200: seq=0 ttl=63 time=0.398 ms
64 bytes from 192.168.1.200: seq=1 ttl=63 time=0.504 ms
^C
--- 192.168.1.200 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.398/0.451/0.504 ms
```

My configuration after the update looks like this:

```
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8080:80'
            - '8443:443'
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=<KEY>
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=XXX
            - DB_PASSWORD=XXX
            - TZ=Europe/Berlin
            - APP_TIMEZONE=Europe/Berlin
            - DISPLAY_TIMEZONE=Europe/Berlin
            - SPEEDTEST_SCHEDULE=*/15 * * * *
            - SPEEDTEST_SERVERS=30906,63817,47513,29806,61290
            - SPEEDTEST_PING_URL=8.8.4.4
            - PRUNE_RESULTS_OLDER_THAN=0
            - TELEGRAM_BOT_TOKEN='<TOKEN>'
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/docker/speedtest-tracker/config:/config'
            - '/docker/speedtest-tracker/web:/etc/ssl/web'
        image: 'lscr.io/linuxserver/speedtest-tracker:latest'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: postgres:15
        restart: always
        environment:
            - POSTGRES_DB=speedtest_tracker
            - POSTGRES_USER=XXX
            - POSTGRES_PASSWORD=XXX

        volumes:
            - '/docker/speedtest-tracker/speedtest-db:/var/lib/postgresql/data'
volumes:
  speedtest-db:
```
Even after a new configuration nothing changed... Same error. The docker host is able to reach DNS and Internet too...
