### ISSUE TITLE
Old results are 2 hours off 

### ISSUE THREAD

**Issue by svenvg93** [alexjustesen/speedtest-tracker#1487]
**Describe the bug**
After updating to v0.20.2 the old result from v0.19.0 are two hours off in time 

**To Reproduce**
1. Run speediest with 0.19
2. upgrade to 0.20.2 with alll the env needed
3. Check the results table

**Expected behavior**
The time should be correct.

**Environment (please complete the following information):**
 - OS: Ubuntu 24.04
-  Architecture: amd64
 - Browser Safari and Chrome
 - Version 0.20.2

Docker-compose:
```
services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:0.20.2
        container_name: speedtest-tracker
        restart: unless-stopped
        environment:
            - TZ=Europe/Amsterdam 
            - APP_TIMEZONE=Europe/Amsterdam 
            - DISPLAY_TIMEZONE=Europe/Amsterdam 
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=sqlite
            - APP_KEY=base64:longkey
            - APP_URL=exmaple.com
            - SPEEDTEST_SCHEDULE=6 */2 * * *
            - SPEEDTEST_SERVERS=52365
            - PRUNE_RESULTS_OLDER_THAN=0
            - CHART_DATETIME_FORMAT="j M Y,  G:i:s"
        volumes:
            - speedtest-tracker:/config
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.speedtest.rule=Host(`example.com`)"
            - "traefik.http.routers.speedtest.entrypoints=websecure"
            - "traefik.http.routers.speedtest.tls=true"
            - "traefik.http.routers.speedtest.tls.certresolver=letencrypt"
            - "traefik.http.services.speedtest.loadbalancer.server.port=80"
        networks:
            - proxy

volumes:
  speedtest-tracker:
    name: speedtest-tracker

networks:
  proxy:
    name: proxy

```

**Screenshots**
v0.19

<img width="1222" alt="Scherm­afbeelding 2024-06-08 om 06 06 53" src="https://github.com/alexjustesen/speedtest-tracker/assets/4511676/55628f29-dbd8-404e-b0c3-18b00cb6dc8e">

v0.20

<img width="1233" alt="Scherm­afbeelding 2024-06-08 om 06 13 45" src="https://github.com/alexjustesen/speedtest-tracker/assets/4511676/a079aed2-de3e-42db-aa40-775d2dd5914e">
