### ISSUE TITLE
General admin page missing when used with traefik proxy

### ISSUE THREAD

**Issue by Tenyun** [alexjustesen/speedtest-tracker#1490]
**Describe the bug**
Freshly installed app behind traefik cannot access the general admin page (I get 404 when I call the url directly)

**To Reproduce**
1. Install with traefik
2. Login with admin@example.com
3. Missing General under Settings

**Expected behavior**
Show General Settings when logged in

**Environment (please complete the following information):**
 ```
version: "3.3"
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - speedtest-tracker-config:/config
      - speedtest-tracker-web:/etc/ssl/web
    environment:
      - APP_DEBUG=true
      - APP_NAME=Home-Tracker
      - APP_KEY=*****
      - PUBLIC_DASHBOARD=true
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=pgsql
      - DB_HOST=st-db
      - DB_PORT=5432
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME=*****
      - DB_PASSWORD=*****
      - TZ=Europe/Berlin
    labels:
      - traefik.enable=true
      - traefik.http.routers.speedtest-tracker.entrypoints=http
      - traefik.http.routers.speedtest-tracker.rule=Host(`st.local.example.com`)
      - traefik.http.middlewares.speedtest-tracker-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.speedtest-tracker.middlewares=speedtest-tracker-https-redirect
      - traefik.http.routers.speedtest-tracker-secure.entrypoints=https
      - traefik.http.routers.speedtest-tracker-secure.rule=Host(`st.local.example.com`)
      - traefik.http.routers.speedtest-tracker-secure.tls=true
      - traefik.http.routers.speedtest-tracker-secure.service=speedtest-tracker
      - traefik.http.services.speedtest-tracker.loadbalancer.server.port=80
      - traefik.docker.network=proxy
    depends_on:
      - st-db
  st-db:
    image: postgres:15
    restart: always
    networks:
      - proxy
    environment:
      - POSTGRES_DB=speedtest_tracker
      - POSTGRES_USER=*****
      - POSTGRES_PASSWORD=*****
    volumes:
      - speedtest-db:/var/lib/postgresql/data
volumes:
  speedtest-tracker-config: null
  speedtest-tracker-web: null
  speedtest-db: null
networks:
  proxy:
    external: true
```

**Screenshots**
![screenshot-2024Jun08-112035](https://github.com/alexjustesen/speedtest-tracker/assets/8769765/afd52ec6-6fd3-4d3a-9aa1-4eb912938b68)

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**
