### ISSUE TITLE
API_KEY issue

### ISSUE THREAD

**Issue by dsxcsman** [alexjustesen/speedtest-tracker#1496]
**Describe the bug**

Since the version changed, I decided to add my API_KEY as suggested (I got it from speedtest-tracker.dev).

So here is my Portainer stack :

version: '3.8'
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    ports:
      - "8091:80"
    environment:
      - PUID=1033
      - PGID=1000
      - DB_CONNECTION=sqlite
      - API_KEY=base64****
    volumes:
      - /volume1/docker/speedtest-tracker:/config
    labels:        
      - "com.centurylinklabs.watchtower.enable=true"  
    security_opt:
    - no-new-privileges:true
    restart: on-failure:5

Here is the result :

![Screenshot_20240608_160045](https://github.com/alexjustesen/speedtest-tracker/assets/5779819/d0596d13-fa66-43f4-8eca-ca524c804199)

I also tried to add the API_KEY directly in Portainer without success.

![Screenshot_20240608_160123](https://github.com/alexjustesen/speedtest-tracker/assets/5779819/6759cb54-bb8d-4131-b81d-61ed266fbc35)

I also tried a fresh install but the result is the same. 

It looks like whatever I do, the API_KEY is not used. Is there any other manipulation to do ?

**Comment by ppittle** [comment]
I was able to get it working following the note in https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.20.0

```
 speedtest-tracker:
    image:  lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    networks:
      - misc
    volumes:
      - /portainer/Files/AppData/Config/speedtest-tracker-alexjustesen:/config            
    ports:
      - 8765:80
    environment:
        - PUID 1000
        - PGID 1000
        - OOKLA_EULA_GDPR=true        
        - DB_CONNECTION=sqlite
        - PUBLIC_DASHBOARD=true
        - APP_KEY=base64:clCteBaLyIwfNFKMejtH+KezhXR***********
```

Do check your naming , the env variable must be named `APP_KEY`.  It looks correct in your screenshot, but is not correct in your "portainer stack"
