### ISSUE TITLE
Does not work anymore is restarting

### ISSUE THREAD

**Issue by zackmuc** [alexjustesen/speedtest-tracker#1504]
**Describe the bug**
I get this:
% Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- 0:00:01 --:--:-- 0 curl: (22) The requested URL returned error: 500 

**To Reproduce**
`services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - APP_TIMEZONE=Europe/Berlin
      - DISPLAY_TIMEZONE=Europe/Berlin
      - APP_KEY= base64:ZbPPNJ2cJ601f6jQp9GVAsI5fZAuXz0idsgxWAKJhcY=
      - DB_CONNECTION=sqlite
      - DB_HOST= #optional
      - DB_PORT= #optional
      - DB_DATABASE= #optional
      - DB_USERNAME= #optional
      - DB_PASSWORD= #optional
      - APP_DEBUG=#true
      - SPEEDTEST_SCHEDULE= 0 */1 * * * 
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - traefik-backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-backend"
      - "traefik.http.routers.speedtestnew-secure.entrypoints=websecure"
      - "traefik.http.routers.speedtestnew-secure.rule=Host(`speedtestnew.xxxx.xxx`)"
      - "traefik.http.routers.speedtestnew-secure.service=speedtestnew"
      - "traefik.http.services.speedtestnew.loadbalancer.server.port=80"
    volumes:
      - /portainer/Files/AppData/Config/speedtest_linuxserver:/config
    ports:
      - 89:80
    restart: unless-stopped

networks:
 traefik-backend:
   external:
     name: traefik-backend
`

**Expected behavior**
Should work

**Environment (please complete the following information):**
Portainer / Traffik on Rasp 4

**Screenshots**
get an 404
**Logs**
`[migrations] 01-nginx-site-confs-default: skipped

[migrations] done

───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗

      ██║     ██╔════╝██║██╔═══██╗

      ██║     ███████╗██║██║   ██║

      ██║     ╚════██║██║██║   ██║

      ███████╗███████║██║╚██████╔╝

      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io

───────────────────────────────────────

To support the app dev(s) visit:

speedtest-tracker: https://github.com/sponsors/alexjustesen

To support LSIO projects visit:

https://www.linuxserver.io/donate/

───────────────────────────────────────

GID/UID

───────────────────────────────────────

User UID:    1000

User GID:    1000

───────────────────────────────────────

Linuxserver.io version: v0.20.3-ls28

Build-date: 2024-06-08T13:10:45+00:00

───────────────────────────────────────

    

using keys found in /config/keys

[custom-init] No custom files found, skipping...

[ls.io-init] done.`

**Comment by c11umw** [comment]
We've seen issues with latest (0.20.3)
If it worked before, can you try forcing 0.20.2?

**Comment by svenvg93** [comment]
Can you place the docker compose and log in code blocks it’s pretty hard to read now 😅. 

Also when are you getting the 404 which url are you trying to open? And it the 404 of the application or from traefik? 

Since you’re using Traefik to reach it you need to set the APP_URL environment with your url.

**Comment by zackmuc** [comment]
`services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - APP_TIMEZONE=Europe/Berlin
      - DISPLAY_TIMEZONE=Europe/Berlin
      - APP_KEY= base64:ZbPPNJ2cJ601f6jQp9GVAsI5fZAuXz0idsgxWAKJhcY=
      - DB_CONNECTION=sqlite
      - DB_HOST= #optional
      - DB_PORT= #optional
      - DB_DATABASE= #optional
      - DB_USERNAME= #optional
      - DB_PASSWORD= #optional
      - APP_DEBUG=#true
      - SPEEDTEST_SCHEDULE= 0 */1 * * * 
      - APP_URL = speedtestnew.xxx.xx
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - traefik-backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-backend"
      - "traefik.http.routers.speedtestnew-secure.entrypoints=websecure"
      - "traefik.http.routers.speedtestnew-secure.rule=Host(`speedtestnew.xxx.xx`)"
      - "traefik.http.routers.speedtestnew-secure.service=speedtestnew"
      - "traefik.http.services.speedtestnew.loadbalancer.server.port=80"
    volumes:
      - /portainer/Files/AppData/Config/speedtest_linuxserver:/config
    ports:
      - 89:80
    restart: unless-stopped


networks:
 traefik-backend:
   external:
     name: traefik-backend
`

**Comment by zackmuc** [comment]
same with 20.2 sorry doese not work with code
[dockercompose.txt](https://github.com/user-attachments/files/15751361/dockercompose.txt)

**Comment by svenvg93** [comment]
You are using sqlite the environment for the db are not needed then. These can be removed. Now it just fives empty values in the container. 

```
      - DB_HOST= #optional
      - DB_PORT= #optional
      - DB_DATABASE= #optional
      - DB_USERNAME= #optional
      - DB_PASSWORD= #optional
```


`      - APP_DEBUG=#true`

I dont see anything obvious when comparing it with my compose which is has Traefik;

```
services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:0.20.3
        container_name: speedtest-tracker
        restart: unless-stopped
        environment:
            - TZ=Europe/Amsterdam
            - APP_TIMEZONE=Europe/Amsterdam
            - DISPLAY_TIMEZONE=Europe/Amsterdam
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=sqlite
            - APP_KEY=base64:longket
            - APP_URL=speedtest.example.com
            - SPEEDTEST_PING_URL=1.1.1.1
            - SPEEDTEST_SCHEDULE=6 */2 * * *
            - SPEEDTEST_SERVERS=52365
            - PRUNE_RESULTS_OLDER_THAN=0
            - DATETIME_FORMAT="j M Y, G:i:s"
            - CHART_DATETIME_FORMAT="j M, G:i:s"
        volumes:
            - speedtest-tracker:/config
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.speedtest.rule=Host(`speedtest.example.com`)"
            - "traefik.http.routers.speedtest.entrypoints=websecure"
            - "traefik.http.routers.speedtest.tls=true"
            - "traefik.http.routers.speedtest.tls.certresolver=letencrypt"
            - "traefik.http.services.speedtest.loadbalancer.server.port=80"
        networks:
            - proxy

volumes:
  speedtest-tracker:
    name: speedtest-tracker

networks:
  proxy:
    name: proxy
```

The only difference I see are 

- You dont have the tis certificate defined in the labels. As you use websecure it will give you the default traefik cert. 
- I Dont expose the port as traefik handles the incoming traffic.

Maybe as a test remove the treafik config and APP_URL to see if you can reach it directly on http://ipofserver:89. Just to make sure the application works.
