### ISSUE TITLE
Server 500 after update to latest linuxserver image

### ISSUE THREAD

**Issue by riddlecp** [alexjustesen/speedtest-tracker#1536]
**Describe the bug**
upon update and then *completely* fresh recreate getting a server error about unsupported cipher or incorrect key length

**To Reproduce**
1. set up and start through docker compose
2. Launch HTTP session in browser - not using HTTPS

**Expected behavior**
Speedtest Tracker dashboard

**Environment:**
 - OS: OpenSuse Leap 15.5
-  Architecture: amd64
 - Browser: chrome
 - Version: v0.20.6-ls29

**Screenshots**
![192 168 1 129_82_](https://github.com/alexjustesen/speedtest-tracker/assets/52296073/19073e02-dcba-41c2-a4c2-2def7ff3034e)

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**
Not using HTTPS as there's no need for me to want to do that internally.

**Docker Compose**
```
---
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    hostname: speedtest-tracker
    environment:
      - PUID=1001
      - PGID=1001
      - DB_CONNECTION=sqlite
      - PUBLIC_DASHBOARD=true
      - APP_KEY= base64:/K2FVH1Fi3PeDNaZ5fYUu8fDUo0U6L50aWTq4q59S0k=
      - SPEEDTEST_SCHEDULE="0 * * * *"
      - PRUNE_RESULTS_OLDER_THAN=90
      - APP_TIMEZONE=America/New_York
      - APP_DEBUG=true
      #- DB_HOST= #optional
      #- DB_PORT= #optional
      #- DB_DATABASE= #optional
      #- DB_USERNAME= #optional
      #- DB_PASSWORD= #optional
    volumes:
      - /mnt2/speedtest_data/config:/config
    ports:
      - 82:80
    restart: unless-stopped
    networks:
      - dockerbridge
networks:
  dockerbridge:
    external: true
```
