### ISSUE TITLE
webhook not working via https

### ISSUE THREAD

**Issue by aifrog** [alexjustesen/speedtest-tracker#1544]
I can get the webhook working well when using http. However, when using https this would not work. No problem at the receiving end as tested with a simple browser. Whats wrong?
Best, H-C

**Comment by svenvg93** [comment]
I don’t have any problems when using https://webhook.site/ which uses https as well for link.
Can you share your setting used?

**Comment by TheGroundZero** [comment]
No issues here using HTTPS endpoint of Healthchecks.io

Does your HTTPS endpoint have a self-signed certificate?

**Comment by aifrog** [comment]
Its a certificate from Letsencrypt and I call "https://speedtest.domain.abc/hook/speedtest". This works well from a browser on the host, but from inside the docker container. A direct call via http is tested and works well (not going through the reverse proxy). Configuration as follows:

```yaml
version: "3.9"
services:
  db:
    image: postgres:16
    container_name: SpeedTest-TRACKER-DB
    hostname: speedtestracker-db
    mem_limit: 1g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "speedtest", "-U", "speedtestuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume1/docker/speedtest/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: speedtest
      POSTGRES_USER: speedtestuser
      POSTGRES_PASSWORD: xxxxxx
    restart: on-failure:5

  speedtest-tracker:
    image: ghcr.io/linuxserver/speedtest-tracker:latest
    container_name: SpeedTest-TRACKER
    healthcheck:
     test: curl -f http://localhost:80/ || exit 1
    environment:
       SPEEDTEST_SCHEDULE: "*/15 * * * *"
       SPEEDTEST_SERVERS: "53257,41540,44081"
       MAIL_HOST: xx.xxx.xxx
       MAIL_PORT: 465
       MAIL_USERNAME: xxx
       MAIL_PASSWORD: xxx
       MAIL_ENCRYPTION: tls
       MAIL_FROM_ADDRESS: xxx@xx.xxx
       PUBLIC_DASHBOARD: true
       PUID: 1047
       PGID: 1000
       TZ: Europe/Berlin
       APP_TIMEZONE: Europe/Berlin
       DISPLAY_TIMEZONE: Europe/Berlin
       DB_CONNECTION: pgsql
       DB_HOST: speedtestracker-db
       DB_PORT: 5432
       DB_DATABASE: speedtest
       DB_USERNAME: speedtestuser
       DB_PASSWORD: xxxxxxx
       APP_KEY: xxxxxxxxxxxxxxxxx
       #APP_KEY: Not mandatory. docker exec speedtest-tracker php /app/www/artisan key:generate --show
    volumes:
      - /volume1/docker/speedtest/config:/config:rw
    ports:
      - 8999:80
    restart: on-failure:5
```
