### ISSUE TITLE
all is working and test are working but graphs are not showing

### ISSUE THREAD

**Issue by spupuz** [alexjustesen/speedtest-tracker#1558]
![image](https://github.com/alexjustesen/speedtest-tracker/assets/1721792/0d8fe557-83c5-4024-9626-ada316142176)
all is working and test are working but graphs are not showing

**Comment by truthsword** [comment]
I'm seeing this too... but despite API addition and image source update, my last graph point (month view) is June 10.

```
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    environment:
      - PUID=1000
      - PGID=1000
      - APP_NAME=My Speedtest Tracker
      - APP_KEY=base64:xxx=
      - PUBLIC_DASHBOARD=true
      - DB_CONNECTION=sqlite
      - APP_TIMEZONE=America/New_York
      - DISPLAY_TIMEZONE=America/New_York
    network_mode: bridge
    ports:
      - 8080:80 #HTTP
#     - "8443:443" #HTTPS
    volumes:
      - config:/config
      - ssl-keys:/config/keys

    healthcheck:
      test: curl -fSs http://localhost/api/healthcheck || exit 1
      interval: 60s
      retries: 5
      start_period: 30s
      timeout: 10s
```
