### ISSUE TITLE
Font and favicon assets do not load using https

### ISSUE THREAD

**Issue by alexjustesen** [alexjustesen/speedtest-tracker#1589]
> I am unable to get this image working behind a reverse proxy, I use traefik, but get mixed content errors on page as the content seems to be loading `http` on a `https` page. I tried setting `APP_URL` parameter, but looks like that is not supported.
> 
> Can someone help?

I have this mixed content problem too.

I just upgraded from v0.18.1 to v0.20.7 today, and although the web page loads and I can use it, the stylesheet and the rabbit favicon fail to load.

I am hosting on a Synology DS1517+ NAS with reverse proxy so that I can use HTTPS. The HTML page contains the following links, which are HTTP addresses when they need to be HTTPS addresses to avoid the mixed content situation:
```
<link rel="icon" href="http://<host:port>/img/speedtest-tracker-icon.png">

<link href="http://<host:port>/fonts/inter/inter.css" rel="stylesheet">
```
Here is my docker compose file:
```
services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        container_name: speedtest-tracker
        ports:
            - 8080:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=base64:<key>
            - APP_URL=https://<host:port>
            - DB_CONNECTION=sqlite
            - TZ=Europe/London
            - APP_TIMEZONE=Europe/London
            - DISPLAY_TIMEZONE=Europe/London 
            - SPEEDTEST_SCHEDULE=0 * * * * # every hour on the hour
            - SPEEDTEST_SERVERS=6274,52523,47643,64354
            - PRUNE_RESULTS_OLDER_THAN=0 # the default is 0 which disables result pruning, this value is in days.                       
        volumes:
            - /volume1/docker/speedtest-tracker:/config
        restart: unless-stopped
```
Is there something missing? I don't understand what APP_URL is used for, so maybe I've got that wrong.

_Originally posted by @Bananas-Are-Yellow in https://github.com/alexjustesen/speedtest-tracker/issues/1117#issuecomment-2198068316_

**Comment by svenvg93** [comment]
just my two cents; 
 The `APP_URL`  should not contain a port if Traefik is doing the proxy stuff. It shoudl be the same as set in `traefik.http.routers.speedtest-tracker.rule=Host` Traefik label. (But then i also expects the Gui not to load at all)
 @Bananas-Are-Yellow  Can you share the Traefik config for this one.

**Comment by Bananas-Are-Yellow** [comment]
It was @whizzzkid who [mentioned Traefik](https://github.com/alexjustesen/speedtest-tracker/issues/1117#issuecomment-2076425787). I'm using the reverse proxy facility in my Synology NAS. The settings look like this:

![image](https://github.com/alexjustesen/speedtest-tracker/assets/5648989/a4575c4e-8aef-4b67-9bbb-dc7627b3315d)

The **Custom Header** has nothing listed, and the **Advanced Settings** tab just has default values.

I access Speedtest Tracker using:

https://myhost:8081/admin

**Comment by bitwolfe** [comment]
I ran into this issue as well, having my instance reverse proxied with HAProxy.

I found that since this is a Laravel app, you can set the ASSET_URL environment variable to get around this issue. Like this:
```
        environment:
            - ASSET_URL=https://<hostname>
```

**Comment by Bananas-Are-Yellow** [comment]
Thank you, @bitwolfe, that works for me. I just commented out the `APP_URL` line and added the equivalent `ASSET_URL` line and that fixed it.
```
services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        container_name: speedtest-tracker
        ports:
            - 8080:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=base64:<key>
            # - APP_URL=https://<host:port>
            - ASSET_URL=https://<host:port>
            - DB_CONNECTION=sqlite
            - TZ=Europe/London
            - APP_TIMEZONE=Europe/London
            - DISPLAY_TIMEZONE=Europe/London 
            - SPEEDTEST_SCHEDULE=0 * * * * # every hour on the hour
            - SPEEDTEST_SERVERS=6274,52523,47643,64354
            - PRUNE_RESULTS_OLDER_THAN=0 # the default is 0 which disables result pruning, this value is in days.                       
        volumes:
            - /volume1/docker/speedtest-tracker:/config
        restart: unless-stopped
```
Do I need both, or is that the complete fix?
