### ISSUE TITLE
SPEEDTEST_SCHEDULE has zero effect

### ISSUE THREAD

**Issue by mightywomble** [alexjustesen/speedtest-tracker#1595]
**Describe the bug**
I've followed several links on issues and created this as a docker compose

```
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8080:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=base64:0C4V84+cnlztGJDjmj8jTzSo2pmY7frk9NRpniS+1yU=
            - DB_CONNECTION=sqlite
            - SPEEDTEST_SCHEDULE="*/5 * * * *"
            - SPEEDTEST_SERVERS=6032
        volumes:
            - /opt/docker/speedtest:/config
            - /opt/docker/speedtest//ssl-keys:/config/keys
        image: lscr.io/linuxserver/speedtest-tracker:0.20.6
        restart: unless-stopped
```
Everything loads up, it runs, and I can manually do speed tests, on the dashboard page it appears no scans are schedules

**To Reproduce**
1. created docker compose
2.  run docker compose
3.  setup
4.  change time to any number of variants on the SPEEDTEST_SCHEDULE= line

**Expected behavior**
Speed test runs as per schedule

**Environment (please complete the following information):**
 - OS: Debian 12
-  Architecture: AMD64
 - Browser ALL
 - Version Latest

**Screenshots**

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**
