### ISSUE TITLE
Missing settings?

### ISSUE THREAD

**Issue by renetsk** [alexjustesen/speedtest-tracker#1618]
Hello,
installed latest version 0.20.7 (in portainer) but I'm missing some settings like server, schedule etc.

```
version: "3.9"
services:
  speedtest-tracker:
    container_name: speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:latest

    ports:
      - xxxx:80
      - xxxx:443
    environment:
      - PUID=1000
      - PGID=1000
      - APP_KEY=base64:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
    volumes:
      - /home/xxx/speedtest-tracker:/config
    restart: unless-stopped

```
What's wrong please?
![Snímka obrazovky 2024-07-20 105005](https://github.com/user-attachments/assets/c532979f-4cf0-435c-b719-2ad499bccaa8)
