### ISSUE TITLE
Bug using HTTPS

### ISSUE THREAD

**Issue by devwebhoop** [alexjustesen/speedtest-tracker#1673]
**Describe the bug**

**To Reproduce**
1. Install latest version on docker:

services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8080:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=base64:8qxyTHOmBXEHqq8JWogAVnHTSQ2CbDSuUL5CJmVpV30=
            - APP_URL=https://localhost
            - DB_CONNECTION=sqlite
            - APP_DEBUG=true
            - SPEEDTEST_SCHEDULE=@hourly
        volumes:
            - /home/<username>/speedtest-tracker/config:/config
            - /home/<username>/speedtest-tracker/config/keys:/config/keys
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
3. Proxy it via nginx to https://speed.yourdomain.com
4. Try to load the charts
5. See error

**Expected behavior**
To see graphs

**Screenshots**
![image](https://github.com/user-attachments/assets/925dac70-e25b-4007-8f7a-b7cdd6de95f1)

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**

**Comment by svenvg93** [comment]
Does the same error happen when you set the APP_URL to your full domain name ?

**Comment by alexjustesen** [comment]
Also you can add `FORCE_HTTPS=true` should you continue to have an issue behind a proxy.

**Comment by r3mi** [comment]
I have a similar issue (hope this is ok to comment here):
speedtest-tracker is served over https (behind a reverse proxy), `APP_URL` is set using https also, but some resources fail to load:
- Mixed Content: The page at 'https://speedtest._redacted_/admin' was loaded over HTTPS, but requested an insecure stylesheet 'http://speedtest._redacted_/fonts/inter/inter.css'. This request has been blocked; the content must be served over HTTPS.
- Mixed Content: The page at 'https://speedtest._redacted_/admin' was loaded over HTTPS, but requested an insecure favicon 'http://speedtest._redacted_/img/speedtest-tracker-icon.png'. This request has been blocked; the content must be served over HTTPS.
The last one causes the favicon to be missing.

No difference observed when setting env variable `FORCE_HTTPS` to `true`

Thanks for speedtest-tracker !

**Comment by a-camacho** [comment]
> I have a similar issue (hope this is ok to comment here): speedtest-tracker is served over https (behind a reverse proxy), `APP_URL` is set using https also, but some resources fail to load:
> 
>     * Mixed Content: The page at 'https://speedtest._redacted_/admin' was loaded over HTTPS, but requested an insecure stylesheet 'http://speedtest._redacted_/fonts/inter/inter.css'. This request has been blocked; the content must be served over HTTPS.
> 
>     * Mixed Content: The page at 'https://speedtest._redacted_/admin' was loaded over HTTPS, but requested an insecure favicon 'http://speedtest._redacted_/img/speedtest-tracker-icon.png'. This request has been blocked; the content must be served over HTTPS.
>       The last one causes the favicon to be missing.
> 
> 
> No difference observed when setting env variable `FORCE_HTTPS` to `true`
> 
> Thanks for speedtest-tracker !

Same environment and issue for me.

**Comment by svenvg93** [comment]
@r3mi @a-camacho, between the proxy and the stt container are you using http or https, and on which port.

**Comment by a-camacho** [comment]
> @r3mi @a-camacho, between the proxy and the stt container are you using http or https, and on which port.

Using http between proxy and speedtest-tracker.

**Comment by alexjustesen** [comment]
Just to confirm you restarted the container after updating the env var?

**Comment by r3mi** [comment]
hello, 
For me, using http between reverse_proxy and speedtest-tracker, on default port 80.
APP_URL set to https (the external adress).
Restarted container after trying env `FORCE_HTTPS`=true, but observed not effect.
Not seen other loading problem apart from these 2 resources (`fonts/inter/inter.css` and `img/speedtest-tracker-icon.png`).

**Comment by abonforti** [comment]
> hello, For me, using http between reverse_proxy and speedtest-tracker, on default port 80. APP_URL set to https (the external adress). Restarted container after trying env `FORCE_HTTPS`=true, but observed not effect. Not seen other loading problem apart from these 2 resources (`fonts/inter/inter.css` and `img/speedtest-tracker-icon.png`).

+1 here, same situation

**Comment by svenvg93** [comment]
Hi All, 
Would it be possible to share which proxy you are using and the configuration. So I can try to replicate the problem. So far we haven't seen any problems when using Cloudflare tunnels or Traefik as a proxy.

**Comment by abonforti** [comment]
> Hi All, Would it be possible to share which proxy you are using and the configuration. So I can try to replicate the problem. So far we haven't seen any problems when using Cloudflare tunnels or Traefik as a proxy.

HAProxy [0.63_2](https://github.com/pfsense/FreeBSD-ports/commits/devel/net/pfSense-pkg-haproxy) (not the devel) under pfSense CE 2.7.2-RELEASE.

**Comment by nurfed1** [comment]
The ASSET_URL setting works for me:
```
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    profiles:
      - nas
    restart: unless-stopped
    network_mode: service:vpn
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.remove-frame-options.headers.customresponseheaders.x-frame-options=
      - traefik.http.routers.speedtest-tracker.rule=Host(`${SPEEDTEST_TRACKER_DOMAIN_NAME}`)
      - traefik.http.services.speedtest-tracker.loadbalancer.server.port=80
      - traefik.http.routers.speedtest-tracker.tls.certresolver=letsencryptresolver
      - traefik.http.routers.speedtest-tracker.middlewares=auth-desktop,remove-frame-options
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - DB_CONNECTION=sqlite
      - APP_KEY=${APP_KEY}
      - ASSET_URL=https://${SPEEDTEST_TRACKER_DOMAIN_NAME}
    volumes:
      - ${SPEEDTEST_TRACKER_CONFIG_PATH}:/config
```
