### ISSUE TITLE
url is wrong when using https and non-standard port such as 8443 at same time

### ISSUE THREAD

**Issue by lz37** [alexjustesen/speedtest-tracker#1685]
**Describe the bug**
url is wrong when using https and non-standard port such as 8443 at same time

**To Reproduce**
when setting https and non-standard port, the request of css file is still 443, `FORCE_HTTPS` doesn't even work. I use k8s, and default port of Nginx Ingress is 8443(in china poeople usually can't use 80 and 443 personally)

**Expected behavior**
just like graphs

![image](https://github.com/user-attachments/assets/9aeaa4e8-10a6-448d-b27e-e3ba33d6942a)

**Environment (please complete the following information):**
 - OS: kubectl 1.28.0
-  Architecture: amd64
 - Browser Edge
 - Version [0.21.2](https://hub.docker.com/layers/linuxserver/speedtest-tracker/0.21.2/images/sha256-0a24adc2264dbed650f90b9718a672a1c97cc501fdfbc9d904f17b805fd24cc1?context=explore)

**Screenshots**
![image](https://github.com/user-attachments/assets/9aeaa4e8-10a6-448d-b27e-e3ba33d6942a)

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**
```yaml
apiVersion: v1
kind: Service
metadata:
  name: speedtest
spec:
  ports:
    - name: speedtest
      port: 80
      protocol: TCP
  selector:
    app: speedtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest
  labels:
    app: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      containers:
        - name: speedtest
          image: lscr.io/linuxserver/speedtest-tracker:latest
          resources:
            limits:
              cpu: "0.5"
              memory: 1024Mi
            requests:
              cpu: "0.02"
              memory: 16Mi
          ports:
            - containerPort: 80
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: DB_CONNECTION
              value: pgsql
            - name: SPEEDTEST_SCHEDULE
              value: "0,30 * * * *"
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: speedtest
            - name: DB_USERNAME
              value: xxxxxx
            - name: DB_PASSWORD
              value: xxxxxxx
            - name: DISPLAY_TIMEZONE
              value: "Asia/Shanghai"
            - name: TZ
              value: "Asia/Shanghai"
            - name: PRUNE_RESULTS_OLDER_THAN
              value: "365"
            - name: APP_KEY
              value: xxxxxx
            - name: APP_URL
              value: https://xxxxxx:8443
            - name: FORCE_HTTPS
              value: "true"
            - name: APP_TIMEZONE
              value: "Asia/Shanghai"
            - name: APP_LOCALE
              value: "zh-CN"
          volumeMounts:
              - name: localtime
                readOnly: true
                mountPath: /etc/localtime
              - mountPath: /config
                name: speedtest-tracker
      volumes:
        - name: localtime
          hostPath:
            type: File
            path: /etc/localtime
        - name: speedtest-tracker
          persistentVolumeClaim:
            claimName: nfs-speedtesttracker-config-pvc
---
# ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speedtest
  labels:
    name: speedtest
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "dnspod"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - xxxxxx
      secretName: xxxxx
  rules:
    - host: xxxxx
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: speedtest
                port:
                  number: 80
```
