### ISSUE TITLE
Errors running 0.4.1

### ISSUE THREAD

**Issue by duckunix** [alexjustesen/speedtest-tracker#171]
**Describe the bug**
Saw the new release this morning, so I did the `normal docker-compose stop bandwidth && docker-compose pull bandwidth && docker-compose up -d bandwidth`, and the image refused to start with an error of:
```
production.ERROR: RyanChandler\FilamentLog\FilamentLogServiceProvider::getPages(): Return value must be of type array, null returned {"exception":"[object] (TypeError(code: 0): RyanChandler\\FilamentLog\
\FilamentLogServiceProvider::getPages(): Return value must be of type array, null returned at /var/www/html/vendor/ryangjchandler/filament-log/src/FilamentLogServiceProvider.php:14)
```

**To Reproduce**
1. `docker-compose stop bandwidth`
2. `docker-compose pull bandwidth`
3. `docker-compose up bandwidth`

**Expected behavior**
A nice container with all the new goodies

**Environment (please complete the following information):**
 - OS: EndevourOS full patched this morning with:
   - docker 1:20.10.21-1
   - docker-compose 2.12.2-1
   - linux 6.0.9.arch1-1
 - Architecture: amd6]
 - Version: 0.4.1

**Logs**
```
10:39:21 [don@harper:/mini/config] $ docker-compose up bandwidth
WARN[0000] network proxy: network.external.name is deprecated in favor of network.name
[+] Running 2/2
 ⠿ Container traefik     Running                                                                                                                                                                                                           0.0s
  ⠿ Container bandwidth  Recreated                                                                                                                                                                                                         0.2s
  Attaching to bandwidth
  bandwidth  |
  bandwidth  | --------------------------------------------------------------------
  bandwidth  |  ____                             ____  _     _        _   _
  bandwidth  | / ___|  ___ _ ____   _____ _ __  / ___|(_) __| | ___  | | | |_ __
  bandwidth  | \___ \ / _ \  __\ \ / / _ \  __| \___ \| |/ _` |/ _ \ | | | |  _ \
  bandwidth  |  ___) |  __/ |   \ V /  __/ |     ___) | | (_| |  __/ | |_| | |_) |
  bandwidth  | |____/ \___|_|    \_/ \___|_|    |____/|_|\__,_|\___|  \___/| .__/
  bandwidth  |                                                             |_|
  bandwidth  |
  bandwidth  | Brought to you by serversideup.net
  bandwidth  | --------------------------------------------------------------------
  bandwidth  |
  bandwidth  | To support Server Side Up projects visit:
  bandwidth  | https://serversideup.net/sponsor
  bandwidth  | -------------------------------------
  bandwidth  | GID/UID
  bandwidth  | -------------------------------------
  bandwidth  |
  bandwidth  | User uid:    1000
  bandwidth  | User gid:    1000
  bandwidth  | -------------------------------------
  bandwidth  |
  bandwidth  | 🏃‍♂️ Checking for Laravel automations...
  bandwidth  | 🔐 Linking the storage...
  bandwidth  | 🔐 SSL_MODE has set to FULL, setting the web server to work in HTTPS only...
  bandwidth  | [2022-11-23 10:39:29] production.ERROR: RyanChandler\FilamentLog\FilamentLogServiceProvider::getPages(): Return value must be of type array, null returned {"exception":"[object] (TypeError(code: 0): RyanChandler\\FilamentLog\\FilamentLogServiceProvider::getPages(): Return value must be of type array, null returned at /var/www/html/vendor/ryangjchandler/filament-log/src/FilamentLogServiceProvider.php:14)
  bandwidth  | [stacktrace]
  bandwidth  | #0 /var/www/html/vendor/filament/filament/src/PluginServiceProvider.php(64): RyanChandler\\FilamentLog\\FilamentLogServiceProvider->getPages()
  bandwidth  | #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1267): Filament\\PluginServiceProvider->Filament\\{closure}()
  bandwidth  | #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1214): Illuminate\\Container\\Container->fireCallbackArray()
  bandwidth  | #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): Illuminate\\Container\\Container->fireResolvingCallbacks()
  bandwidth  | #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(860): Illuminate\\Container\\Container->resolve()
  bandwidth  | #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\\Foundation\\Application->resolve()
  bandwidth  | #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(845): Illuminate\\Container\\Container->make()
  bandwidth  | #7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1419): Illuminate\\Foundation\\Application->make()
  bandwidth  | #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(222): Illuminate\\Container\\Container->offsetGet()
  bandwidth  | #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(193): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance()
  bandwidth  | #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(332): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()
  bandwidth  | #11 /var/www/html/vendor/filament/filament/src/FilamentServiceProvider.php(278): Illuminate\\Support\\Facades\\Facade::__callStatic()
  bandwidth  | #12 /var/www/html/vendor/filament/filament/src/FilamentServiceProvider.php(103): Filament\\FilamentServiceProvider->bootTableActionConfiguration()
  bandwidth  | #13 /var/www/html/vendor/spatie/laravel-package-tools/src/PackageServiceProvider.php(151): Filament\\FilamentServiceProvider->packageBooted()
  bandwidth  | #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\\LaravelPackageTools\\PackageServiceProvider->boot()
  bandwidth  | #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
  bandwidth  | #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
  bandwidth  | #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
  bandwidth  | #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
  bandwidth  | #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(933): Illuminate\\Container\\Container->call()
  bandwidth  | #20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(914): Illuminate\\Foundation\\Application->bootProvider()
  bandwidth  | #21 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
  bandwidth  | #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(915): array_walk()
  bandwidth  | #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
  bandwidth  | #24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(242): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
  bandwidth  | #25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(383): Illuminate\\Foundation\\Application->bootstrapWith()
  bandwidth  | #26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(153): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
  bandwidth  | #27 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
  bandwidth  | #28 {main}
  bandwidth  | "}
  bandwidth  |
  bandwidth  | In FilamentLogServiceProvider.php line 14:
  bandwidth  |
  bandwidth  |   RyanChandler\FilamentLog\FilamentLogServiceProvider::getPages(): Return val
  bandwidth  |   ue must be of type array, null returned
  bandwidth  |
  bandwidth  |
  bandwidth  | s6-rc: warning: unable to start service laravel-automations: command exited 1
  bandwidth  | /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
  bandwidth  | prog: fatal: stopping the container.
  bandwidth exited with code 1
  bandwidth  | usermod: no changes
```

**Additional context**
This has been running fine for me for a while.  I even moved it to a new host this week and it picked right up.

**Comment by duckunix** [comment]
Docker compose file snippet:
````
  bandwidth:
    container_name: bandwidth
    hostname: bandwidth.home.tld
    image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
    depends_on:
      - traefik
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - MAIL_HOST=xxxxxxxxxxxxxx
      - MAIL_PORT=587
      - MAIL_USERNAME=xxxxxxxxxxxxxxxxxx
      - MAIL_PASSWORD=xxxxxxxxxxxxxxxx
      - MAIL_FROM_ADDRESS="xxxxxxxxxxxxxxxxx"
      - MAIL_FROM="home Speedtest"
      - APP_NAME="home Speedtest"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mini/config/bandwidth:/config
      - /mini/config/bandwidth/cache:/var/www/html/bootstrap/cache
      - /mini/config/bandwidth/certs:/etc/ssl/web
    restart: unless-stopped
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.headers.customResponseHeaders=X-Robots-Tag: noindex, nofollow"
      - "traefik.port=443"
      - "traefik.protocol=https"
      - "traefik.frontend.rule=Host:bandwidth.home.tld"
      - "traefik.docker.network=proxy"
```
