### ISSUE TITLE
500 when specifing intervals in cron

### ISSUE THREAD

**Issue by JanzenJohn** [alexjustesen/speedtest-tracker#1726]
**Describe the bug**
When using intervals in the cron notation like `*/10 * * * *` there is just a 500 server error

**To Reproduce**
1. set SPEEDTEST_SCHEDULE to `*/10 * * * *`
2. See error

**Expected behavior**
The app should do speedtests every ten minutes

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - 5.10.0-32-amd64 #1 SMP Debian 5.10.223-1 (2024-08-10) x86_64 GNU/Linux
-  Architecture: [e.g. arm64, amd64]
- amd64
 - doesn't matter
 - Version [e.g. v1
 - App: 0.21.2

**Logs**
this logs nothing on the server / client
i can collect logs if you tell me how

**Additional context**
I've seen this issue be mentioned in other issues, but none actually solved it

**Comment by svenvg93** [comment]
I'm not seeing any problems when I change my schedule to `*/10 * * * *` and restart the container
`- SPEEDTEST_SCHEDULE=*/10 * * * *`

Can you share your docker compose. Maybe it will tell us more what the problem might be.

For debugging set the env `APP_DEBUG=true`. Then the error will give more information.

**Comment by JanzenJohn** [comment]
the compose is this

```
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8080:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - SPEEDTEST_SCHEDULE=*/10 * * * *
            - APP_KEY=[REDACTED]
            - APP_URL=http://localhost
            - DB_CONNECTION=sqlite
        volumes:
            - ./data:/config
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
```

this has apparently fixed itself? I restarted the docker container with the option again and it didn't complain like last time, i strictly copied the string out of the docker compose while creating this issue
