### ISSUE TITLE
RROR: unable to bind listening socket for address '127.0.0.1:9000':

### ISSUE THREAD

**Issue by KhaledMostafaME** [alexjustesen/speedtest-tracker#1787]
**Describe the bug**
Unable to run Speedtest-Tracker 

ERROR: FPM initialization failed
ERROR: unable to bind listening socket for address '127.0.0.1:9000': Address in use (98)

**To Reproduce**

```
`version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks TCP
      - 8388:8388/udp # Shadowsocks UDP
      - 8080:80   # Speedtest
      - 8443:443  # Speedtest
      - 8995:9000
      - 8090:8090/tcp # qBittorrent port
      - 8191:8191/tcp # FlareSolverr
      - 9696:9696/tcp # Prowlarr
      - 6765:6767/tcp # Bazarr VPN
      - 9091:9091/tcp # Bazarr VPN
      - 8112:8112/tcp # Deluge web UI
      - 58846:58846/tcp # Deluge daemon
      - 58946:58946/tcp # Torrent port
      - 58946:58946/udp # Torrent port
      - 3000:3000 # Selenium Grid WebDriver port
      - 51820:51820/udp # WireGuard port if needed
    environment:
      - PUID=[Removed]# Your UID
      - PGID=[Removed]# Your GID
      - TZ=Asia/Dubai # Your timezone
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=[Removed] # Make sure this is correct
      - SERVER_COUNTRIES=United Arab Emirates
      #- MTU=1300  # Set the MTU value
      #- WIREGUARD_MTU=1300  
      - VPN_PORT_FORWARDING=on # Enable port forwarding
      - UPDATER_PERIOD=8h
      - HTTPPROXY=on # Enable HTTP Proxy
      - SHADOWSOCKS=on # Enable Shadowsocks Proxy
      - FIREWALL_OUTBOUND_SUBNETS=172.20.0.0/16,192.168.1.0/24,192.168.70.0/24
    volumes:
      - /volume1/docker/gluetun:/gluetun
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=1032  # Your UID
      - PGID=65536  # Your GID
      - APP_KEY=[Removed]
      - DB_CONNECTION=sqlite
      - APP_TIMEZONE=Asia/Dubai # Your timezone
    volumes:
      - /volume1/docker/speedtest-tracker:/config
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped`

```

**Environment (please complete the following information):**
 - OS: Synology DSM
-  Architecture: amd64
 - Browser Chrome
