### ISSUE TITLE
Test status "Started" instead of "Failed" when there is no internet connection

### ISSUE THREAD

**Issue by LukeAllinson** [alexjustesen/speedtest-tracker#1821]
**Describe the bug**
I am currently in the midst of an internet outage (posting this via my mobile phone). Speedtest-Tracker is not showing any failures, and instead all tests are showing as "Starting" and with no data attached if I view the results.
What triggers an actual failure?
Apologies if I am missing something obvious here.
It would also be nice if the graph reflected these failed tests too (although I see there is already an open request for that).

**To Reproduce**
I am unsure whether this is limited to my build/installation, although I don't believe I have configured anything out of the ordinary.
My docker-compose is included below for information:
```
speedtest-tracker:  
    container_name: speedtest-tracker  
    image: lscr.io/linuxserver/speedtest-tracker:latest  
    restart: unless-stopped  
    environment:  
      - PUID=1512  
      - PGID=1512  
      - APP_KEY=base64:XXXXXXXXXXXXXXXX  
      - DB_CONNECTION=sqlite  
      - SPEEDTEST_SCHEDULE=*/15 * * * *  
      - SPEEDTEST_SERVERS=23389,62486,54746,40377  
      - PRUNE_RESULTS_OLDER_THAN=7  
      - DISPLAY_TIMEZONE=${TIMEZONE}  
    volumes:  
      - ${DOCKER_BASE_FOLDER}/speedtest-tracker/config:/config  
      - ${DOCKER_BASE_FOLDER}/speedtest-tracker/keys:/config/keys
```

**Expected behavior**
A failed test (due to loss of internet connectivity) should show as failed in the test results.

**Environment (please complete the following information):**
 - OS: linuxserver.io container, running on Ubuntu 24.04.01, docker version 27.3.1
-  Architecture: amd64
 - Browser: The issue is browser independent (I have tried Edge and Firefox)
 - Version: 0.22.0 (linuxserver.io container)

**Screenshots**
![image](https://github.com/user-attachments/assets/ee840e61-0a64-461b-b5cf-c9a11f304c86)

**Logs**
I use Dozzle for docker log viewing; nothing shown:

![image](https://github.com/user-attachments/assets/c83dde89-faad-41f8-9219-2b973b6637df)

**Additional context**
If I "docker exec" into the container and run the speedtest program interactively, it clearly says that it can't resolve the hostname.

![image](https://github.com/user-attachments/assets/b00a9f87-e04a-4eac-b65d-931f729fa37f)
