### ISSUE TITLE
Wrong date in web ui

### ISSUE THREAD

**Issue by Staubgeborener** [alexjustesen/speedtest-tracker#1887]
**Describe the bug**
The date in the web ui is one day before the real date. For example: Right now it is December 5th in my time zone, the web UI shows December 6th. In the docker container, the correct date of December 05 is displayed with `date`. Precisely because of the latter, I don't really understand why the date is incorrect. Is there an env variable to pass date/time correctly?

**To Reproduce**
Deploy the docker compose file below and check web ui.

**Expected behavior**

**Environment (please complete the following information):**
HOST:
 - OS: Debian
-  Architecture: amd64
 - Browser: Tested with ungoogled-chromium, firefox and edge
 - Version 0.24.3

I am running speedtest-tracker inside docker with this docker compose:
```
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8081:80
            - 9543:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=base64:XXXXX
            - APP_URL=http://localhost
            - DISPLAY_TIMEZONE=Australia/Hobart
            - SPEEDTEST_SCHEDULE=0 * * * *
            - PRUNE_RESULTS_OLDER_THAN=7
            - DB_CONNECTION=sqlite
            - PUBLIC_DASHBOARD=true
        volumes:
            - ./config:/config
            - ./custom-ssl-keys:/config/keys
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
```

**Screenshots**
![speedtracker-wrong-date](https://github.com/user-attachments/assets/87d1c3cd-743e-496f-a328-71ba51fdc8c0)

**Logs**

> user@lab:~/home-ops/speedtest-tracker$ docker logs speedtest-tracker
> [migrations] started
> [migrations] 01-nginx-site-confs-default: skipped
> [migrations] done
> ───────────────────────────────────────
> 
>       ██╗     ███████╗██╗ ██████╗
>       ██║     ██╔════╝██║██╔═══██╗
>       ██║     ███████╗██║██║   ██║
>       ██║     ╚════██║██║██║   ██║
>       ███████╗███████║██║╚██████╔╝
>       ╚══════╝╚══════╝╚═╝ ╚═════╝
> 
>    Brought to you by linuxserver.io
> ───────────────────────────────────────
> 
> To support the app dev(s) visit:
> speedtest-tracker: https://github.com/sponsors/alexjustesen
> 
> To support LSIO projects visit:
> https://www.linuxserver.io/donate/
> 
> ───────────────────────────────────────
> GID/UID
> ───────────────────────────────────────
> 
> User UID:    1000
> User GID:    1000
> ───────────────────────────────────────
> Linuxserver.io version: v0.24.3-ls61
> Build-date: 2024-11-27T16:12:47+00:00
> ───────────────────────────────────────
> 
> using keys found in /config/keys
> [custom-init] No custom files found, skipping...
> [ls.io-init] done.

**Additional context**
