### ISSUE TITLE
Can't reverse-proxy through Caddy

### ISSUE THREAD

**Issue by mircsicz** [alexjustesen/speedtest-tracker#1932]
First of all: Let me thank you for your awesome project which I'm following along progressing since a few month  and use it on three site's <3

**Describe the bug**
I just can't get it to let me login if called from behind a Caddy reverse-proxy

Speedtest compose.yml
```
---
services:
  speedtest-tracker:
    container_name: speedtest
    ports:
      - 8082:80
    environment:
      - PORT=80
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=sqlite
      - APP_TIMEZONE=America/zzz
      - DISPLAY_TIMEZONE=America/zzz
      - APP_KEY=base64:XXX-MINE-XXX
      - SPEEDTEST_SCHEDULE='*/15 0-23 * * *'
      - SPEEDTEST_SERVERS=
      - PRUNE_RESULTS_OLDER_THAN=95
      - PUBLIC_DASHBOARD=true
      - APP_URL=https://subdom.mydom.net/speedtest/
      - ASSET_URL=https://subdom.mydom.net/speedtest/
    volumes:
      - /srv/docker/speedtest/config:/config
      # - /path/to-custom-ssl-keys:/config/keys
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
```
Caddy compose.yml
```
---
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - reverseproxy_net
    volumes:
      - /srv/docker/reverseproxy/config:/etc/caddy
      - /srv/docker/reverseproxy/site:/srv
      - /srv/docker/reverseproxy/data:/data
  tunnel:
    container_name: caddy-cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=XXX-MyToken-XXX

networks:
  reverseproxy_net:
    name: reverseproxy_net
    driver: bridge
```
Caddyfile
```
(private-only) {
        @private not client_ip 172.21.0.0/24 10.10.1x.0/24 10.10.1y.0/24 10.10.1z.0/24
        respond @private "Not from within so: Access Denied"
        }

subdom.mydom.net {
#http://mx-office.jumilove.net {
        #basic_auth {
        #       # docker exec -it CID sh; caddy hash-password
        #       admin mypasswdhash
        #}
        #respond "Welcome, {http.auth.user.id}" 200
        redir /octoprint /octoprint/
        handle_path /octoprint/* {
                handle_path /webcam/* {
                        import private-only
                        reverse_proxy 10.10.1xx.20:8080
                }
                reverse_proxy 10.10.1xx.20:8081 {
                        header_up X-Forwarded-Proto {scheme}
                        header_up X-Script-Name /octoprint
                }
        }
        redir /speedtest /speedtest/
        handle_path /speedtest/* {
                rewrite /admin* /speedtest/admin*
                reverse_proxy 10.10.1xx.20:8082 {
                        header_up X-Script-Name /speedtest
                }
        }
}

```

**To Reproduce**
1. Setup adopting my configs
2. try to login

**Expected behavior**
Successful login and a loaded backend and also graph on the public dashboard

**Environment (please complete the following information):**
 - OS: Raspbian / Docker -> 
-  Architecture: arm64
 - Browser Chrome 131 on MacOS 15.1.1
 - Version: lscr.io/linuxserver/speedtest-tracker -> App: 1.0.1

**Screenshots**
Dashboard: https://subdom.mydom.net/speedtest
![Bildschirmfoto 2024-12-16 um 8 04 49 PM](https://github.com/user-attachments/assets/781ca7dc-41c9-4ea7-983b-c4b16b0c7ddc)
Login Button will load https://subdom.mydom.net/admin instead of https://subdom.mydom.net/speedtest/admin/login

As I've set header_up:
```
                reverse_proxy 10.10.1xx.20:8082 {
                        header_up X-Script-Name /speedtest
``` 
I'ld expect it to rewrite the URL accordingly ;-)                       

**Logs**
let me know what to pull from the container...

P.S.: Seems the missing graph is TLDR or RTFM issue from upgrading to 1.0 ;-)
