### ISSUE TITLE
Keep all data from legacy API in new API v1

### ISSUE THREAD

**Issue by Dillton** [alexjustesen/speedtest-tracker#1989]
**Is your feature request related to a problem? Please describe.**
Hi.
I am using speedtest-tracker to monitor uplink status at my home and I have rest sensors configured in 
HomeAssistant based on legacy API like this:
```
- platform: rest
  name: SpeedTest Download
  unique_id: speedtest_download
  resource: http://10.0.0.51:20083/api/speedtest/latest
  method: GET
  value_template: "{{ value_json['data']['download'] }}"
  json_attributes_path: "$.data"
  json_attributes:
    - "server_name"
    - "server_id"
    - "url"
  unit_of_measurement: Mb/s
  state_class: measurement
  scan_interval: 300
```

I always like new things so I went directly to changing the sensors for new API.
What I am missing basically are the responded data I am using as sensor attributes as it's faster for me to check these on HA side instead of going to speedtest ui:
```
  json_attributes:
    - "server_name"
    - "server_id"
    - "url"
```

**Describe the solution you'd like**
Would be nice to keep these values also in new API.
