### ISSUE TITLE
"chmod: changing permissions of '/XXX': Bad address" error message

### ISSUE THREAD

**Issue by jlobster** [alexjustesen/speedtest-tracker#2004]
This was also posted to https://github.com/linuxserver/docker-speedtest-tracker/issues/39 with no response.

**Describe the bug**
I am experiencing the same issue as the docker-swag issue https://github.com/linuxserver/docker-swag/issues/514. I am also on QNAP. Tried running as root and as proper UID/GID. See system info below.

Wondering which version I can pin it to to make it work, since QNAP does not appear to be fixing this. :(

Or if there's another workaround.

**To Reproduce**
1. Use compose file below (I use dockge)
2. Start stack
Note: I have also followed the QNAP instructions (including mariadb) in the documentations

**Expected behavior**
I expect the stack/app to start up and be accessible

**Environment (please complete the following information):**
uname -a:
`Linux AltQNAP453B 5.10.60-qnap #1 SMP Thu Nov 14 01:14:29 CST 2024 x86_64 GNU/Linux`

docker info:
```
Client:
 Version:    27.1.2-qnap4
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.1-qnap2
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 11
  Running: 9
  Paused: 0
  Stopped: 2
 Images: 32
 Server Version: 27.1.2-qnap4
```

**Screenshots**
N/A

**Logs**
```
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
speedtest-tracker: https://github.com/sponsors/alexjustesen

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    100
───────────────────────────────────────
Linuxserver.io version: v1.1.0-ls72
Build-date: 2025-01-14T02:10:22+00:00
───────────────────────────────────────
    
using keys found in /config/keys
chmod: changing permissions of '/etc/logrotate.d/acpid': Bad address
chmod: changing permissions of '/etc/logrotate.d/nginx': Bad address
chmod: changing permissions of '/etc/logrotate.d/php-fpm': Bad address
chmod: changing permissions of '/etc/logrotate.d/php-fpm83': Bad address
chmod: changing permissions of '/config/nginx/site-confs': Bad address
chmod: changing permissions of '/config/nginx/site-confs/default.conf.sample': Bad address
chmod: changing permissions of '/config/nginx/site-confs/default.conf': Bad address
chmod: changing permissions of '/config/nginx/nginx.conf.sample': Bad address
chmod: changing permissions of '/config/nginx/ssl.conf.sample': Bad address
chmod: changing permissions of '/config/nginx/nginx.conf': Bad address
chmod: changing permissions of '/config/nginx/ssl.conf': Bad address
chmod: changing permissions of '/config/nginx/dhparams.pem': Bad address
chmod: changing permissions of '/config/nginx/resolver.conf': Bad address
chmod: changing permissions of '/config/nginx/worker_processes.conf': Bad address
s6-rc: warning: unable to start service init-permissions: command exited 1
```

**Additional context**
Compose file:
```
version: "3.8"
services:
  speedtest-tracker:
    ## Speedtest Tracker: Track speedtests
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    networks:
      - web
    ports:
      - 8980:80
    environment:
      - PUID=1000
      - PGID=100
      - TZ=${TZ}
      - APP_KEY=base64:[REDACTED]
      - APP_URL=http://192.168.1.16 # (also tried :8980)
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE=0 */6 * * *
      - SPEEDTEST_SERVERS=68132,2409,16089
      - DISPLAY_TIMEZONE=${TZ}
    volumes:
      - ${APPDATA}/speedtest-tracker:/config
networks:
  web:
    name: web
    driver: bridge
```
