### ISSUE TITLE
[Bug] Changing PRUNE_RESULTS_OLDER_THAN value doesn't have any effect

### ISSUE THREAD

**Issue by armond-avanes** [alexjustesen/speedtest-tracker#2006]
**Describe the bug**
When I decrease the value of PRUNE_RESULTS_OLDER_THAN environment variable from 180 to 90 (days), it doesn't prune my result history. I've been waiting for two days for this process to happen, because I thought it might have been scheduled for a specific time of the day to be executed.

**To Reproduce**
1. Stop the running docker container
2. Decrease PRUNE_RESULTS_OLDER_THAN to a lower value
3. Start the container

**Expected behavior**
To prune my result history according to the current value of PRUNE_RESULTS_OLDER_THAN.

**Environment (please complete the following information):**
 - OS: Raspberry OS
-  Architecture: arm64
 - Browser: Chrome
 - Version: 1.2.0

**Additional context**
I've searched the `settings` table in the database and I couldn't find any `prune_results_older_than` record there. So looks like there is only one source of truth for this setting and that's the environment variable.

**Comment by svenvg93** [comment]
Did it work when you used 180?

**Comment by armond-avanes** [comment]
Good point! I checked my results and my oldest one goes back to June 8 which is more than 7 months old. Does this mean the feature is not working at all regardless of the settings? It's a long time I've been maintaining the exact same instance with the same database, etc and only been auto-updated with WatchTower. Could it be because of an older version corrupted the settings?

**Comment by svenvg93** [comment]
When I run the command manual it all works as intended. Can you share your docker compose.

**Comment by armond-avanes** [comment]
I have automated my docker apps [un]installations using Ansible, so there is no docker compose file and I'm running the database in a separate docker container. Here is what I have for docker container installation for SpeedTest-Tracker only:

(the variables are replaced by Ansible by their corresponding values)

```
- name: Install and run docker container
  docker_container:
    name: "{{ docker_speedtest_tracker_container_name }}"
    image: "{{ docker_speedtest_tracker_image_name }}"
    restart_policy: unless-stopped
    published_ports:
      - "{{ docker_speedtest_tracker_exposed_http_port }}:{{ docker_speedtest_tracker_internal_http_port }}"
      - "{{ docker_speedtest_tracker_exposed_https_port }}:{{ docker_speedtest_tracker_internal_https_port }}"
    volumes:
      - "{{ docker_speedtest_tracker_directory }}/config:/config"
      - "{{ ssl_certificates_directory }}/host.crt:/etc/ssl/web/ssl.crt:ro"
      - "{{ ssl_certificates_directory }}/host-pk.pem:/etc/ssl/web/ssl.key:ro"
    env_file: "{{ docker_speedtest_tracker_directory }}/docker-app.env"
    state: started
    container_default_behavior: compatibility
    detach: yes
```

... and the `docker-app.env` template file:

```
PUID=1000
PGID=1000
TZ={{ rpi_timezone }}

APP_NAME=HomeLab - Speedtest Tracker
APP_URL=https://{{ ansible_host }}:{{ docker_speedtest_tracker_exposed_https_port }}
APP_KEY={{ docker_speedtest_tracker_secret_key }}
APP_DEBUG=false
APP_TIMEZONE={{ rpi_timezone }}
APP_LOCALE=en
APP_FALLBACK_LOCALE=en

PUBLIC_DASHBOARD=true
SPEEDTEST_SCHEDULE=8-59/15 * * * *
SPEEDTEST_SERVERS=57682,60433,61417,52311,33893,52470,14236,12191,9916,34840,7190,50081,21001,19230,21541,35056,5861
DISPLAY_TIMEZONE={{ rpi_timezone }}
PRUNE_RESULTS_OLDER_THAN=90

DB_CONNECTION=mysql
DB_HOST={{ mariadb_host_ip }}
DB_PORT={{ docker_mariadb_exposed_port }}
DB_DATABASE={{ docker_speedtest_tracker_database_name }}
DB_USERNAME={{ docker_speedtest_tracker_database_user }}
DB_PASSWORD={{ docker_speedtest_tracker_database_password }}
```

If you need to know the actual value of a particular variable or a setting/record in the database, please let me know and I will post them here.

By the way, what's the cron schedule for pruning the data? Is it calculated from the container up time? I don't see any cron schedule variable in the env variables.
