### ISSUE TITLE
Unsupported cipher or incorrect key length

### ISSUE THREAD

**Issue by bluestorm0** [alexjustesen/speedtest-tracker#2084]
At the first starting I got this issue with **500 SERVER ERROR**.
So I set **APP_DEBUG=true**.

Then I got this one
**_Unsupported cipher or incorrect key length. Supported ciphers are: aes-128-cbc, aes-256-cbc, aes-128-gcm, aes-256-gcm._**

Environment (please complete the following information):

- OS: GNU/Linux synology_r1000_923+
- Architecture: AMD Ryzen R1600

I use into Docker. Please find docker-compose.yml file here (I just change some charaters into APP_KEY)
```
version: '3.5'

services:
  speedtest-tracker:
    container_name: speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:latest
    ports:
      - 8480:80
      - 8443:443
    volumes:
      - ./config:/config
      - ./config/ssl-keys:/config/keys
    environment:
      -APP_KEY=base64:qV7nn0ahJww2s1X9Kk/CbiFaWtKqKPRMri2d0rAukiA=X0Iqupoy+NpsVwXR6rbwlzcpFaKVQZSiMB1234567890
      - DB_CONNECTION=sqlite
      - DISPLAY_TIMEZONE=Europe/Paris
      - APP_TIMEZONE=Europe/Paris
      - TIMEZONE=Europe/Paris
      - APP_DEBUG=true
    restart: unless-stopped

```
