### ISSUE TITLE
Very slow, no speed tests & no servers

### ISSUE THREAD

**Issue by andrewbpowers** [alexjustesen/speedtest-tracker#2096]
Hello!

The following problem has occurred after I updated last month:

Speedtest Tracker no longer performs tests, the web interface is quite slow. When I start a speedtest manually, it takes quite a long time until the window with the server selection is displayed. If I then try to select a server, only "Loading" is displayed, but even after a few seconds no more servers are shown.

This may be the reason why no more speed tests are performed and all tests started via cron (PEEDTEST_SCHEDULE=0 */3 * * * *) end with a “Failed”. 
Container log: `production.ERROR: Failed to fetch external IP address. ["cURL error 28: Resolving timed out after 5001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://icanhazip.com/"] `

In the past I have always update via Portainer (recreate), which has never led to a problem. But even a complete reinstallation did not solve the problem. I always made updates when I was notified that there was a new version.

So far about 3000 results have been saved. I don't know if this information could be useful.

Yes, Pi-hole is in use, but has not been a problem in the past and “icanhazip.com” is on the whitelist. 

As part of my research, I also ran “sudo docker exec -it speedtest-tracker curl https://icanhazip.com”, which, however, is strangely qutted with “curl: (6) Could not resolve host: icanhazip.com”. Unfortunately, I cannot say whether this error would have been displayed before the update.

Since I have tried to find informations about the problem described and to identify and fix the error(s) myself, I am only writing now.

- Architecture: arm64 (Raspberry 4, 8GB)
- Browser: Chrome / Safari
- Version: Linuxserver.io version: v1.2.5-ls82, Build-date: 2025-03-01T21:25:51+00:00

Docker Compose file:

```
---
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - APP_KEY=secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
      - APP_URL=
      - SPEEDTEST_SCHEDULE=0 */3 * * *
      - SPEEDTEST_SERVERS=14236,57682,16620,65064,64431,16615,52053,2426,10878,29471,57997,64074
      #- SPEEDTEST_INTERFACE=eth0
      - DB_CONNECTION=sqlite
      - DB_HOST= #optional
      - DB_PORT= #optional
      - DB_DATABASE= #optional
      - DB_USERNAME= #optional
      - DB_PASSWORD= #optional
      - DISPLAY_TIMEZONE=America/Los_Angeles #optional
      - PRUNE_RESULTS_OLDER_THAN=365 #optional
    volumes:
      - /home/pi/speedtesttracker/data:/config
    ports:
      - 8073:80
    restart: unless-stopped
```

By the way, I only added the variable “`SPEEDTEST_SERVERS=14236,57682,16620,65064,64431,16615,52053,2426,10878,29471,57997,64074`” at the last and new installation, after the Speedtest Tracker stopped working.

Thank you very much for your attention and any help! :-)

Best regards

**Comment by alexjustesen** [comment]
Couple of things we can try first...

- Make sure to set the `APP_URL`, also you can remove the extra `DB_` environment variables since you're using sqlite.
- Try removing all the servers listed and see if the CLI will select a server for you.

**Comment by andrewbpowers** [comment]
Dear Alex,

thank you very, very much for your prompt reply! :-)

I have changed the Docker Compose file as follows:

```
---
services:
  speedtest-tracker:
    image: [lscr.io/linuxserver/speedtest-tracker:latest](http://lscr.io/linuxserver/speedtest-tracker:latest)
    container_name: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - APP_KEY=secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
      - APP_URL=http://192.168.9.138:8033
      - SPEEDTEST_SCHEDULE=0 */3 * * *
      #- SPEEDTEST_SERVERS=14236,57682,16620,65064,64431,16615,52053,2426,10878,29471,57997,64074
      #- SPEEDTEST_INTERFACE=eth0
      - DB_CONNECTION=sqlite
      #- DB_HOST= #optional
      #- DB_PORT= #optional
      #- DB_DATABASE= #optional
      #- DB_USERNAME= #optional
      #- DB_PASSWORD= #optional
      - DISPLAY_TIMEZONE=America/Los_Angeles
      - PRUNE_RESULTS_OLDER_THAN=365
    volumes:
      - /home/pi/speedtesttracker/data:/config
    ports:
      - 8033:80
      - 8433:443
    restart: unless-stopped

```

I only tested the server list after the last reinstallation, before that this option was never active.

Unfortunately, nothing has changed and when I click on “Speedtest” in the webintace, it takes about 10 seconds until the window with the server selection is displayed and then there are still no servers available and after about 15 seconds it says: “unable to retrieve ookla servers check internet connection and check logs”.

I found a post on reddit “Need Help | SpeedTest Tracker - Stopped working on March 5th”, where Speedtest Tracker also just stopped working.

What a pity! :-(
