### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'speedtest_tracke

### ISSUE THREAD

**Issue by samad20** [alexjustesen/speedtest-tracker#2131]
**Describe the bug**
I got an error on logs and 500 code on UI

**Environment**
 - OS:debian
-  Architecture: arm64
 - Browser chrome

**Logs**
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'speedtest_tracke  

**Additional context**
```
services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        container_name: speedtest-tracker
        ports:
            - 101:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=100
            - APP_KEY=**************
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedtest_tracker
            - DB_PASSWORD=***********
        volumes:
            - ./data:/config
            - ./ssl-keys:/config/keys
        depends_on:
            - db
    db:
        image: mysql
        restart: always
        environment:
            - MYSQL_DATABASE=speedtest_tracker
            - MYSQL_USER=speedtest_tracker
            - MYSQL_PASSWORD=***********
            - MYSQL_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_PASSWORD}"]
            interval: 5s
            retries: 5
            timeout: 5s
volumes:
  speedtest-db:
```

Edited by @alexjustesen: I removed your password and wrapped it in a code block to make it easier to read.
