### ISSUE TITLE
[Question]   SQLSTATE[HY000] [2002] Host is unreachable

### ISSUE THREAD

**Issue by skubi23t** [alexjustesen/speedtest-tracker#2240]
### Pre-work

- [x] I have read the [docs](https://docs.speedtest-tracker.dev).
- [x] I have searched open and closed issues.
- [x] I agree to follow this project's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md).

### Description

![Image](https://github.com/user-attachments/assets/5ab5bc1d-becb-4125-9ee7-3e4b164ebca3)

Can someone help me to understand what causes the above error ?

### Expected Behavior

Doesn't launch

### Steps to Reproduce

Logs in docker. 

### Deployment Environment

Docker Compose

### Application Information

```json
nothing
```

### What browser(s) are you seeing the problem on?

All

### Logs

```shell

```

**Comment by skubi23t** [comment]
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8766:80'
            - '8443:443'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=dbname
            - DB_USERNAME=usr
            - DB_PASSWORD=pwd
        volumes:
            - /speedtest_config:/config

        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=dbname
            - MARIADB_USER=usr
            - MARIADB_PASSWORD=pwd
            - MARIADB_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
volumes:
  speedtest-db:

**Comment by alexjustesen** [comment]
Couple of thoughts...

1. Change `DB_CONNECTION=mysql` to `DB_CONNECTION=mariadb`
2. You all need an `APP_KEY`
3. Did you change your DB username/password after starting the container for the first time? If so delete the database volume and start the stack again.

Ref in docs: https://docs.speedtest-tracker.dev/getting-started/installation/using-docker-compose

**Comment by skubi23t** [comment]
Thank you for the prompt response! 
Indeed, I had some mess in there, so I fixed it to become like below:

```
services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        container_name: speedtest-tracker
        ports:
            - 8766:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=base64:+2D3yKgbFABRqSPavdUo/1CmPoFbzCfV1ILGrmW5tsU=
            - DB_CONNECTION=mariadb
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=usr
            - DB_PASSWORD=pwd        volumes:
            - /speedtest_config:/config
        depends_on:
            - db
    db:
        image: mariadb:11
        restart: always
        environment:
            - MYSQL_DATABASE=speedtest_tracker
            - MYSQL_USER=usr
            - MYSQL_PASSWORD=pwd
            - MYSQL_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            interval: 5s
            retries: 3
            timeout: 5s
volumes:
  speedtest-db:
```

Loads fine now the app, but the db status is "unhealthy" with logs like below:


ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO) ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO) healthcheck innodb_initialized failed


Do you know how I can fix that?
