### ISSUE TITLE
[Question] TimeZoneConfigNotWork

### ISSUE THREAD

**Issue by xuyue1998** [alexjustesen/speedtest-tracker#2265]
### Pre-work

- [x] I have read the [docs](https://docs.speedtest-tracker.dev).
- [x] I have searched open and closed issues.
- [x] I agree to follow this project's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md).

### Description

![Image](https://github.com/user-attachments/assets/08d76b73-bc4d-438f-89e3-97e787128c04)
I upgraded from version 0.27 to 1.6.1 and maintained the same configuration, but the time zone configuration did not take effect correctly.

![Image](https://github.com/user-attachments/assets/e7273025-aa43-407d-9b9c-2a2d6e33a1ef)

### Expected Behavior

Switch to the corresponding time zone

### Steps to Reproduce

Set time zone to Asia/Shanghai

### Deployment Environment

Docker Run

### Application Information

```json
Synology Docker
```

### What browser(s) are you seeing the problem on?

all

### Logs

```shell

```

**Comment by svenvg93** [comment]
Im not seeing the same behavoir on my instance. Can you share your docker compose/run that you use.

**Comment by p1r473** [comment]
Im seeing the exact same thing

**Describe the bug**
Timestamps in the UI are always displayed in UTC, and SPEEDTEST_SCHEDULE=*/1 * * * * is ignored. The “Next speedtest at…” value is always set to the next half-hour or hour (e.g., 2:30am), even though I’ve configured it to run every minute.

Both timezone and scheduler config are being ignored, even though the environment variables are properly set.

**To Reproduce**
Steps to reproduce the behavior:
Delete any previous config and container:
`rm -rf /volume1/docker/speedtest-tracker/`
create docker-compose.yaml
```
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    container_name: speedtest-tracker
    ports:
      - 8444:443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - APP_TIMEZONE=America/Toronto
      - DISPLAY_TIMEZONE=America/Toronto
      - APP_KEY=REDACTED
      - DB_CONNECTION=sqlite
      - ENABLE_SCHEDULER=true
      - SPEEDTEST_SCHEDULE=*/1 * * * *
      - PRUNE_RESULTS_OLDER_THAN=30 days
      - FORCE_HTTPS=true
    volumes:
      - ./config:/config
```
start the container
`docker compose up -d`

Visit the dashboard and observe:
“Next speedtest at…” is still set in UTC time
Timestamps on results are in UTC
`docker exec -it speedtest-tracker date`
Mon Jul  7 02:30:09 UTC 2025

Speedtests are only running once per hour or half-hour, not every minute
**Expected behavior**
The dashboard and results should reflect America/Toronto time
Speedtests should run every minute per the configured schedule

**Screenshots**
<img width="1476" height="224" alt="Image" src="https://github.com/user-attachments/assets/85a08c6a-d0cc-49f3-b3ad-7cdab231b58b" />

**Context**
OS: Docker on Synology
Speedtest-Tracker Version: lscr.io/linuxserver/speedtest-tracker:latest
