### ISSUE TITLE
Docker with Traefik : HTTPS Mixed Content

### ISSUE THREAD

**Issue by guigui42** [alexjustesen/speedtest-tracker#280]
I am using the following Docker compose template : 

```
version: '3.4'
services:
  speedtesttracker:
    image: ghcr.io/alexjustesen/speedtest-tracker:latest
    container_name: speedtesttracker
    networks:
      backend:
    ports:
      - 8766:80
    volumes:
      - speedtest2:/config
    environment:
      - PUID=272
      - PGID=276
    labels:
      - traefik.enable=true
      - traefik.http.routers.speedtest2.rule=Host(`speedtest2.XXXXXXXX.com`)
      - traefik.http.services.speedtest2.loadbalancer.server.port=80
      - traefik.docker.network=web
      - traefik.http.routers.speedtest2.tls=true
      - traefik.http.routers.speedtest2.tls.certresolver=myresolver

volumes:
  speedtest2:
    name: speedtest2
  backend:
    external: true
```

when trying to access it using my domain, I get the mixed content errors : 
https://speedtest2.XXXXXXXX.com/admin/login

![image](https://user-images.githubusercontent.com/2376010/210139065-2e411331-20c9-464e-ab0e-a60f88f407c8.png)
![image](https://user-images.githubusercontent.com/2376010/210139155-163d8a12-b703-435f-82df-7efc0d6632e5.png)

And looking at the source code, it is indeed trying to load HTTP content into my HTTPS page : 
![image](https://user-images.githubusercontent.com/2376010/210139245-32819a8d-02c1-40a2-aebf-6553c9715fc2.png)

Trying to access the same page using the HTTP page will work fine :  http://MYIP:8766

Is there a way to pass the Base URL as en Docker Env variable to avoid this ?
