### ISSUE TITLE
Docker didnt start because of a bug(?)

### ISSUE THREAD

**Issue by solisinvictum** [alexjustesen/speedtest-tracker#358]
Hey, 

just found that project and it seems to be a nice piece of software.

I used like here described https://docs.speedtest-tracker.dev/getting-started/installation docker-compose mysql.

My composefile:

```
user@speedtesttracker:~$ cat docker-compose.yml 
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8080:80'
            - '8443:443'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
        volumes:
            - '/home/user/speedtest:/config'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest_tracker
            - MARIADB_USER=speedy
            - MARIADB_PASSWORD=password
            - MARIADB_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
volumes:
  speedtest-db:
user@speedtesttracker:~$ 
```
After docker compose up -d, something gets downloaded and started, but in fact the docker didnt start fully up (website isnt accessable).

So i tried only compose up, and get following in a loop:

```
speedtest-tracker  | --------------------------------------------------------------------
speedtest-tracker  |  ____                             ____  _     _        _   _
speedtest-tracker  | / ___|  ___ _ ____   _____ _ __  / ___|(_) __| | ___  | | | |_ __
speedtest-tracker  | \___ \ / _ \  __\ \ / / _ \  __| \___ \| |/ _` |/ _ \ | | | |  _ \
speedtest-tracker  |  ___) |  __/ |   \ V /  __/ |     ___) | | (_| |  __/ | |_| | |_) |
speedtest-tracker  | |____/ \___|_|    \_/ \___|_|    |____/|_|\__,_|\___|  \___/| .__/
speedtest-tracker  |                                                             |_|
speedtest-tracker  | 
speedtest-tracker  | Brought to you by serversideup.net
speedtest-tracker  | --------------------------------------------------------------------
speedtest-tracker  | 
speedtest-tracker  | To support Server Side Up projects visit:
speedtest-tracker  | https://serversideup.net/sponsor
speedtest-tracker  | -------------------------------------
speedtest-tracker  | GID/UID
speedtest-tracker  | -------------------------------------
speedtest-tracker  | 
speedtest-tracker  | User uid:    1000
speedtest-tracker  | User gid:    1000
speedtest-tracker  | -------------------------------------
speedtest-tracker  | 
speedtest-tracker  | 🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...
speedtest-tracker  | 🏃‍♂️ Checking for Laravel automations...
speedtest-tracker  | 🔐 Linking the storage...
speedtest-tracker  | [2023-01-25 17:49:06] production.ERROR: The /var/www/html/bootstrap/cache directory must be present and writable. {"exception":"[object] (Exception(code: 0): The /var/www/html/bootstrap/cache directory must be present and writable. at /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php:178)
speedtest-tracker  | [stacktrace]
speedtest-tracker  | #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(137): Illuminate\\Foundation\\PackageManifest->write()
speedtest-tracker  | #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(107): Illuminate\\Foundation\\PackageManifest->build()
speedtest-tracker  | #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(90): Illuminate\\Foundation\\PackageManifest->getManifest()
speedtest-tracker  | #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(79): Illuminate\\Foundation\\PackageManifest->config()
speedtest-tracker  | #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php(26): Illuminate\\Foundation\\PackageManifest->aliases()
speedtest-tracker  | #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(242): Illuminate\\Foundation\\Bootstrap\\RegisterFacades->bootstrap()
speedtest-tracker  | #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(383): Illuminate\\Foundation\\Application->bootstrapWith()
speedtest-tracker  | #7 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(153): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
speedtest-tracker  | #8 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
speedtest-tracker  | #9 {main}
speedtest-tracker  | "} 
speedtest-tracker  | 
speedtest-tracker  | In PackageManifest.php line 178:
speedtest-tracker  |                                                                              
speedtest-tracker  |   The /var/www/html/bootstrap/cache directory must be present and writable.  
speedtest-tracker  |                                                                              
speedtest-tracker  | 
speedtest-tracker  | s6-rc: warning: unable to start service laravel-automations: command exited 1
speedtest-tracker  | /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
speedtest-tracker  | prog: fatal: stopping the container.
```
Docker and Compose just runs fine. nginx reverse proxy and pi-hole as quick test just runs fine.

Edit:

OS Clean install of Debian 11.
