### ISSUE TITLE
Web UI login/password

### ISSUE THREAD

**Issue by GentleHoneyLover** [alexjustesen/speedtest-tracker#36]
Hi,

What's the login / password from the Web UI?

<img width="471" alt="Screen Shot 2022-09-29 at 21 23 05" src="https://user-images.githubusercontent.com/38346023/193124031-a93080c9-d9a5-4980-894a-8502a5d6c29e.png">

my docker compose:

```yml
speedtest-new:
    container_name: speedtest-new
    image: ghcr.io/alexjustesen/speedtest-tracker:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${UID}
      - PGID=${GID}
      - PHP_POOL_NAME=speedtest-tracker_php
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/app/database.sqlite
    ports:
      - 8765:80
    volumes:
      - ${VLM_PATH}/speedtest-new:/app
```
