### ISSUE TITLE
Issue with Traefik - Reverse proxy

### ISSUE THREAD

**Issue by IosifZ** [alexjustesen/speedtest-tracker#360]
Hi guys,

Awesome project, much better than the old, but for the life of me I cannot seem to be able to make the Reverse proxy to work. And I say this after I read all the issues related to this (both open and closed).

I can access the container using the local IP:8088/4443
If I try to access it through the reverse proxy I get a 'Internal Server Error' message.

Here is my [compose ](https://gist.github.com/IosifZ/d804138ee6072ed5192a6860e51a7cbe) file, Traefik and Speedtest Tracker relevant bits (plus the old one as an example of how I normally set the reverse proxy for the rest of my containers).

Many thanks to whoever might point me in the right way.

**Comment by alexjustesen** [comment]
@IosifZ did you pass through the domain you're using as `APP_URL` environment variable for the container?

**Comment by IosifZ** [comment]
> @IosifZ did you pass through the domain you're using as `APP_URL` environment variable for the container?

No, I was just reading about that now. can I use this in conjuncture of the Zone variable that I have stored into my .env file (basically that is my domain name) ?

Option 1:
APP_URL=speedtest.${ZONE}`)

Option 2:
APP_URL=speedtest.domain.com

Thanks.

**Comment by alexdelprete** [comment]
You are missing this in speedtest-tracker section:

```
- traefik.http.services.speedtest.loadbalancer.server.scheme=https

```

**Comment by alexdelprete** [comment]
Can you share ST log at startup please? I want to be sure of the internal config at boot time.

Your Traefik config looks good, there's the scheme, there's insecureSkipVerify.

Some users were getting crazy because they used http:// instaed of https:// when accessing through traefik. I know it sounds stupid, but it's a common mistake. :)

Another thing: can you also share traefik log for the error in accessing ST?

**Comment by IosifZ** [comment]
> Can you share ST log at startup please? I want to be sure of the internal config at boot time.
> 
> Your Traefik config looks good, there's the `scheme`, there's `insecureSkipVerify`. You also set `SSL_MODE` in the compose file, wise choice. I prefer setting env vars in the compose file.
> 
> Some users were getting crazy because they used `http://` instead of `https://` when accessing through traefik. I know it sounds stupid, but it's a common mistake. :)
> 
> Another thing: can you also share traefik log for the error in accessing ST?
> 
> Probably you already read it, but [here](https://github.com/alexjustesen/speedtest-tracker/issues/54#issuecomment-1336297975) after a long discussion Daniel found the right config. Looks pretty similar to yours. Unfortunately I don't use tags in compose, I have a dynamic yaml file for all services in Traefik, so can't share my config if you use tags.

I forgot to mention that if I try to access speedtest.domain.com, I reach the Google Oauth and I pass it, then I see the "Internal Server Error" message.

**Comment by alexdelprete** [comment]
It seems Traefik is validating the certificate, ignoring your `insecureSkipVerify` setting. Please check your configuration.

Possible solutions:

![image](https://user-images.githubusercontent.com/7027842/215071098-f986e3c8-2c5c-4998-979a-3e885768707d.png)

**Comment by IosifZ** [comment]
> It seems Traefik is validating the certificate, ignoring your `insecureSkipVerify` setting. Please check your configuration.
> 
> Possible solutions:
> 
> ![image](https://user-images.githubusercontent.com/7027842/215071098-f986e3c8-2c5c-4998-979a-3e885768707d.png)

I do not use Kubernetes, so I am not sure if that possible solution applies to my use case.
Here is a longer piece from Traefik [log](https://gist.github.com/IosifZ/1b93ca61d8bdb1dd94b35aaf6dc2679c)

**Comment by alexdelprete** [comment]
Doesn't matter if you use Kubernetes or Docker, the problem is that the certificate is being verified. That's what I wanted to show you.

Your last log confirms that the self-signed certificate of ST is being verified/challenged:

```
DBG ACME CA=https://acme-v02.api.letsencrypt.org/directory msg=Trying to challenge certificate for domain [speedtest.DOMAIN.com] found in HostSNI rule providerName=basic.acme routerName=speedtest_https@docker rule=Host(`speedtest.DOMAIN.com`)
```

Questions:
- did you try disabling this OAuth temporarily?
- did you try (as test) accessing ST via http/80?
- do you have other backend services (like ST) using self-signed certs, configured with Traefik?

**Comment by alexdelprete** [comment]
Try this in ST section just as a test:

```yaml
    labels:
      - com.ouroboros.enable=true
      - traefik.enable=true
      - 'traefik.http.routers.speedtest_https.rule=Host(`speedtest.${ZONE}`)'
      - traefik.http.routers.speedtest_https.tls=true
      - traefik.http.routers.speedtest_https.tls.certresolver=basic
      - traefik.http.services.speedtest.loadbalancer.server.port=443
      - traefik.http.services.speedtest.loadbalancer.server.scheme=https
```

BTW: wh

**Comment by alexdelprete** [comment]
From ST point of view, there's not much we can do, since it works accessing it directly both on http and https.

Open an issue on traefik repo, it seems that your back-end certificate is being verified despite the `insecureSkipVerify` setting. It's weird because I have it working as many others too, and the config is very similar to yours.

Good luck.

**Comment by IosifZ** [comment]
> From ST point of view, there's not much we can do, since it works accessing it directly both on http and https.
> 
> Open an issue on traefik repo, it seems that your back-end certificate is being verified despite the `insecureSkipVerify` setting. It's weird because I have it working as many others too, and the config is very similar to yours.
> 
> Good luck.

Is there a way to disable the self certificate part on ST?

**Comment by alexdelprete** [comment]
> Is there a way to disable the self certificate part on ST?

use http to bypass https. the https service needs a certificate, and a self-signed one is being generated.

**Comment by IosifZ** [comment]
> > Is there a way to disable the self certificate part on ST?
> 
> use http to bypass https. the https service needs a certificate, and a self-signed one is being generated.
> 
> Maybe @Daniel-Kalus can take a look at your config to see if I've missed something obvious, he spent quite some time making this work.

I altered a little bit my configuration hoping that I can have HTTPS handled by Traefik and connect to the app on port 80 (i have at least another app that works like this).

here is the new [config](https://gist.github.com/IosifZ/964e3036903c64a94b4eaa5167d9c696):

The good part is that it worked, I can see the logon page. The bad part is that it is white :-)

![image](https://user-images.githubusercontent.com/53576878/215093885-ca3f8362-31ef-4166-9cab-f402a522b826.png)

**Comment by greboreda** [comment]
> > > Is there a way to disable the self certificate part on ST?
> > 
> > 
> > use http to bypass https. the https service needs a certificate, and a self-signed one is being generated.
> > Maybe @Daniel-Kalus can take a look at your config to see if I've missed something obvious, he spent quite some time making this work.
> 
> I altered a little bit my configuration hoping that I can have HTTPS handled by Traefik and connect to the app on port 80 (i have at least another app that works like this).
> 
> here is the new [config](https://gist.github.com/IosifZ/964e3036903c64a94b4eaa5167d9c696):
> 
> The good part is that it worked, I can see the logon page. The bad part is that it is white :-)
> 
> ![image](https://user-images.githubusercontent.com/53576878/215093885-ca3f8362-31ef-4166-9cab-f402a522b826.png)
> 
> LE I also switched SSL Mode to off, same behavior, white page with huge icons.

I have the same issue using nginx as reverse proxy.

As I see there are rendered some absolute URIs to load static resources (filament assets and app css)

![imagen](https://user-images.githubusercontent.com/10188536/215167779-7fbe8ff6-7ce6-48b0-a35c-6ad772d2352b.png)

Those assets aren't reached due to CSF policies.

Maybe http scheme is also hardcoded?

Thank you :)

**Comment by alexdelprete** [comment]
I use Traefik, and it works perfectly with ST, both with http/https.

Check your default headers config in your proxy, here's the ones I use after checking compatibility with a lot of backend services, and I found this as a good balance config:

```yaml
    default-headers:
      headers:
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "PATCH"
          - "DELETE"
          - "OPTIONS"
          - "HEAD"
          # - "TRACE"

        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginList:
          - "*"
        accessControlMaxAge: 180
        addVaryHeader: true
        browserXssFilter: true
        # # CSP: don't use base-uri 'self' nor form-action 'self'; or frame-ancestors 'self'; they are disruptive for many services script-src 'self'; style-src 'self'; img-src 'self';
        contentSecurityPolicy: object-src 'self';
        # # This creates problem on some webapps (RainMachine)
        # # contentTypeNosniff: true
        permissionsPolicy: vibrate=(self); geolocation=(self); midi=(self); notifications=(self); push=(self); vibrate=(self); fullscreen=(self); microphone=(); camera=(); magnetometer=(); gyroscope=(); speaker=();
        forceSTSHeader: true
        customFrameOptionsValue: SAMEORIGIN
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: same-origin
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
```
