### ISSUE TITLE
influx db with self-signed certificate

### ISSUE THREAD

**Issue by rameskum** [alexjustesen/speedtest-tracker#424]
**Is your feature request related to a problem? Please describe.**
Currently, I am using influx db with a self-signed certificate, which I tried configuring on the speed test tracker. It isn't working.
I am only guessing this is because of an SSL verification failure, and I cannot find the logs.

**Describe the solution you'd like**
It will be awesome to have a configuration variable that will skip host/ssl verification. 
Having access to logs for communication failures would be great too.

**Additional context**
NA

**Comment by alexjustesen** [comment]
So there shouldn't be any validation of SSL when communicating with influx, I'd double check your URL is correct with either `http` or `https` present along with if you have any specific port.

https://docs.speedtest-tracker.dev/settings/data-platforms/influxdb2

**Comment by rameskum** [comment]
Yes, a flag to disable SSL verification.

My local influx db is deployed over TLS using a self-signed certificate. 
Below is the configuration for the influx DB.

![ss-2023-02-26-16 15 12](https://user-images.githubusercontent.com/10393227/221437786-31e0ad20-d2ac-40c5-9d9d-bcacb3d7009f.png)


Also, where can I find logs in case of any failure while pushing data to the influx db?

**Comment by alexjustesen** [comment]
You can find logs in the mounted directory along with the .env file

**Comment by rameskum** [comment]
I am using the below docker-compose for deployment, and I mounted one directory with no log files.

```yaml   
speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8766:443'
        environment:
            PUID: 1000
            PGID: 1000
            DB_CONNECTION: pgsql
            DB_HOST: ${PG_HOST}
            DB_PORT: ${PG_PORT}
            DB_DATABASE: ${PG_DB}
            DB_USERNAME: ${PG_USER}
            DB_PASSWORD: ${PG_PASS}
            MAIL_HOST: ${MAIL_HOST}
            MAIL_PORT: ${MAIL_PORT}
            MAIL_USERNAME: ${MAIL_USER}
            MAIL_PASSWORD: ${MAIL_PASS}
            MAIL_ENCRYPTION: tls
            MAIL_FROM_ADDRESS: ${MAIL_FROM}
        volumes:
            - '/docker/appdata/speedtest-tracker:/config'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
````


![ss-2023-02-28-11 31 22](https://user-images.githubusercontent.com/10393227/221916746-3fabe36f-9601-4938-ba36-3499ba4451e2.png)
