### ISSUE TITLE
unable to exec /etc/s6-overlay/scripts/startup: Permission denied

### ISSUE THREAD

**Issue by benjamin-feron** [alexjustesen/speedtest-tracker#44]
Hello,

I encounter a problem when I launch the image with an error message :

s6-rc-oneshot-run: fatal: unable to exec /etc/s6-overlay/scripts/startup: Permission denied

I launched it with docker-compose with this simple configuration :

```
services:
  speedtest-tracker:
    build: ./speedtest-tracker
```

The repo is freshly cloned in speedtest-tracker directory.

Architecture : aarch64

Can you help me ?

Thanks

**Comment by alexjustesen** [comment]
Hey @benjamin-feron I'd avoid the `main` branch atm and use a release. I'm aware of a permission issue when creating the SQLite DB during startup if you don't specify an external db.

**Comment by benjamin-feron** [comment]
Hey,

Thank you for your response

I've done a `git checkout v0.1.0-alpha.6` in the repo and the same issue persits.

```
networks:
  databases:
    external: true

services:
  speedtest-tracker:
    build: ./speedtest-tracker
    restart: unless-stopped
    networks:
      - databases
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: speedtest-tracker_test
      DB_USERNAME: speedtest-tracker_test
      DB_PASSWORD: speedtest-tracker_test
```

`s6-rc-oneshot-run: fatal: unable to exec /etc/s6-overlay/scripts/startup: Permission denied`

The database exists with privileges on speedtest-tracker_test user.
