### ISSUE TITLE
authentication: false still forces the login screen

### ISSUE THREAD

**Issue by cdaringe** [alexjustesen/speedtest-tracker#45]
# problem

the config and start script yields the following issues:

- login screen still required upon visiting http://localhost:8080, even with `authentication: false`
- 🐇  Configuring Speedtest Tracker... `/entrypoint: 11: [: sqlite: unexpected operator`
- ...and i cannot put the db in `/app`, because php says `app` is not a permitted dir, thus i put the db in /var/www/html/db`, as shown below

```yaml
---
authentication: false
influxdb:
  enabled: false
  version: 2 # Only InfluxDB2 is supported right now
  url: "http://your-influxdb-instance" # Full url to your InfluxDB instance, sometimes this includes a port number
  org: "" # Organization name, usually created when you installed InfluxDB
  bucket: "speedtest-tracker" # A name location to store the speedtest data in
  token: "" # This is your API token
notifications:
  channels:
    discord:
      webhook_url: null # Set as null to disable
    slack:
      webhook_url: null # Set as null to disable
speedtest:
  enabled: true
  schedule: "*/30 * * * *" # every hour
  ookla_server_id: null # specify a server ID to use a specific server
tz: "UTC"
```

```sh
// start.sh
set -exo pipefail
docker run -it --rm --name speedtest-tracker \
  -p 8080:80 \
  -e "PHP_POOL_NAME=speedtest-tracker_php" \
  -e "DB_CONNECTION=sqlite" \
  -e "DB_DATABASE=/var/www/html/db/database.sqlite" \
  -v $PWD/app:/app \
  -v $PWD/db:/var/www/html/db/ \
  ghcr.io/alexjustesen/speedtest-tracker:latest
```
