### ISSUE TITLE
touch: cannot touch '/config/database.sqlite': Permission denied

### ISSUE THREAD

**Issue by yonas** [alexjustesen/speedtest-tracker#473]
**docker-compose.yaml**

```
version: '3.3'

services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8080:80'
            - '8443:443'
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - './config:/config'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped

```

**Console**
```
$ doas docker-compose up
speedtest-tracker    | usermod: no changes
speedtest-tracker    | 
speedtest-tracker    | --------------------------------------------------------------------
speedtest-tracker    | 
speedtest-tracker    |  _______                       __ __                __
speedtest-tracker    | |     __|.-----.-----.-----.--|  |  |_.-----.-----.|  |_
speedtest-tracker    | |__     ||  _  |  -__|  -__|  _  |   _|  -__|__ --||   _|
speedtest-tracker    | |_______||   __|_____|_____|_____|____|_____|_____||____|
speedtest-tracker    |          |__|
speedtest-tracker    |  _______                   __
speedtest-tracker    | |_     _|.----.---.-.----.|  |--.-----.----.
speedtest-tracker    |   |   |  |   _|  _  |  __||    <|  -__|   _|
speedtest-tracker    |   |___|  |__| |___._|____||__|__|_____|__|
speedtest-tracker    | 
speedtest-tracker    | 
speedtest-tracker    | --------------------------------------------------------------------
speedtest-tracker    | 
speedtest-tracker    | To support Speedtest Tracker visit:
speedtest-tracker    | https://github.com/alexjustesen/speedtest-tracker
speedtest-tracker    | -------------------------------------
speedtest-tracker    | GID/UID
speedtest-tracker    | -------------------------------------
speedtest-tracker    | 
speedtest-tracker    | User uid:    1000
speedtest-tracker    | User gid:    1000
speedtest-tracker    | -------------------------------------
speedtest-tracker    | 
speedtest-tracker    | 🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...
speedtest-tracker    | 
speedtest-tracker    | 🐇  Configuring Speedtest Tracker...
speedtest-tracker    | 
speedtest-tracker    | 🙄  SQLite database not found, creating...
speedtest-tracker    | touch: cannot touch '/config/database.sqlite': Permission denied
speedtest-tracker    | s6-rc: warning: unable to start service laravel-automations: command exited 1
speedtest-tracker    | /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
speedtest-tracker    | prog: fatal: stopping the container.
```

OS: Ubuntu 22.10 amd64
