### ISSUE TITLE
Container stops due to having lack of permissions

### ISSUE THREAD

**Issue by ZeyoYT** [alexjustesen/speedtest-tracker#498]
### Docker Compose
```
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '4080:80'
            - '4443:443'
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - '/home/pi/Desktop/speedtest-tracker:/config'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
```
### Docker Logs
```
--------------------------------------------------------------------
 _______                       __ __                __
|     __|.-----.-----.-----.--|  |  |_.-----.-----.|  |_
|__     ||  _  |  -__|  -__|  _  |   _|  -__|__ --||   _|
|_______||   __|_____|_____|_____|____|_____|_____||____|
         |__|
 _______                   __
|_     _|.----.---.-.----.|  |--.-----.----.
  |   |  |   _|  _  |  __||    <|  -__|   _|
  |___|  |__| |___._|____||__|__|_____|__|
--------------------------------------------------------------------
To support Speedtest Tracker visit:
https://github.com/alexjustesen/speedtest-tracker
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...
🐇  Configuring Speedtest Tracker...
🙄  SQLite database not found, creating...
touch: cannot touch '/config/database.sqlite': Permission denied
s6-rc: warning: unable to start service laravel-automations: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
```
### Information that might be useful
Hi, i have tried running the compose with docker directly and with portainer and both way i get this issue `touch: cannot touch '/config/database.sqlite': Permission denied`, i dont know whats causing the lack of permissions problem
