### ISSUE TITLE
Test Email & Email Notifications not being received

### ISSUE THREAD

**Issue by blusls79** [alexjustesen/speedtest-tracker#501]
Hi! Great work. Wondering if you can help me with an issue I am experiencing. When I setup the mail notification, I never receive the email. I have checked all spam filters/folders I have and I don't see the email I am expecting when I click the test button in the Mail sections of the notifications page. I am using a known good email configuration via Sendgrid. Which I have setup on other tools and apps I have running in my environm

1. Setup email notification configuration with Sendgrid.
2. Click test email notification button
3. Await test email delivery.

**Expected behavior**
Receive the test email, and email notifications going forward.

**Environment (please complete the following information):**
 - OS: Ubuntu
-  Architecture: arm64
 - Browser chrome
 - Version: Speedtest Tracker v0.11.11

**Screenshots**

**Logs**
Did not see anything in the logs

**Additional context**

**Comment by alexjustesen** [comment]
Couple of additional debugging steps...

1. make sure to "Save" the email address form before clicking "Test"
2. double check your environment config against the docs [here](https://docs.speedtest-tracker.dev/settings/notifications/mail), SMTP is the currently support mail pattern and I'm using Mailgun currently and it's working

**Comment by stephanebob** [comment]
Just to share that I have the same issue. SMTP parameters (that are working on other tools) correctly defined in the /etc/environment fil on ubuntu 22.04, and email of the recipient defined on the page /admin/notifications, and no results when I click on the "test mail channel" button.

**Comment by blusls79** [comment]
Yeah, I have done as suggested. They were already configured. If it helps I am using Portainer. I created my .env file, uploaded it. Restarted my container and still nothing. All I see in the logs is the following message.

04/01/2023 9:30:20 AM
[2023-04-01 15:30:20] production.ERROR: Connection could not be established with host "mailhog:1025": stream_socket_client(): Unable to connect to mailhog:1025 (Connection refused) {"exception":"[object] (Symfony\\Component\\Mailer\\Exception\\TransportException(code: 0): Connection could not be established with host \"mailhog:1025\": stream_socket_client(): Unable to connect to mailhog:1025 (Connection refused) at /var/www/html/vendor/symfony/mailer/Transport/Smtp/Stream/SocketStream.php:154)

![image](https://user-images.githubusercontent.com/50538328/229299480-e2daf49c-e529-40ce-8bef-9c5f0f978c9d.png)

**Comment by alexdelprete** [comment]
As you can see, it's connecting to `mailhog:1025`, not to `smtp.sendgrid.net`, this tells you it's not reading the .env file, probably because it's being created in the wrong folder.

It has to be in the folder that you mapped `/config` to.

Use a docker-compose file, it's much easier, and you can define the variables directly there vs the  .env file.

As an example, here's mine:

```yaml
version: '3.3'
services:
  speedtest-tracker:
    image: ghcr.io/alexjustesen/speedtest-tracker:v0.11.12
    container_name: speedtest-tracker
    restart: unless-stopped
    ports:
      - 8008:443
    environment:
      TZ: Europe/Rome
      PUID: 1000
      PGID: 1000
      DB_CONNECTION: mysql
      DB_HOST: mariadb.domain.dom
      DB_PORT: 3306
      DB_DATABASE: speedtest_tracker
      DB_USERNAME: ****
      DB_PASSWORD: ****
      TELEGRAM_BOT_TOKEN: '****:****'
    volumes:
      - $PWD/config:/config
      - $PWD/certs:/etc/ssl/web
```
