### ISSUE TITLE
There seems to be a failure in checking the web server + PHP-FPM.

### ISSUE THREAD

**Issue by savvasdalkitsis** [alexjustesen/speedtest-tracker#506]
**Describe the bug**
Docker image won't start.

**To Reproduce**
Running docker image on Ubuntu 22.04.1 LTS won't start due to attached logs

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS
-  Architecture: amd64

**Logs**
Logs attached:
[logs.txt](https://github.com/alexjustesen/speedtest-tracker/files/11023488/logs.txt)

**Comment by savvasdalkitsis** [comment]
this is the docker compose snippet i'm deploying:

```

  speedtest:
    container_name: speedtest
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/London
    image: ghcr.io/alexjustesen/speedtest-tracker:latest
    labels:
      traefik.enable: "true"
      traefik.http.routers.speedtest.entrypoints: websecure
      traefik.http.routers.speedtest.middlewares: chain-oauth@file
      traefik.http.routers.speedtest.rule: Host(`**********`)
      traefik.http.routers.speedtest.service: speedtest
      traefik.http.routers.speedtest.tls: "True"
      traefik.http.routers.speedtest.tls.certresolver: letsencryptresolver
      traefik.http.services.speedtest.loadbalancer.server.port: '8080'
    volumes:
    - /services/service/speedtest/data:/config:rw
```

It seems correct to me unless i'm being blind and missing something obvious.
