### ISSUE TITLE
[Feature Request] Cron Schedule from specific hour

### ISSUE THREAD

**Issue by ShlomiD83** [alexjustesen/speedtest-tracker#552]
Hi,
Is it possible to config a cron schedule to start from a specific hour (e.g 0 12/4 * * *)?
at the moment it's not possible, an error pops up about a syntax error.

Thanks.

**Comment by hackeysack01** [comment]
this is called stepping in the vixie cron docs 
https://github.com/vixie/cron/blob/master/Documentation/Features.md

**Comment by begna112** [comment]
Just wanted to add that this also should allow formats like `4/10 * * * *` to run every 10 minutes, begining at the 4th minute of the hour.

**Comment by ArthurMitchell42** [comment]
> Hi,
> 
> Is it possible to config a cron schedule to start from a specific hour (e.g 0 12/4 * * *)?
> 
> at the moment it's not possible, an error pops up about a syntax error.
> 
> 
> 
> Thanks.

Plus one on this please

**Comment by alexjustesen** [comment]
> Hi, Is it possible to config a cron schedule to start from a specific hour (e.g 0 12/4 * * *)? at the moment it's not possible, an error pops up about a syntax error.
> 
> Thanks.

@ShlomiD83 circling back on this one since cron came up on another issue recently. Could you do `0 */4 * * *` to achieve every 4 hours?

**Comment by ShlomiD83** [comment]
That's the way I have it set now, the request was if we can run the test from a specific time and then 4 hours.
For example start at 2AM and from there count 4 hours and test again.

**Comment by ArthurMitchell42** [comment]
Hi Alex, 
The issue with starting at midnight and multiple hours after that is that the results are heavily affected by quite a few background tasks like backup processes, downloads etc.
These all start every 4 hours for me and can take up to 1.5 hours to finish. The ideal way to get around this would be to run speed test every 4 hours but offset it by 2 hours to run at 02:00, 06:00 etc.
Thanks,
Arthur

**Comment by alexjustesen** [comment]
Thanks @ArthurMitchell42, didn't really consider that use case but makes complete sense. 

I either don't have as much data as you or I'm spoiled with gigabit symmetric.

**Comment by ArthurMitchell42** [comment]
Oh wow, you are are lucky. The best I can hope for is about 73Mb/s down and 19 up even on a good day. 😀

**Comment by alexjustesen** [comment]
@ShlomiD83 and @ArthurMitchell42 that other package ended up failing the validation criteria. While not ideal for the time being you could pass which hours you want the tests to run like so... `0 2,6,10,14,18,22 * * *`

**Comment by armond1978** [comment]
@alexjustesen Is there any ETA for supporting x/y field format?

**Comment by alexjustesen** [comment]
> @alexjustesen Is there any ETA for supporting x/y field format?

Not at the moment, I haven't been able to find a package that'll help with validation of the expressions with the formats above.

**Comment by bobluck** [comment]
> Just wanted to add that this also should allow formats like `4/10 * * * *` to run every 10 minutes, begining at the 4th minute of the hour.

agree would be nice if this was supported, since everybody in the world is hitting the Speedtest servers at the same time. Would be nice to keep my 15 minute interval starting at 7 minutes after the hour.

**Comment by lnlyssg** [comment]
I wonder if the issues reported in #1260, #1328, #1319 are all linked into the fact everyone is hitting the servers on the hour, every 30 mins etc?

**Comment by ArthurMitchell42** [comment]
Regarding issues of low rates I wonder if adding a "random" variance value on top of the cron schedule might help.
For example, if you set a test every 4 hours, adding a pseudo random value of 60 minutes means the test would trigger at some point during the defined hour but would be substantially less likely to cause a storm of activity at the servers. This would be particularly effective if the randomness went down to seconds rather than units of minutes.
What do we think?

**Comment by hackeysack01** [comment]
or just comply as advertised with the cron syntax that goes back to the 1980's.

This halfassed implementation caused me to stop using this software.

**Comment by alexjustesen** [comment]
## TL;DR

Use the range syntax to achieve an offset schedule, example `4-59/5 * * * *`.

## Deep Dive

Turns out the cron "standard" syntax is anything but consistent. Certain implementations (i.e. Java) support non-standard characters like `/` and others are more strict when it comes to the syntax it considers "valid". 

As far as the syntax `4/5 * * * *` this means "run every 5 minutes, starting at 4 minutes past the hour". So this syntax includes an "offset" for the schedule and would look like `:04, :09, :14, :19` etc.

If we used the range syntax `4-59/5 * * * *` this means "run every 5 minutes, minutes 4 through 59 past the hour". This syntax still includes an offset for the schedule but it's not as clear and would still look like `:04, :09, :14, :19` etc.

![image](https://github.com/alexjustesen/speedtest-tracker/assets/1144087/bf7e87d8-a08b-440b-82ee-85a11bfc66fa)

If you have trouble sleeping at night I suggest taking a look at https://en.wikipedia.org/wiki/Cron. 

Since we finally have a good documented resolution that passes validation to implementing schedules "from" a time (aka an offset) I'm going to close this one out.

**Comment by lnlyssg** [comment]
Could I suggest either a doc/FAQ update and or removing the link to https://crontab.cronhub.io on the settings page? As soon as you open https://crontab.cronhub.io it presents "*/5 * * * *" which gives the syntax error

**Comment by alexjustesen** [comment]
> Could I suggest either a doc/FAQ update and/or removing the link to https://crontab.cronhub.io on the settings page? As soon as you open https://crontab.cronhub.io it presents "*/5 * * * *" which gives the syntax error

Done, added to the FAQ and linked back to this issue and the comment above. I'm going to leave the link to cronhub.io because `*/5 * * * *` "every 5 minutes" is valid, `4/5 * * * *` isn't with the offset.

**Comment by lnlyssg** [comment]
@alexjustesen Would https://crontab.guru be better to link to than https://crontab.cronhub.io/? The former gives a warning for `4/5 * * * *` "Non standard! May not work with every cron."

**Comment by alexjustesen** [comment]
Happy to review a PR, it's probably a better fit.

**Comment by TheGroundZero** [comment]
Looks like https://github.com/alexjustesen/speedtest-tracker/issues/552#issuecomment-2028532010 no longer functions with the new config?

If I try e.g. `1/6` for hours I get a 500 error.
Enabling debugging shows the issue is `/6` considered as an invalid option.
I had to swap to comma-seperated values instead.

**Comment by lnlyssg** [comment]
It's working OK for me with `SPEEDTEST_SCHEDULE=7-59/30 * * * *`

**Comment by TheGroundZero** [comment]
OK, so it appears you need to specify a range.
It was unclear to me from the example that that is required and the `<offset>/<interval>` syntax doesn't work.

`SPEEDTEST_SCHEDULE=37 1/6 * * *`

> **InvalidArgumentException**
> Invalid CRON field value 1/6 at position 1

`SPEEDTEST_SCHEDULE=37 0-23/6 * * *` Works fine

**Comment by mightywomble** [comment]
Seeing as my bug report was closed I will comment here

I have tried every SPEEDTEST_SCHEDULE in my docker compose  none of them work. 

All I’m looking for is a regular speed test that runs hourly. Can anyone help? Do I need to delete and recreate my config folder, I’m not sure this should be this hard?

```
services:
    speedtest-tracker:
        container_name: speedtest-tracker:latest
        ports:
            - 8080:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=************
            - DB_CONNECTION=sqlite
            - SPEEDTEST_SCHEDULE=7-59/30 * * * *
        volumes:
            - /opt/docker/speedtest:/config
            - /opt/docker/speedtest//ssl-keys:/config/keys
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
```

**Comment by mpaw** [comment]
@mightywomble `SPEEDTEST_SCHEDULE=0 */1 * * *` will run it every hour on the hour

**Comment by mightywomble** [comment]
ChangedDocker compose restart Made no differenceI will delete all the config start again and see if that makes a differenceSent from my iPadOn 9 Jul 2024, at 07:43, Marcin Pawelek ***@***.***> wrote:﻿
@mightywomble SPEEDTEST_SCHEDULE=0 */1 * * * will run it every hour on the hour

**Comment by lnlyssg** [comment]
@mightywomble What exactly is the issue? Is the test not running at all with the schedule?

**Comment by mightywomble** [comment]
CorrectI am expecting the test it’s the above to run hourly, its not running at all on a schedule It runs ok manuallySent from my iPadOn 9 Jul 2024, at 09:28, Jim ***@***.***> wrote:﻿
@mightywomble What exactly is the issue? Is the test not running at all with the schedule?

**Comment by lnlyssg** [comment]
Do you see the "Next speedtest at:" info on the admin dashboard?
<img width="432" alt="Screenshot 2024-07-09 at 10 23 46" src="https://github.com/alexjustesen/speedtest-tracker/assets/10902647/9d4f54ec-0e41-455f-90bf-e52ce9ac295f">

Does the Results table show any tests other than the manual ones?

**Comment by mightywomble** [comment]
No I don't see Next Speed test at:
The results table ONLY shows manual runs
Get BlueMail <https://bluemail.me> for Desktop
Jim wrote:
Do you see the "Next speedtest at:" info on the admin dashboard?
Screenshot.2024-07-09.at.10.23.46.png (view on web) <https://github.com/alexjustesen/speedtest-tracker/assets/10902647/9d4f54ec-0e41-455f-90bf-e52ce9ac295f> 
Does the Results table show any tests other than the manual ones?

**Comment by mightywomble** [comment]
I have deleted the previous volumes and started afresh with this

Using this docker-compose.yaml
```
services:
    speedtest-tracker:
        container_name: speedtest-tracker:latest
        ports:
            - 8080:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=base64:0C4V84+cnlztGJDjmj8jTzSo2pmY7frk9NRpniS+1yU=
            - DB_CONNECTION=sqlite
            - SPEEDTEST_SCHEDULE=0 */1 * * *
        volumes:
            - /opt/docker/speedtest:/config
            - /opt/docker/speedtest//ssl-keys:/config/keys
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
```

I ran 

```
docker compose pull
docker compose start

```

This resulted in the following dashboard

![image](https://github.com/alexjustesen/speedtest-tracker/assets/21082180/18e2179b-145d-4907-ac32-48bd75cd42b6)
