### ISSUE TITLE
Running multiple instances

### ISSUE THREAD

**Issue by jtambasco** [alexjustesen/speedtest-tracker#555]
**Describe the bug**
In docker-compose, I have made two instances of speedtest-tracker in a docker-compose:
```
speedtest-tracker:
      container_name: speedtest_tracker
      ports:
          - 6543:80
          - 6443:443
      environment:
          - PUID=1000
          - PGID=1000
      volumes:
          - ./speedtest-tracker:/config
      image: ghcr.io/alexjustesen/speedtest-tracker:latest
      restart: unless-stopped

speedtest-tracker-gluetun:
      container_name: speedtest_tracker_gluetun
      environment:
          - PUID=1000
          - PGID=1000
      volumes:
          - ./speedtest-tracker-gluetun:/config
      image: ghcr.io/alexjustesen/speedtest-tracker:latest
      network_mode: service:gluetun
      restart: unless-stopped
```

One of them is to report the speed of my home network, while the other is to report the speed of my home network via some VPN configured in gluetun.  It works quite well, with both instances accessible via their respective http(s) ports.  When I open both instances at the same time, the web browser forces me to refresh the webpage of one of the instances, and proceeds to log me out of that instance.  It then takes a couple of tries to re-log back into that instance, before one of the instances again logs out.  The problem only happens if I open both instances.

I assume this is a bug?

**Expected behaviour**
Not get logged out when opening 2 instances.
_or_
I guess a workaround would be if somehow the one instance was able to check the speed of both networks, but this sounds like it'd be a lot of work.

**Environment**

- OS: Manjaro
- Architecture: amd64
- Browser: Chrome
