### ISSUE TITLE
Telegram notification do not appear to be working

### ISSUE THREAD

**Issue by rossman-home** [alexjustesen/speedtest-tracker#636]
**Describe the bug**

Telegram notifications to not appear to be working.  Tested once, started over to verify.  No notifications have come through.  

**To Reproduce**

Created new bot, added bot token to environment variable list, restarted session to verify via 'printenv' that the token was listed correctly, and messaged the bot.  Attempted to run a speed test and I am not getting a notification on Telegram

**Expected behavior**
Notification to appear in Telegram

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu] Linux Mint
-  Architecture: [e.g. arm64, amd64] amd64
 - Browser [e.g. chrome, safari] chr
 - Version [e.g. v1] Mint 21.1, Speedtest Tracker 0.11.17

**Screenshots**

![telegram notification](https://github.com/alexjustesen/speedtest-tracker/assets/123216252/02d756b1-73a1-467d-9eca-462aa780e305)
![botcreation](https://github.com/alexjustesen/speedtest-tracker/assets/123216252/34a24652-3ba0-4d5d-84ec-af044a52db82)
![Telegram token](https://github.com/alexjustesen/speedtest-tracker/assets/123216252/7fdaa97e-9985-47ed-98b6-3a2be87806df)
![username](https://github.com/alexjustesen/speedtest-tracker/assets/123216252/901502a0-7ec5-4a75-9f9e-9319a84a1237)

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**

**Comment by m-primo** [comment]
I have the same issue, it sounds like the `.env` file is not updating or cached or whatever, for me I get:

```
No Telegram bot provided.
You need to add "TELEGRAM_BOT_TOKEN" in your .env file or add it as environment variable
```

Even though I have added a valid bot token that has been tested on a different platform.

The same problem with mail, but for mail it shows mail sent and it's not sent.

**Comment by alexdelprete** [comment]
Where do you have the .env file? It must be in the /config volume mapped directory.

If using docker-compose, put environment variables directly in the docker-compose.yml file. That's how I have configured it, and telegram/mail notifications are working perfectly fine:

```yaml
version: '3.3'
services:
  speedtest-tracker:
    image: ghcr.io/alexjustesen/speedtest-tracker:v0.11.17
    container_name: speedtest-tracker
    restart: unless-stopped
    environment:
      TZ: Europe/Rome
      PUID: 1000
      PGID: 1000
      DB_CONNECTION: mysql
      DB_HOST: xxxx.yyy.dom
      DB_PORT: 3306
      DB_DATABASE: speedtest_tracker
      DB_USERNAME: speedtest
      DB_PASSWORD: x8h5yoda
      TELEGRAM_BOT_TOKEN: 'xxxxxxxxxxxxxxxxxxxxxxxxxx'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/config:/config
      - $PWD/certs:/etc/ssl/web
    ports:
      - 8008:443
```
