### ISSUE TITLE
500 on /admin/results

### ISSUE THREAD

**Issue by pud-micha** [alexjustesen/speedtest-tracker#648]
**Describe the bug**

**To Reproduce**
1. Go to http://192.168.99.xxx/admin/general)
2. See error: 500

**Expected behavior**
Some page

**Environment (please complete the following information):**
 - OS-Server: LXC Ubuntu 23.04 on Proxmox 7.4, 6 GB HDD, 2 GB RAM, 2 Cores
-  Architecture-Server: AMD64
 - OS-Client: Win 10
 - Browser-Client: any
 - Version 0.11.17

**Screenshots**
![image](https://github.com/alexjustesen/speedtest-tracker/assets/98957254/66bc4ebd-87c3-4a36-a0ec-b55a7dc4a5a1)

**Logs**
dont know there to find

**Additional context**
docker-compose.yml

```
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 80:80
            - 443:443
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - '/docker/speedtest-tracker:/config'
            - '/docker/speedtest-tracker/web:/etc/ssl/web'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
```

I've tried SQlite, MySQL, ProgressDB. Everytime the same problem.

Running a speedtest ends always as not successful.
