### ISSUE TITLE
Dashboards are always presented in GMT

### ISSUE THREAD

**Issue by synfinatic** [alexjustesen/speedtest-tracker#659]
**Describe the bug**
No matter what I set `TZ` to in the environment or `General -> Timezone` in the UI, the dashboard always displays graphs and the "last speed run" in GMT.

**To Reproduce**

Look at the dashboard.

**Expected behavior**
The dashboard to honor the timezone set.

**Environment (please complete the following information):**
 - OS: Linux
-  Architecture: amd64
 - Browser:  safari
 - Version: v0.11.17

**Screenshots**

Notice current local time in upper right corner, but time showing in the dashboard:
<img width="1737" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/1075352/d83f3eb8-4cac-4d9e-9d8b-230094a7461a">

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**

**Comment by alexdelprete** [comment]
This has already been discussed in other issues, please read this: https://github.com/alexjustesen/speedtest-tracker/issues/649#issuecomment-1614281059

I submitted a PR for the installation doc: https://github.com/alexjustesen/speedtest-tracker-docs/pull/14

**Comment by synfinatic** [comment]
This is my `docker-compose.yaml` which seems to incorporate that change already?

```yaml
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        ports:
#            - '8080:80'
#            - '8443:443'
             - 8765:80
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Los_Angeles
            - TELEGRAM_BOT_TOKEN=XXXXXX
            - APP_URL=http://oban.int.synfin.net:8765
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/volume1/docker/speedtest/config:/config'
            - '/volume1/docker/speedtest/web:/web'
        restart: unless-stopped
        networks:
            CustomBridge:
                ipv4_address: 172.17.0.12


networks:
    CustomBridge:
        external: true
```

**Comment by alexdelprete** [comment]
Indeed. But you didn't mention that in the OP. :)

I don't know, every time there's an issue on time in the UI or cron schedules, that was the problem.

The default of ST is UTC, are you sure the setting of TZ in the UI are correct? Another strange thing I noticed in your OP screenshot: times are reported in 24h format...I expect that to be in am/pm format for America.

**Comment by synfinatic** [comment]
```
$  docker-compose exec speedtest-tracker date
Mon Jul 17 17:11:03 PDT 2023
```

<img width="932" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/1075352/65eb3071-a64a-4269-b3bd-a7c4ff9feee0">

**Comment by alexdelprete** [comment]
Yeah...I forgot about the time format setting. :)

Change TZ in the UI to Boston and see if something changes...

**Comment by synfinatic** [comment]
Changed the UI to `Americas/New_York` (since there is no Boston) and the time moved forward by +3 hours... which is 3 hours ahead of my TZ.  Of course it is not actually 3am in New York either so it's also wrong.

**Comment by alexdelprete** [comment]
I didn't expect that to fix the problem, just wanted to see if the UI TZ was working correctly, and it does. But in some way it's stuck to UTC as the baseline.

I'm out of advices: the container is set correctly (PDT is your timezone as shown by the date command), TZ env too, so it should work as expected.

I'll pass this to @alexjustesen since I'm out of ideas.

**Comment by synfinatic** [comment]
thanks for the help @alexdelprete

**Comment by alexdelprete** [comment]
Sorry I couldn't help you much...:(

I was also thinking about an .env file lying around, but docker-compose should have priority over .env variables...

**Comment by synfinatic** [comment]
So that last thing about New York giving me a +3 offset gave me an idea.

I removed the `/etc/localtime` volume and set my `TZ=UTC`.  then in the UI I set the timezone to `Americas/Los_Angeles` and now it works. :). So yeah, you did help!

**Comment by alexdelprete** [comment]
good lateral thinking. :)

but that's not what docs say you should do...so there's a bug somewhere...in the docs, or in the sw. :)

Can you show the date command output as you did previously?

**Comment by synfinatic** [comment]
```
$ docker-compose exec speedtest-tracker date
Tue Jul 18 00:43:33 UTC 2023
```

**Comment by alexdelprete** [comment]
try to configure TZ env in docker-compose to America/Los_Angeles again, date command again, then check the UI again. Basically, we're only excluding localtime. :)

**Comment by synfinatic** [comment]
For giggles, I added back the `TZ=Americas/Los_Angeles` and tested.   Same result.  `date` returns UTC, and UI tracks the setting in the UI.  so the issue seems to be with `/etc/localtime`

**Comment by alexdelprete** [comment]
That's what I suspected: TZ is not having any effect on the container's configuration. You configured LA, but date still gives you UTC.

Last test: remove TZ from docker-compose too. ;)

**Comment by synfinatic** [comment]
Okay, gotta take it back a bit.

The issue is still with `/etc/localtime`.

But I made a mistake:

```yaml
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        ports:
#            - '8080:80'
#            - '8443:443'
             - 8765:80
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Los_Angeles
            - TZ=UTC
            - TELEGRAM_BOT_TOKEN=XXXXX
            - APP_URL=http://oban.int.synfin.net:8765
        volumes:
#            - '/etc/localtime:/etc/localtime:ro'
            - '/volume1/docker/speedtest/config:/config'
            - '/volume1/docker/speedtest/web:/web'
        restart: unless-stopped
        networks:
            CustomBridge:
                ipv4_address: 172.17.0.12


networks:
    CustomBridge:
        external: true
```

Notice I set `TZ` twice... and the latter won.  Correctly setting `TZ=Americas/Los_Angeles`:


```
$ docker-compose exec speedtest-tracker bash
root@4ee52e1e873c:/var/www/html# echo $TZ
America/Los_Angeles

root@4ee52e1e873c:/var/www/html# date
Mon Jul 17 17:56:15 PDT 2023
```

Dashboard seems to correctly honor the timezone config in the UI (tested with Los Angeles, UTC and New York).

**Comment by alexdelprete** [comment]
I removed TZ and localtime from docker-compose and to my surprise, last test result jumped from 02:25 to 04:25 (in the future). :)

![image](https://github.com/alexjustesen/speedtest-tracker/assets/7027842/80cf6c79-2d8a-49d0-816a-df30b03ab2a2)

Data is stored in the database correctly, with timestamps in UTC:

![image](https://github.com/alexjustesen/speedtest-tracker/assets/7027842/7a2b6041-5806-4400-9f33-4035b8d8e2d8)

So in the UI it should simply apply the db record timestamp (UTC) and apply the user's configured TZ in the General Settings.

But it shows 04:25 for me, instead of the correct 02:25.

So in principle, it shouldn't need any TZ or localtime set in the docker-compose file...

Let me try re-adding localtime again in docker-compose...

**Comment by alexdelprete** [comment]
Can you test this? I have TZ only in docker-compose, without localtime...and the difference is there:

```
â¯ docker exec -it speedtest-tracker date
Tue Jul 18 03:15:20 CEST 2023
â¯ docker exec -it speedtest-tracker cat /etc/localtime
TZif2UTCTZif2UTC
UTC0
```

**Comment by alexdelprete** [comment]
Readding /etc/localtime fixed my last result:

![image](https://github.com/alexjustesen/speedtest-tracker/assets/7027842/8d24defb-0e73-4df9-89f5-59884a19ef69)

And `date` is consistent with `localtime`, obviously:

```console
> docker exec -it speedtest-tracker date
Tue Jul 18 03:21:53 CEST 2023

> docker exec -it speedtest-tracker cat /etc/localtime
LMTRMTCESTCET
CET-1CEST,M3.5.0,M10.5.0/3
```

**Comment by alexdelprete** [comment]
Ok, now I have only localtime mapped and all UI times are correct. TZ not needed for me, but localtime is.

```console
❯ docker exec -it speedtest-tracker bash

root@24f515afefe9:/var/www/html# echo $TZ

root@24f515afefe9:/var/www/html# date
Tue Jul 18 03:33:31 CEST 2023

root@24f515afefe9:/var/www/html# cat /etc/localtime
LMTRMTCESTCET
CET-1CEST,M3.5.0,M10.5.0/3
```

Test without TZ and localtime: times were off +2h
Test with TZ only: times were off +2h
Test with localtime only: times are correct

If you could do the same 3 tests we could maybe find some pattern...:)

**Comment by synfinatic** [comment]
No.  The problem happens for me every time I add `/etc/localtime`.  Doesn't matter if `TZ` is set or not.  Just `/etc/localtime`.

Random guess to explain the inconsistency: I'm using `SQLite` and you're using a different DB.

**Comment by alexdelprete** [comment]
That might explain it. Maybe sqlite stores timedates differently, I don't know...but @alexjustesen might shed some light on this.

Warning: in future versions ST will drop support for sqlite, so if you're starting collecting data, I'd suggest you start with mysql/mariadb so you don't have to migrate data.

**Comment by synfinatic** [comment]
:(  really, SQLite is probably all something like this needs???  How about PostgreSQL?  I've stopped using mysql/etc years ago.

**Comment by alexdelprete** [comment]
problem is not the app...but many users failing to configure permissions properly so a lot of open issues about container not starting up etc.

PostgreSQL might be a proper FR, open an issue about it so @alexjustesen can evaluate it.

**Comment by synfinatic** [comment]
No clue about permissions.  I just started the container and it worked as expected.

As for a FR, isn't PG already supported per the docs???

**Comment by alexdelprete** [comment]
> I just started the container and it worked as expected.

Yes, that's because you have PUID/PGID set to a userid that has proper access to the folder where the sqlite file has been created. Many people don't.

PG is supported? Gee...I forgot about that. You're good then. :)

**Comment by peterzolczer** [comment]
I have the same problem. TZ is set to my timezone, /etc/localtime is mapped, UI TZ is set to my timezone, too, but results are displayed in GMT. In my case, it's as if the UTC+2 "was ignored" from the time, e.g. in results I see 7:57, when actually it's 9:57 AM CEST (UTC+2).

**Comment by alexdelprete** [comment]
> I have the same problem

Peter, did you read this whole thread? Particularly, last 20 posts. :)

What db are you using?

**Comment by peterzolczer** [comment]
I did, and I'm sorry if I missed something very obvious. Has this issue been already solved?

I'm using PostgreSQL with ST.

**Comment by alexdelprete** [comment]
Well, for me TZ in docker-compose didn't have any effect, but localtime was critical. I use MariaDB.

For @synfinatic localtime created the issue, so he had to remove it to solve it, but he uses sqlite.

You use PostgreSQL, so try removing TZ and localtime, do some tests with all combinations:

- no TZ / no localtime
- TZ=UTC / no localtime
- no TZ / localtime

Let me know...

**Comment by peterzolczer** [comment]
Thank you for the summary, it is fully clear now. I removed the localtime mapping from the volumes section and not the time is correct in the UI. I'll do the remaining tests on Tuesday and report back with the full results.

**Comment by alexdelprete** [comment]
Thanks Peter, let us know so maybe we can revise the documentation.

**Comment by azizLIGHT** [comment]
Removing the /etc/localtime volume from docker-compose.yml worked

```
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8080:80'
            - '8443:443'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
            - TZ=America/New_York
        volumes:
#            - '/etc/localtime:/etc/localtime:ro'
            - '/mnt/nas-proxmox/docker/speedtest-tracker:/config'
            - '/mnt/nas-proxmox/docker/speedtest-tracker/web:/etc/ssl/web'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest_tracker
            - MARIADB_USER=speedy
            - MARIADB_PASSWORD=password
            - MARIADB_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
volumes:
  speedtest-db:
```
