### ISSUE TITLE
Trying to install via docker into a debian system and getting no response

### ISSUE THREAD

**Issue by zezretro** [alexjustesen/speedtest-tracker#664]
**Describe the bug**
I have used docker compose to try and install. Compose gives no errors and the container starts successfully. However when I try and hit the external http port I get nothing and when I goto portainer and look at the logs it shows no logs. I can access the containers console but I dont know where to look for log info

Here is my docker compose file. I am using postgres here but also started with sqllite to the same result. The postgres container appears to the up and the logs for that container confirm this

The local directories /root/speedtest/config and /root/speedtest/web exist but are empty

Anything I should look at to start?

```
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8080:80'
#            - '8070:443'
        environment:
            - PUID=0
            - PGID=0
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
            - TZ=Europe/Tallinn
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /root/speedtest/config:/config
            - /root/speedtest/web:/etc/ssl/web
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: postgres:15
        container_name: speedtest-postgres
        restart: always
        environment:
            - POSTGRES_DB=speedtest_tracker
            - POSTGRES_USER=speedy
            - POSTGRES_PASSWORD=password
        volumes:
            - /root/speedtest/db:/var/lib/postgresql/data
```

**Comment by alexdelprete** [comment]
Unfortunately on startup the container initialization process takes a while (2 to 5 minutes, depending on the hardware), you need to be patient.

As soon as it completes, you'll see the logs through `docker logs speedtest-tracker` command. If you don't see any log it means it didn't complete the startup phase yet.

From what I could analyze, it seems to be a problem with php-fpm...at startup I can see php-fpm process hitting the cpu with various processes for quite some time...as soon as it finishes, the container starts and I can see the log.

On RPi platform this can last many minutes, unfortunately. I already told @alexjustesen about this.

If you don't see the logs...it means the container didn't start, so you can't hit the http port.

**Comment by zezretro** [comment]
This is helpful thank you. I went back to my container and it still doesn't work but now I see error logs telling me to run it as another user/group beside root.

All good, I can work on this issue. Thank you for pointing this out

**Comment by alexdelprete** [comment]
> now I see error logs telling me to run it as another user/group beside root

That's a good advice. I run it wih user id 1000, and chown the mapped folders/subfolders (`$PWD/config` and `$PWD/certs`) to user 1000:

```
version: '3.3'
services:
  speedtest-tracker:
    image: ghcr.io/alexjustesen/speedtest-tracker:v0.11.17
    container_name: speedtest-tracker
    restart: unless-stopped
    ports:
      - 8008:443
    environment:
      #TZ: Europe/Rome
      PUID: 1000
      PGID: 1000
      DB_CONNECTION: mysql
      DB_HOST: yyyyyyyy
      DB_PORT: nnnnn
      DB_DATABASE: speedtest_tracker
      DB_USERNAME: yyyyyyyyy
      DB_PASSWORD: xxxxxxxxxx
      TELEGRAM_BOT_TOKEN: 'xxxxxxxxxxx'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/config:/config
      - $PWD/certs:/etc/ssl/web

```
