### ISSUE TITLE
Revisit #519 ? (ports 80/443)

### ISSUE THREAD

**Issue by luckman212** [alexjustesen/speedtest-tracker#673]
I read https://github.com/alexjustesen/speedtest-tracker/issues/519 and I saw it was closed. Fair enough. 

I just want to mention, in my case I set up speedtest-tracker on my Synology nas, which binds to ports 80 and 443 and makes it very difficult to change.

The container runs fine in "bridge" network mode, using the internal Docker network. However **there's a ~15% performance hit** when running this way, so my speedtest results are not quite accurate.

I'd like be able to run in "host" mode, where the container sits directly on the wire, but this doesn't seem possible unless we can have nginx listen on another port. Is there any chance for this to be revisted?

**Comment by KossikCZ** [comment]
@luckman212 Hi Luke, just out of my curiosity what speed of line are you running this on? I have the same setup on my DS218+ with the bridge mode but get my full 500Mbit/s just fine.

**Comment by luckman212** [comment]
@KossikCZ I'm using a DS1621+ and it's attached to a gigabit fiber connection. I'm seeing ~810Mbit from the container vs 920 when running iperf "outside".

**Comment by KossikCZ** [comment]
@luckman212 Ah, so perhaps it only hits the limit when close to 1Gb/s. Tx a lot, good to know.

**Comment by alexjustesen** [comment]
> @KossikCZ I'm using a DS1621+ and it's attached to a gigabit fiber connection. I'm seeing ~810Mbit from the container vs 920 when running iperf "outside".

I have gig fiber as well so I'll test this on my DS920+. @KossikCZ are you running a bonded connection on your NAS or just a single network connection?

**Comment by alexjustesen** [comment]
@luckman212 @KossikCZ Dug into this a little more, I was able to reach my theoretical speeds during a speedtest on a bridge network using the following `docker-compose.yml` file. I think you hit a limitation of your NAS or your network which is preventing the full speeds as it "works for me" (famous last words).

```
version: '3.3'
services:
    app:
        container_name: speedtest-tracker
        ports:
            - '8080:80'
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=base64:allthatbasethatbasethatbase
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
            - TZ=America/New_York
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - speedtest-app:/config
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest_tracker
            - MARIADB_USER=speedy
            - MARIADB_PASSWORD=password
            - MARIADB_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
volumes:
    speedtest-app:
    speedtest-db:

```

Going to close this out as I don't think it's an app limitation.
