### ISSUE TITLE
Adminpage broken via ipv6

### ISSUE THREAD

**Issue by maximizzar** [alexjustesen/speedtest-tracker#683]
When visiting the speedtest-tracker adminpage via the ipv6 address of the dockerhost system, only rudimentary html and icons load. Markup and style aren't working. Access the adminpage via the ipv4 address of the dockerhost system everything ist working.

## Reproduce
1. setup debian 12 with docker on it (it's a privilied lxc in my case)
2. Setup ipv6 in /etc/docker/daemon.json
3. use docker-compose.yaml
4. browse to http://ipv6.docker.host.system:8080/admin and to http://ipv4.docker.host.system:8080/admin

### /etc/docker/daemon.json
```yaml
{
  "default-runtime": "nvidia",
  "runtimes": {
    "nvidia": {
      "path": "/usr/bin/nvidia-container-runtime",
      "runtimeArgs": []
    }
  },
  "ipv6": true,
  "fixed-cidr-v6": "fdf0:f340:633a::/48",
  "experimental": true,
  "ip6tables": true,
  "registry-mirrors": [
    "https://registry.ipv6.docker.com"
  ]
}
```

### docker-compose.yaml
```yaml
version: '3.9'

# http port: 80
# https port: 443
#api port: 9000

name: 'speedtest-tracker'

networks:
  default:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 'fdc5:db8b:6316::/48'

services:
  app:
    depends_on:
      - db
    environment:
      DASHBOARD_POLLING: 60
      DB_CONNECTION: 'pgsql'
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: 'speedtest_tracker'
      DB_USERNAME: '${POSTGRES_USER}'
      DB_PASSWORD: '${POSTGRES_PASSWORD}'
      PGID: 1000
      PUID: 1000
      TZ: 'UTC'
    hostname: 'speedtest-tracker'
    image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
    ports:
      - '8080:80'
      - '9000:900'
    restart: unless-stopped
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - 'app:/config'
      # - '/path/to/directory/web:/etc/ssl/web'
  db:
    image: 'postgres:15'
    restart: 'unless-stopped'
    environment:
     POSTGRES_DB: 'speedtest_tracker'
     POSTGRES_USER: '${POSTGRES_USER}'
     POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  app:
  db:
```

## Expected behavior
As described above, the admin page works perfectly under ipv4. It would be desirable to see the same behavior under ipv6.

## Environment
- privileged lxc debian 12 container with docker
-  Architecture: amd64
 - Client Win64 Firefox/116.0
 - Version v0.11.17

## Screenshots

![ipv6-page](https://github.com/alexjustesen/speedtest-tracker/assets/60427093/d2d7182f-b074-4d11-be88-55c94a2fe415)

![ipv4-page](https://github.com/alexjustesen/speedtest-tracker/assets/60427093/99e7fce6-4a70-482e-b4f5-43d9d6c8f24c)

**Comment by alexjustesen** [comment]
At this time I believe ipv6 isn't supported in the base container. I'll look into enabling it

**Comment by alexjustesen** [comment]
@maximizzar taking another look at this and ipv6 should work but it's likely that your `APP_URL=` needs to be set if you're behind a load balancer. Looks like from the screenshots it was just the assets that didn't load?

**Comment by maximizzar** [comment]
I am try to access the app via http://[2001:db8:1337::42]:http-port. I thought I got it working, but it still won't do it. I now installed it on a ipv6 only lxc with docker and it constantly returns 500 Server Errors and the error below. I also Include the [lxc.conf.txt](https://github.com/alexjustesen/speedtest-tracker/files/12520334/lxc.conf.txt), used was an debian 12 template.

### [logs.txt](https://github.com/alexjustesen/speedtest-tracker/files/12520191/logs.txt)

The following error I only got constantly when in my v6-only environment. I hope this helps to narrow it down (a few runs out of 20-30 worked till restart). 
```
[2023-09-05 07:26:46] production.ERROR: No application encryption key has been specified. {"exception":"[object] (Illuminate\\Encryption\\MissingAppKeyException(code: 0): No application encryption key has been specified. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79)
```

**Comment by alexjustesen** [comment]
So you'll want to pass `APP_KEY=base64:somekeygoeshere`, you can take the value for this environment variable out of your old `.env` file in the mounted `/config` folder or inside the container run `php artisan key:generate --show` and use that value.

**Comment by maximizzar** [comment]
Unfortunately, I have to admit that this is largely due to an error on OSI layer eight. The rest is dns. How I got speedtest-tracker fully working on ipv6, I stated below.

The errors I had come possibly from the .env file I used to store the db-password and name in. I don't know why and how, but setting those values in the docker compose directly solved all the problems I had.

## speedtest-tracker ipv6-setup
- Have an ipv6 host system with docker.
- define a default network with ipv6 support inside the docker compose file.
- If your subnet is in a local range, you can just copy my docker daemon.json file.
- to speedtest over v6, modify the "www.speedtest.net" record to be an "AAAA-record" for "2a04:4e42:600::731" or if you're able to just CNAME it to ipv6.speedtest.net.

### get it working - examples
 Here's how I've done it. First, make docker ipv6 capable. There are different ways, just check the docs at [docker.io](https://docs.docker.com/config/daemon/ipv6/).
```yaml
{
  "ipv6": true,
  "fixed-cidr-v6": "fde2:2ea7:0715::/48",
  "experimental": true,
  "ip6tables": true
}
```

Secondly, we have the docker-compose yaml. Use the default one and add the networks section.
```yaml
version: '3.3'

networks:
  default:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 'fdad:afd7:46ff::/48'

services:
 ...
```
