### ISSUE TITLE
Slower speed than real speed

### ISSUE THREAD

**Issue by icolumbro** [alexjustesen/speedtest-tracker#811]
I have a VDSL (mixed copper/fiber) connection with a theoretical maximum down/up speed of 200/20 Mbps which translates into an actual speed of around 105/20 Mpbs. Unfortunately Speedtest Tracker never measures a speed higher than 30 Mbps, losing all usefulness. With the henrywhitaker3 version I didn't have the problem.
I use _Nginx Proxy Manager_ as a reverse proxy.
This is my docker-compose.yml file:
```
version: '3.3'

services:
   speedtest-tracker:
     container_name: speedtest-tracker
     image: ghcr.io/alexjustesen/speedtest-tracker:latest
     volumes:
       - /home/icolumbro/docker-stacks/speedtest-tracker:/config
       - /home/icolumbro/docker-stacks/speedtest-tracker/web:/etc/ssl/web
     restart: unless-stopped
     depends_on:
       - db
     networks:
       - nginx-proxy-manager_default

   db:
     image: mariadb:10
     restart: always
     volumes:
       - speedtest-db:/var/lib/mysql
     networks:
       - nginx-proxy-manager_default

volumes:
   speedtest-db:
```
