### ISSUE TITLE
[Traefik2] Login page doesn't work under proxy

### ISSUE THREAD

**Issue by dreamwhite** [alexjustesen/speedtest-tracker#814]
Currently trying to add a reverse proxy to my existing Speedtest Tracker install via `docker-compose.yml` file.

**docker-compose.yml** file:

```yaml
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
            - TELEGRAM_BOT_TOKEN=XXXXXXXXXXX
        volumes:
            - ./config:/config
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: always
        depends_on:
            - db
        networks:
          - web
          - internal
        labels:
          - traefik.enable=true
          - traefik.http.routers.speedtest-tracker.rule=Host(`192.168.1.23`)  && PathPrefix(`/speedtest-tracker`)
          - traefik.http.services.speedtest-tracker.loadbalancer.server.port=80
          - traefik.http.routers.speedtest-tracker.middlewares=speedtest-tracker-strip
          - traefik.http.middlewares.speedtest-tracker-strip.stripprefix.prefixes=/speedtest-tracker
    db:
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest_tracker
            - MARIADB_USER=XXXXXXXXXXXX
            - MARIADB_PASSWORD=XXXXXXXXXXXX
            - MARIADB_RANDOM_ROOT_PASSWORD=true
        volumes:
            - ./var_lib_mysql:/var/lib/mysql
        networks:
          - internal
        labels:
          - traefik.enable=false

networks:
  web:
    external: true
  internal:
    external: false
```

With the above file I can start my Speedtest Tracker instance:

![image](https://github.com/alexjustesen/speedtest-tracker/assets/17933708/29eb9bf1-08b6-407a-bea9-d9b25a76c3fb)

except for that I cannot login: I type my credentials but it doesn't redirect to the dashboard page.

Looking in the Developer Console, it seems that some resources (`livewire.js` and `inter.css`) aren't loaded.

Is there any chance of fixing it?

Thanks in advance
dreamwhite
