### ISSUE TITLE
consistent ping

### ISSUE THREAD

**Issue by ArthurHuyghe** [alexjustesen/speedtest-tracker#826]
### Description
I would like to propose a new feature that allows users to perform a consistent ping (every 1~5 min 🤷‍♂️)  to websites of their choice, separate from the main speedtest functionality with their own graph. The tool should provide feedback on the ping results for each specified target, including average latency, packet loss, and a timestamp. I also think it should have the ability to notify the user if his internet is down (as far as that's possible if his internet is indeed down...) and if his latency is abnormally high.

**Comment by alexjustesen** [comment]
Something that was absolutely in my backlog and glad to see others wanting the solution. Envisioning something in the UI along with scheduled pings.

**Comment by alexjustesen** [comment]
I'll have to check out SmokePing, definitely don't want to reinvent the wheel

**Comment by alexdelprete** [comment]
Pretty simple to setup. Configuration is all files/dir based:

```
---
version: "2.1"
services:
  smokeping:
    image: ghcr.io/linuxserver/smokeping:2.8.2
    container_name: smokeping
    hostname: smokeping
    restart: unless-stopped
    labels:
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - $PWD/config:/config
      - $PWD/data:/data
    ports:
      - 9080:80
    networks:
      - proxy
networks:
  proxy:
    external: true
```
