### ISSUE TITLE
SQLSTATE[HY000] [1130] Host '172.29.28.3' is not allowed to connect to this      MariaDB server      

### ISSUE THREAD

**Issue by MarkusMory** [alexjustesen/speedtest-tracker#847]
**Describe the bug**
After my vacation I noticed that my speedtest-tracker wasn't working anymore (Error 500). As I was lazy I tried to create a fresh instance. For doing that I used the recommended Docker Compose from the documentation. I just did change the Ports, PUID, PGID, TZ and Volumes.

After the two containers have been created I can see errors in both container logs:

**Speedtest-Tracker:**
In Connection.php line 801:
                                                                               
  SQLSTATE[HY000] [1130] Host '172.29.28.3' is not allowed to connect to this  
   MariaDB server (Connection: mysql, SQL: select * from information_schema.t  
  ables where table_schema = speedtest_tracker and table_name = migrations an  
  d table_type = 'BASE TABLE')                                                 
                                                                               
In Connector.php line 65:
                                                                               
  SQLSTATE[HY000] [1130] Host '172.29.28.3' is not allowed to connect to this  
   MariaDB server                                                              
                                                                               
s6-rc: warning: unable to start service laravel-automations: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.

**DB:**
2023-10-04 11:50:32 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: '172.29.28.3' (This connection closed normally without authentication)
2023-10-04 11:50:44 4 [Warning] Aborted connection 4 to db: 'unconnected' user: 'unauthenticated' host: '172.29.28.3' (This connection closed normally without authentication)

**To Reproduce**
Docker Compose:
```
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '49156:80'
            - '49157:443'
        environment:
            - PUID=1003
            - PGID=100
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
            - TZ=Europe/Berlin
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/share/Container/Container-Shares/speedtest-tracker:/config'
            - '/share/Container/Container-Shares/speedtest-tracker/web:/etc/ssl/web'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: always
        depends_on:
            - db
    db:
        container_name: speedtest-tracker-db
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest_tracker
            - MARIADB_USER=speedy
            - MARIADB_PASSWORD=password
            - MARIADB_RANDOM_ROOT_PASSWORD=true
            - TZ=Europe/Berlin

        volumes:
            - speedtest-db:/var/lib/mysql
volumes:
  speedtest-db:

```
**Expected behavior**
The speedtest-tracker should authenticate itself with the username/password

**Environment (please complete the following information):**
 - OS: QNAP Disk Station V3.0.5.623

**Logs**

[_speedtest-tracker-db_logs.txt](https://github.com/alexjustesen/speedtest-tracker/files/12802073/_speedtest-tracker-db_logs.txt)
[_speedtest-tracker_logs.txt](https://github.com/alexjustesen/speedtest-tracker/files/12802074/_speedtest-tracker_logs.txt)

Thank you very much for your help.

Markus
