### ISSUE TITLE
500 Error after update to version v0.13.1 Latest

### ISSUE THREAD

**Issue by lfac76** [alexjustesen/speedtest-tracker#848]
After an update to version v0.13.1 Latest I recieived the 500 error. I restart the docker, recreate the docker and nothing works. My docker-compose.yml is:

```
---
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8888:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - $PWD/config:/config
        image: ghcr.io/alexjustesen/speedtest-tracker
```

My config/.env file is:

```
APP_NAME="Speedtest Tracker"
APP_ENV=production
APP_KEY=xxx
APP_DEBUG=false
APP_URL=http://localhost

LOG_CHANNEL=stderr
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=sqlite
# DB_HOST=127.0.0.1
# DB_PORT=3306
# DB_DATABASE=speedtest_tracker
# DB_USERNAME=root
# DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database
SESSION_DRIVER=database
SESSION_LIFETIME=120

MAIL_MAILER=smtp
MAIL_HOST=mailhog
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

TELEGRAM_BOT_TOKEN=xxx
```

Any error on the log is:

```
[2023-10-04 10:43:52] production.ERROR: No application encryption key has been specified. {"exception":"[object] (Illuminate\\Encryption\\MissingAppKeyException(code: 0): No application encryption key has been specified. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79)
[stacktrace]
```
