### ISSUE TITLE
Can't send email from "old" container since v0.11.17

### ISSUE THREAD

**Issue by VitreousVein** [alexjustesen/speedtest-tracker#854]
**Describe the bug**
Hi. I wanted to share a problem that i have been facing this week. The setup for the Email-Notifications just does not work for the container i had a while ago. Today I started another container and the Notification just worked. First I thought the problem was an SSL or TLS issue but that was cleared after the new container worked. The log in the original container shows it trying to connect to ``` mailhog:1025 ``` but failing. I don't know the cause and don't know what to try.

**To Reproduce**

1. Go to Notifications Site
2. Click Test mail channel

**Expected behavior**
Receive the Email just like from the new container.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture: amd64
 - Browser: Firefox
 - Version: v0.13.1

**Logs**

- docker compose (both are the same):
```yml
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
          - '8089:80'
          - '8449:443'
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
        volumes:
            - './config:/config'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest_tracker
            - MARIADB_USER=speedy
            - MARIADB_PASSWORD=password
            - MARIADB_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
volumes:
  speedtest-db:
``` 

- error in docker log:
[2023-10-06 22:18:06] production.ERROR: Connection could not be established with host "mailhog:1025": stream_socket_client(): php_network_getaddresses: getaddrinfo for mailhog failed: Name or service not known {"exception":"[object] (Symfony\\Component\\Mailer\\Exception\\TransportException(code: 0): Connection could not be established with host \"mailhog:1025\": stream_socket_client(): php_network_getaddresses: getaddrinfo for mailhog failed: Name or service not known at /var/www/html/vendor/symfony/mailer/Transport/Smtp/Stream/SocketStream.php:154)

- .env file from the original container:
```
APP_NAME="Speedtest Tracker"
APP_ENV=production
APP_KEY=
APP_DEBUG=false
APP_URL=http://localhost
FORCE_HTTPS=false

LOG_CHANNEL=stderr
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=sqlite
# DB_HOST=127.0.0.1
# DB_PORT=3306
# DB_DATABASE=speedtest_tracker
# DB_USERNAME=root
# DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=database
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database
SESSION_DRIVER=database
SESSION_LIFETIME=120

MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=**********
MAIL_PASSWORD=**********
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=**********
MAIL_FROM_NAME="Speedtest Tracker"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

TELEGRAM_BOT_TOKEN=
```

- env file from the new container:
```
# A full list of options can be found in the '.env.example' file.

# Application key
# Used for encryption where needed, if a key is not generated run: php artisan key:generate
APP_KEY=

# Application URL
# Not used in the URL but effects links in emails and notifications: https://docs.speedtest-tracker.dev/faqs#links-in-emails-dont-point-to-the-correct-url
APP_URL=http://localhost

# SMTP mail config
# Only SMTP protocol is supported at this time: https://docs.speedtest-tracker.dev/settings/notifications/mail
MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=**********
MAIL_PASSWORD=**********
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=**********
MAIL_FROM_NAME="Speedtest Tracker"

# Telegram bot config
TELEGRAM_BOT_TOKEN=null
```
