### ISSUE TITLE
New Install: Container Stopping with Fatal Error

### ISSUE THREAD

**Issue by sladester** [alexjustesen/speedtest-tracker#909]
I just installed on a Synology NAS DS423+ using docker compose with Container Manager.

I tried both the Maria DB and postgres installs.  The install starts but is non-responsive via the web.  A check of the log shows that after a bit, the speedtest container (not the DB) is crashing.   Before the crash, the logs show that it is "Migrating the database..." but I never see it end.

Attached are the logs.  Thanks!

[speedtest-tracker.csv](https://github.com/alexjustesen/speedtest-tracker/files/13339288/speedtest-tracker.csv)

**Comment by vincentbls** [comment]
Same problem for me (docker compose with Container Manager.
[speedtest-tracker.csv](https://github.com/alexjustesen/speedtest-tracker/files/13340608/speedtest-tracker.csv)

**Comment by ItJustFox** [comment]
Same here.
I wont post the log because, they are the same has the first one.

**Comment by Deses** [comment]
I'm having absolutely no issues using a dockerized PostgreSQL 14 under Unraid.

**Comment by vincentbls** [comment]
I use MariaDB deployed at the same time as the SpeedTest container.

**Comment by alexjustesen** [comment]
I've got my running on my DS920+ using the following config, let me know if this works for you as it's a section of the docs that needs updating to reference Container Manager.

```
version: '3.3'
services:
    app:
        container_name: speedtest-tracker
        ports:
            - '8080:80'
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=keygoeshere...
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
            - TZ=America/New_York
        volumes:
            - speedtest-app:/config
        image: 'ghcr.io/alexjustesen/speedtest-tracker:v0.13.3'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest_tracker
            - MARIADB_USER=speedy
            - MARIADB_PASSWORD=password
            - MARIADB_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
volumes:
    speedtest-app:
    speedtest-db:
```

Note: `PUID` and `PGID` might be different for you.
