### ISSUE TITLE
Server sent charset (0) unknown to the client

### ISSUE THREAD

**Issue by Beckti** [alexjustesen/speedtest-tracker#932]
**Describe the bug**
Had a automatic update from v0.13.3 to v0.13.4 yesterday and I keep getting an error even when manualy downgrading back to v0.13.3.

**To Reproduce**
1. Create with version v0.13.3
2. Update to v0.13.4
3. Go to the logs

**Expected behavior**
The update should have worked

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
-  Architecture: amd64
 - Browser edge
 - Version v0.13.4

**Screenshots**

**Logs**
Speedtest-tracker:
#35 {main}
"} 
In Connection.php line 822:
                                                                               
  SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Pleas  
  e, report to the developers (Connection: mysql, SQL: select * from informat  
  ion_schema.tables where table_schema = speedtest_tracker and table_name = m  
  igrations and table_type = 'BASE TABLE')                                     
                                                                               
In Connector.php line 65:
                                                                               
  SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Pleas  
  e, report to the developers                                                  
                                                                               
s6-rc: warning: unable to start service laravel-automations: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.

Speedtest-db:
2023-11-27  6:47:06 29 [Warning] Aborted connection 29 to db: 'unconnected' user: 'unauthenticated' host: '192.168.96.3' (This connection closed normally without authentication)

**Comment by alexjustesen** [comment]
Can you also share your `docker-compose.yml` file as well?

Thanks

**Comment by alexjustesen** [comment]
A couple of notes...

1. This volume `/path/to/directory:/config` is incorrect. You'll need to either mount `/config` to a location on your host machine or to another volume (recommended).
2. Remove `TZ` variable and mounted volume `etc/localtime:/etc/localtime:ro` as that's getting removed in the next release anyways

I'm including an updated `docker-compose.yml` file below that you can use to get started.

```
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8080:80'
            - '8443:443'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
        volumes:
            - 'speedtest-app:/config'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest_tracker
            - MARIADB_USER=speedy
            - MARIADB_PASSWORD=password
            - MARIADB_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
volumes:
  speedtest-app:
  speedtest-db:
```
